### ISSUE TITLE
在接口上注解key无法获取到参数值，都是null

### ISSUE THREAD

**Issue by oaoit** [alibaba/jetcache#103]
应该是使用JDK动态代理的问题吧？有没有计划使用cglib替换？

**Comment by areyouok** [comment]
用的就是spring aop，同时支持cglib和jdk proxy。EnableMethodCache注解上可以设置proxyTargetClass属性，和spring是一样一样的。

如果没拿到参数，是不是使用了参数名，但编译的时候javac没有指定-parameters参数。

**Comment by oaoit** [comment]
在MyBatis的Mapper接口上加的注解，@EnableMethodCache的proxyTargetClass = true的。
![image](https://user-images.githubusercontent.com/3363419/41892046-5991b8aa-7949-11e8-9979-b107c0ab1d69.png)
![image](https://user-images.githubusercontent.com/3363419/41892065-69530780-7949-11e8-98b2-6f713431f35b.png)

**Comment by areyouok** [comment]
-parameters参数指定了吗

**Comment by oaoit** [comment]
制定后重新编译运行，还是取不到。
<img width="457" alt="image" src="https://user-images.githubusercontent.com/3363419/41948134-e55a2742-79ed-11e8-9ecb-188899f3ea2b.png">
<img width="313" alt="image" src="https://user-images.githubusercontent.com/3363419/41948155-f92dba0e-79ed-11e8-8681-d977c119fa1b.png">
<img width="526" alt="image" src="https://user-images.githubusercontent.com/3363419/41948167-04e46d48-79ee-11e8-84a3-4610631aedd6.png">

**Comment by JoshShaw** [comment]
贴个方法：
https://www.cnblogs.com/zhangshiwen/p/6022794.html

但是每次运行前如果改了代码，都需要mvn package一下。

**Comment by oaoit** [comment]
ide运行并不需要打包，放到单独的容器里运行，打包也很正常。或者你把编译过的代码拷贝过去。
