### ISSUE TITLE
维护问题

### ISSUE THREAD

**Issue by yhan219** [alibaba/jetcache#104]
框架本身很不错，但目前好像主要维护的只有@areyouok，后期如果作者离职阿里，不知道这个项目有何打算？毕竟缓存框架选型还是比较重要，如果以后没人维护导致需要换框架的话改动会非常大。另外，除了阿里彩票，阿里内部还有其他地方使用jetcache吗？

**Comment by areyouok** [comment]
感谢关注。我已经离职阿里一年有余了。可以看到，这一年来我一直在维护的。

开源软件的重要特点就是没有担保，毕竟代码都在这里了，代码量也不大。同时，我一直维持了较高的代码质量和很高的单元测试覆盖率，这花费了很多时间。issue列表里面，真正涉及bug的issue非常非常少。

最近提交不是很频繁，但是有重大问题肯定是第一时间修正的。兼容性上当前传递的依赖虽然是spring4，boot1.x，但是在spring5和boot2上都测试过，短期没有看到什么重大问题。

以后要做什么，issue列表里面都有讨论。近期要做的都是小优化。设计定位上也是有取舍的，有些功能就一直没有做，比如redis的list、set等支持，原因已经讨论过很多次了。

**Comment by yhan219** [comment]
感谢作者的付出，那我们这边就放心的用了
