### ISSUE TITLE
解惑一下，关于缓存刷新 时 返回旧值的原理

### ISSUE THREAD

**Issue by CrossIce** [alibaba/jetcache#108]
使用redis，这个实现是因为redis的io效率很高 不会存在锁的原因，还是刷新时 会在存储一个新的缓存，等缓存存储完成，key就会指向新存储的缓存，然后删除旧的缓存吗？

**Comment by areyouok** [comment]
你的问题是从#107来的吗？

我的意思是，因为当前刷新任务是scheduleWithFixedDelay，所以，如果刷新间隔是10秒，去数据库加载需要5秒，那么10～15秒的时间段内，缓存里面是旧值。

**Comment by CrossIce** [comment]
这个意思是 15秒之后数据库加载完的数据  会存储到 key指向的旧值的存储地址？如果数据很大 依然会存在io阻塞是吗？

**Comment by areyouok** [comment]
15s的时候数据库加载完毕，然后用put方法更新缓存，更新完毕以后读取到的都会是新值了

**Comment by CrossIce** [comment]
谢谢您的解答，我看到了这个框架支持caffeine，那刷新机制应该是redis或者是caffeine来实现。

**Comment by areyouok** [comment]
自动刷新是jetcache实现的

**Comment by CrossIce** [comment]
我去年用过定时线程来刷新caffeine缓存，来避免缓存穿透问题，要是早点看到您的项目，就不会那么麻烦了

**Comment by areyouok** [comment]
https://github.com/ben-manes/caffeine/wiki/Refresh

caffeine可以自动刷新的。不过jetcache的分布式自动刷新功能更强一些，而且可以指定一段时间没有访问就停止刷新，避免无谓的刷新任务过多。
