### ISSUE TITLE
类型转换异常

### ISSUE THREAD

**Issue by FloriaLI** [alibaba/jetcache#111]
使用encoder/decoder使用java，返回对象结构格式为：
public class MyClass implements Serializable{
    private static final long serialVersionUID = 1L;
    private String a;
    private List<AnotherClass> b;
}
时出现AnotherClass不能被转化为AnotherClass的类型转换异常报错

**Comment by FloriaLI** [comment]
不好意思没打上去。。
private List<AnotherClass> b;
这种

**Comment by FloriaLI** [comment]
bList里面的类型是AnotherClass

**Comment by areyouok** [comment]
以前有反馈过类似的问题，和spring dev tools有关，开发环境会出现，生产环境不会出现。

可以升级到最新版本试试。或者
```
System.setProperty("spring.devtools.restart.enabled", "false");
```

**Comment by FloriaLI** [comment]
好的，尝试了一下，已经不报错了

**Comment by zhuxixi** [comment]
学习了

**Comment by FloriaLI** [comment]
想请问一下redis配置可以支持同一个area里面不同IP和port的配置么？想连接一个主从模式的redis
