### ISSUE TITLE
Concurrency bug in the access time handling

### ISSUE THREAD

**Issue by cruftex** [alibaba/jetcache#112]
Snippet of `AbstractEmbeddedCache.parseHolderResult` :

````
            long accessTime = holder.getAccessTime();
            holder.setAccessTime(now);
            if (config.isExpireAfterAccess()) {
                long expireAfterAccess = config.getExpireAfterAccessInMillis();
                if (now >= accessTime + expireAfterAccess) {
                    return CacheGetResult.EXPIRED_WITHOUT_MSG;
                }
            }
````

And snippet of `CacheValueHolder`:

````
public final class CacheValueHolder<V> implements Serializable {
   // . . .
    private long accessTime;
   // . . .
````

I see two problems here:

- there is no guarantee by the Java Memory Model that the update of the `accessTime` becomes visible to other threads
- the update of a long is non atomic on a 32 bit system

As a quick fix I suggest that `accessTime` is declared `volatile`.

Another solution would be to keep it as-is, but live with the fact that the access time update is "lossy" and entries may expire unintentionally. But I think that the behavior should be deterministic and testable.

**Comment by areyouok** [comment]
Thank you.
I have fixed it in 2.5.5
