### ISSUE TITLE
在application.properties中如何配置呢？

### ISSUE THREAD

**Issue by zjcnb** [alibaba/jetcache#113]
您好，请问在application.properties中如何配置呢？

**Comment by areyouok** [comment]
和yml一样的呀，yml和properties只是同一种内容的不同表现形式

**Comment by zjcnb** [comment]
我在application.properties中配置的时候，根本没有提示jecache相关的信息，jar包我已经引入

**Comment by areyouok** [comment]
贴一下你的配置和具体问题

**Comment by zjcnb** [comment]
jetcache.statIntervalMinutes=15
jetcache.areaInCacheName=false
jetcache.local.default.type=linkedhashmap
jetcache.local.default.keyConvertor=fastjson
jetcache.remote.default.type=redis
jetcache.remote.default.keyConvertor=fastjson
jetcache.remote.default.valueEncoder=java
jetcache.remote.default.valueDecoder=java
jetcache.remote.default.poolConfig.minIdle=5
jetcache.remote.default.poolConfig.maxIdle=20
jetcache.remote.default.poolConfig.maxTotal=50
jetcache.remote.default.host=127.0.0.1
jetcache.remote.default.port=6379

**Comment by areyouok** [comment]
信息不足没法判断哦
