### ISSUE TITLE
请问jetcache @CacheUpdate 更新缓存的策略是什么？

### ISSUE THREAD

**Issue by liuhaozzu** [alibaba/jetcache#115]
请问通过@CacheUpdate(name="userCache-", key="#user.userId", value="#user")注解的方法在更新数据时，更新缓存的策略是什么？
1，先淘汰缓存---》更新数据库---》更新缓存
2，更新数据库---》淘汰缓存
是1还是2？
另外，更新缓存失败时，有重试策略吗？或者有相应的重试策略接口吗？

**Comment by areyouok** [comment]
方式2，如果要失效缓存有专门的另外一个注解CacheInvalidate。
实际上1和2严格说都是有问题的，应该先操作数据库，再失效比较好。
目前没有重试，有需求的可以通过CreateCache拿到缓存实例自己做 。
