### ISSUE TITLE
jetcache中的连接池和Springboot中redisTemplate的连接池如何整合？

### ISSUE THREAD

**Issue by ling49043171** [alibaba/jetcache#117]
背景：
   当前我的项目中用到了jetcache，另外也用到了Spring boot中的redisTemplate

jetcache方面，我的配置如下：
`jetcache:

      statIntervalMinutes: 15
      areaInCacheName: false
      local:
          default:
               type: linkedhashmap
               keyConvertor: fastjson
               limit: 100
      remote:
           default:
               type: redis
               keyConvertor: fastjson
               valueEncoder: java
               valueDecoder: java
               poolConfig:
                    maxTotal: 200
                    minIdle: 10
                    maxIdle: 50
                host: 127.0.0.1
                port: 6379
                database: 1
`

这里的redis连接池，应该是jetcache自己创建的（另外jetcache里的连接池其他配置项也太清楚支持有哪些）。

下面是我的redisTemplate连接池配置：
`
@Configuration
public class RedisConfig {

    private RedisProperties redisProperties;
    public RedisConfig(RedisProperties redisProperties) {
        this.redisProperties = redisProperties;
    }

    @Bean
    public JedisPoolConfig jedisPoolConfig () {
        JedisPoolConfig config = new JedisPoolConfig();
        config.setMaxTotal(redisProperties.getPool().getMaxTotal());
        config.setMinIdle(redisProperties.getPool().getMinIdle());
        config.setMaxIdle(redisProperties.getPool().getMaxIdle());
        config.setTestOnBorrow(redisProperties.getPool().isTestOnBorrow());
        config.setTestOnReturn(redisProperties.getPool().isTestOnReturn());
        config.setTestOnCreate(redisProperties.getPool().isTestOnCreate());

        config.setTestWhileIdle(redisProperties.getPool().isTestWhileIdle());
        config.setMaxWaitMillis(redisProperties.getPool().getMaxWaitMillis());
        // 表示idle object evitor两次扫描之间要sleep的毫秒数
        config.setTimeBetweenEvictionRunsMillis(redisProperties.getPool().getTimeBetweenEvictionRunsMillis());
        // 表示idle object evitor每次扫描的最多的对象数
        config.setNumTestsPerEvictionRun(redisProperties.getPool().getNumTestsPerEvictionRun());
        // 表示一个对象至少停留在idle状态的最短时间，然后才能被idle object evitor扫描并驱逐；这一项只有在timeBetweenEvictionRunsMillis大于0时才有意义
        config.setMinEvictableIdleTimeMillis(redisProperties.getPool().getMinEvictableIdleTimeMillis());

        return config;
    }

    @Bean
    public JedisConnectionFactory connectionFactory() {
        return constructJedisConnectionFactory(redisProperties.getDatabase());
    }

    @Bean("redisTemplate")
    public RedisTemplate<String, String> redisTemplate() {
        return constructRedisTemplate(connectionFactory());
    }

    private RedisTemplate<String, String> constructRedisTemplate(JedisConnectionFactory jedisConnectionFactory) {
        RedisTemplate<String, String> template = new RedisTemplate<>();
        template.setConnectionFactory(jedisConnectionFactory);
        template.setKeySerializer(new StringRedisSerializer());
        template.setValueSerializer(new GenericToStringSerializer<>(Object.class));
        return template;
    }

    private JedisConnectionFactory constructJedisConnectionFactory(int index) {
        JedisConnectionFactory factory = new JedisConnectionFactory();
        factory.setHostName(redisProperties.getHost());
        factory.setPort(redisProperties.getPort());
        factory.setPassword(redisProperties.getPassword());
        factory.setPoolConfig(jedisPoolConfig());
        factory.setDatabase(index);
        factory.setTimeout(30000);
        factory.afterPropertiesSet();
        return factory;
    }
}
`
程序运行自然是没有问题的，但是对同一个redis DB，会运行两个redis连接池(一个是jetcache内部自己的，一个是我对redisTemplate配置的)。

请问：
1. 有没有什么办法让jetcache的连接池也能配置到我的RedisTemplate的连接池中呢？
2. 另外，jetcache支持哪些连接池配置选项？

**Comment by areyouok** [comment]
能配置哪些属性是GenericObjectPoolConfig指定的。
现在spring boot的配置方式，要复用你的连接池需要定制，相关类是RedisAutoConfiguration。或者按未使用spring boot的方式进行配置，那样是通过代码配置的，比较灵活。
或者是lettuce客户端可以不用配置连接池。

**Comment by lioutall** [comment]
这样配置行不行
`@CreateCache(expire = 60 * 60 * 24 * 7, cacheType = CacheType.REMOTE, name = "base")
    private Cache<String, String> base;
/**
     * 获取jedis对象, 记得归还资源哦
     * @return .
     */
    public Jedis getJedis() {
        JedisPool pool = base.unwrap(JedisPool.class);
        return pool.getResource();
    }`
