### ISSUE TITLE
多个@EnableMethodCache只有一个生效

### ISSUE THREAD

**Issue by charlesvhe** [alibaba/jetcache#119]
我们的使用场景是：
项目开发使用jetcache，项目依赖的jar包也使用jetcache。
jar包含有@EnableMethodCache basePackages设置，然后项目本身也用到了@EnableMethodCache basePackages设置，只有一个生效，导致另一个设置的basePackages中的注解失效。

**Comment by areyouok** [comment]
这种情况以前没有遇到过。

在同一个spring application context里面，我理解应该统一来配置吧。

**Comment by charlesvhe** [comment]
业务配置是应该统一配置，但是一些组件，想做到引入依赖即可使用就需要多个@EnableMethodCache了。例如我有个一通过注解埋点实现打点计数的组件，底层用的jetcache，这个组件就需要配置自己的@EnableMethodCache，业务服务在引用这个组件的时候就会有问题了，其他组件 配置、审查等等底层使用jetcache也都有这个问题，如果在业务应用的入口类配置感觉不够优雅，不够可插拔。

可以参考Feign的实现方式 @EnableFeignClients

**Comment by areyouok** [comment]
EnableMethodCache还有一些别的属性，比如proxyTargetClass等，如果同一个Spring application context里面，多个EnableMethodCache指定的proxyTargetClass不一致，该怎么处理呢，这样会导致很多问题。
此外还有CreateCache注解，如果有多个多次初始化，会不会有问题我没有试过。

最后一些全局属性还是要在yml里面统一配置的，所以EnableMethodCache这个注解统一用一个我觉得问题不大。配置、审查这些组件如果用了jetcache，可以让它们分别定义一个常量，指明要扫描的包名，在EnableMethodCache统一配置的时候把这些包名都加进来。
