### ISSUE TITLE
我用Cached注解，本地保存，如何取出来呢

### ISSUE THREAD

**Issue by zjcnb** [alibaba/jetcache#120]
@Cached(name = "userService.getUserById",key = "#Id",expire = 100)
	User getByUserId(long Id) throws Exception;

**Comment by zjcnb** [comment]
/**
	 * 根据id获取用户信息
	 * @param Id
	 * @return
	 * @throws Exception
	 */
	@Cached(name = "userService.getUserById",key = "#Id",cacheType = CacheType.LOCAL)
	@CacheRefresh(refresh = 1,timeUnit=TimeUnit.MINUTES)
	User getByUserId(long Id) throws Exception;‘


自动更新也没有生效，尴尬

**Comment by areyouok** [comment]
你使用了参数的名称，编译的时候是否指定了-parameters参数？

**Comment by zjcnb** [comment]
制定了参数，是#user.id,我看本地也有了，但是我不知道怎么取出来，如果过是CreateCache这个注解的话，我知道怎么取。就是单独的这个Cache注解生成记录之后，不知道如何取出来

**Comment by areyouok** [comment]
createcache注解和cached注解的name属性相同，就会得到同一个cache了。不过这样有个潜在的坑，就是这两个注解的属性（比如超时时间）配置必须都一样，因为不确定哪个会先初始化。

我以后也许应该提供一个专门的注解来干这件事。

**Comment by areyouok** [comment]
我第一个回答说的-parameters参数，指的是javac编译器的参数

**Comment by zjcnb** [comment]
我本地运行idea跑起来的web项目，在自己本地测试。那个问题我一会试试，还有一个需要咨询一下，就是我看wiki，那个自动刷新写的比较笼统，/**
     * 1分钟刷新一次
     */
    @PostConstruct
    public void init() throws Exception{
        RefreshPolicy policy = RefreshPolicy.newPolicy(1,TimeUnit.MINUTES);
        userCache.config().setRefreshPolicy(policy);
    }
我目前是这样的

**Comment by zjcnb** [comment]
您有qq群吗？或者您的一个联系方式，如果方便的话，希望可以加一下。

**Comment by areyouok** [comment]
没有群。你这样写是有问题的，没有指定loader。
cached注解可以不用指定loader，但是createcache需要。

**Comment by zjcnb** [comment]
哦哦，刚才我试了一下，cached注解的name 和createCache的注解name相同，但是貌似并没有放到哪个map里，代码如下：
@Cached(name = "userService",key = "#Id",cacheType = CacheType.LOCAL,expire = 20,keyConvertor = "#Id")
	User getByUserId(long Id) throws Exception;
@CreateCache(name = "userService",cacheType = CacheType.LOCAL,localLimit = 50,expire = 20)
    public Cache<Object,User> userCache;

第一个是在接口的方法上，第二个实在实现类里

**Comment by areyouok** [comment]
你指定了一个不存在的keyConvertor，会出错的
