### ISSUE TITLE
只想启用本地缓存，不想开启远端缓存

### ISSUE THREAD

**Issue by allon2** [alibaba/jetcache#121]
目前只想开启本地缓存，不想开启远端缓存，目前的版本是否支持，如果不支持是否有计划

**Comment by zjcnb** [comment]
这个是支持的，我已经验证了

**Comment by allon2** [comment]
如何支持呢？

**Comment by areyouok** [comment]
就是zjcnb说的这样的，不过我自己都没这样试过

**Comment by zjcnb** [comment]
是支持的，因为我现在就是用的本地缓存没有用远程。

**Comment by allon2** [comment]
非spring boot配置，求一个spring的配置

**Comment by areyouok** [comment]
getting started文档里面有，不要设置remoteCacheBuilders就行了
