### ISSUE TITLE
缓存刷新时间问题

### ISSUE THREAD

**Issue by goldpumpkin** [alibaba/jetcache#124]
缓存默认刷新策略是60s一次吗？ 
`        Map localBuilders = new HashMap();
        EmbeddedCacheBuilder localBuilder = LinkedHashMapCacheBuilder
                .createLinkedHashMapCacheBuilder()
                .keyConvertor(FastjsonKeyConvertor.INSTANCE);
        localBuilder.getConfig().setExpireAfterAccessInMillis(1);
        localBuilder.getConfig().setRefreshPolicy(RefreshPolicy.newPolicy(10,TimeUnit.SECONDS));
        localBuilders.put(CacheConsts.DEFAULT_AREA, localBuilder);`
这么设置有问题吗？怎么不生效？
缓存实例使用的是 
`    @Cached(name="staticData:", key="'city'",expire = 10,timeUnit = TimeUnit.SECONDS,cacheType = CacheType.LOCAL)
    @CacheRefresh(refresh = 10, stopRefreshAfterLastAccess = 5, timeUnit = TimeUnit.SECONDS)`

**Comment by areyouok** [comment]
默认是不刷新的。

```
localBuilder.getConfig().setRefreshPolicy(RefreshPolicy.newPolicy(10,TimeUnit.SECONDS)); 
```

这一行可以去掉。

你设置了stopRefreshAfterLastAccess，一个key，5秒钟没有访问的话，它就不刷新了。

**Comment by goldpumpkin** [comment]
好的，谢谢！找到问题了，麻烦再问一下。
现在的项目用的spring的redisTemplate，获取不到底层Poo<Jedis>
   @Bean
    public Pool<Jedis> pool(){}
那这个bean该这么注进去呢？

**Comment by areyouok** [comment]
看文档
https://github.com/alibaba/jetcache/wiki/RedisWithJedis_CN

如果使用spring boot，你要定义这个先：
```
@Bean(name = "defaultPool")
@DependsOn(RedisAutoConfiguration.AUTO_INIT_BEAN_NAME)//jetcache2.2+
public JedisPoolFactory defaultPool() {
    return new JedisPoolFactory("remote.default", JedisPool.class);
}
```

不使用spring boot的情况下，jedis pool是需要你自己配置，然后提供给jetcache的
