### ISSUE TITLE
jetcache如何接入codis？使用lettuce链接

### ISSUE THREAD

**Issue by sky-junjun** [alibaba/jetcache#126]
codis项目中配置的是zk地址，而且有用户名和密码
jetcache如何接入？尝试将zk地址，密码以standalone方式配置
无法链接，求指导

**Comment by areyouok** [comment]
我没有专门用过codis，不过codis和redis连接起来应该是一样的，你应该先试试连普通的redis能不能行。
而且你给的信息也太少了。

**Comment by sky-junjun** [comment]
``
  remote:
    default:
      type:  redis.lettuce
      keyConvertor: fastjson
      valueEncoder: java
      valueDecoder: java
      poolConfig:
        minIdle: 5
        maxIdle: 20
        maxTotal: 50
      uri: redis://:order*18@116.92.161.111:15232
这里：
zkServer：116.92.161.111:15232 ，是codis的zk地址端口
password：order*18，是配置的codis明文密码
这样子的配置就是按照普通redis配置来配置的，只不过带了密码，提示连接不上
如果将uri修改为：redis://:116.92.161.111:15232，项目启动成功，但是，无法读取和写入数据到remotecache

codisPool的配置：CodisPool(zkServer,name,password,"3000",jedisPoolConfig())
我们项目里使用的是jedis

但是这个样子感觉好像没办法接入啊

**Comment by areyouok** [comment]
你上面是lettuce，下面怎么又是jedis呢？
