### ISSUE TITLE
tryLockAndRun是阻塞的吗

### ISSUE THREAD

**Issue by weidedong** [alibaba/jetcache#127]
//在heavyDatabaseOperation中查询数据库并填充缓存
cache.tryLockAndRun("key", 60, TimeUnit.SECONDS, () -> heavyDatabaseOperation());
//如果cache.tryLockAndRun非阻塞，那么cache[key]会报异常
var value = cache[key];

**Comment by areyouok** [comment]
没太明白你的意思，这个方法是尝试性的获取锁，如果成功就执行操作，如果失败会立即返回false，不会堵塞
