### ISSUE TITLE
 ERR invalid expire time in psetex

### ISSUE THREAD

**Issue by wongben** [alibaba/jetcache#130]
<dependency>
			<groupId>com.alicp.jetcache</groupId>
			<artifactId>jetcache-starter-redis-lettuce</artifactId>
			<version>2.5.5</version>
		</dependency>
		
		<dependency>
			<groupId>io.projectreactor</groupId>
			<artifactId>reactor-core</artifactId>
			<version>3.1.8.RELEASE</version>
		</dependency>
		<dependency>
			<groupId>com.github.ben-manes.caffeine</groupId>
			<artifactId>caffeine</artifactId>
			<version>2.6.2</version>
--------------------------------------
jetcache:
    statIntervalMinutes: 0
    areaInCacheName: false
    local:
        default:
            type: caffeine
            keyConvertor: fastjson
            limit: 20000
    remote:
        default:
            type: redis.lettuce
            keyConvertor: fastjson
            valueEncoder: kryo
            valueDecoder: kryo
            uri: redis://zdc123@10.40.64.117:6379/6?timeout=10000s
            expireAfterWriteInMillis: 900000

-------------------------------------
ERROR [JetCacheDefaultExecutor] com.alicp.jetcache.AbstractCache [51] -| jetcache(RedisLettuceCache) PUT error. key=f2f26b43cd0a42158441e468b68a8b2d.
2018/7/30 下午4:04:26io.lettuce.core.RedisCommandExecutionException: ERR invalid expire time in psetex
2018/7/30 下午4:04:26	at io.lettuce.core.protocol.AsyncCommand.completeResult(AsyncCommand.java:118)
2018/7/30 下午4:04:26	at io.lettuce.core.protocol.AsyncCommand.complete(AsyncCommand.java:109)
2018/7/30 下午4:04:26	at io.lettuce.core.protocol.CommandHandler.complete(CommandHandler.java:598)
2018/7/30 下午4:04:26	at io.lettuce.core.protocol.CommandHandler.decode(CommandHandler.java:556)
2018/7/30 下午4:04:26	at io.lettuce.core.protocol.CommandHandler.channelRead(CommandHandler.java:508)
2018/7/30 下午4:04:26	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
2018/7/30 下午4:04:26	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
2018/7/30 下午4:04:26	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
2018/7/30 下午4:04:26	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
2018/7/30 下午4:04:26	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
2018/7/30 下午4:04:26	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
2018/7/30 下午4:04:26	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
2018/7/30 下午4:04:26	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
2018/7/30 下午4:04:26	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
2018/7/30 下午4:04:26	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
2018/7/30 下午4:04:26	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
2018/7/30 下午4:04:26	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434)
2018/7/30 下午4:04:26	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
2018/7/30 下午4:04:26	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
2018/7/30 下午4:04:26	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965)
2018/7/30 下午4:04:26	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
2018/7/30 下午4:04:26	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:645)
2018/7/30 下午4:04:26	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:580)
2018/7/30 下午4:04:26	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:497)
2018/7/30 下午4:04:26	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:459)
2018/7/30 下午4:04:26	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
2018/7/30 下午4:04:26	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
2018/7/30 下午4:04:26	at java.lang.Thread.run(Thread.java:748)

**Comment by areyouok** [comment]
我猜是不是调用put的时候，溢出了？
相关的超时时间设置的是多少嘛

**Comment by wongben** [comment]
产线还是有异常
配置信息如下：
jetcache:
    statIntervalMinutes: 0
    areaInCacheName: false
    local:
        default:
            type: caffeine
            keyConvertor: fastjson
            limit: 20000
    remote:
        default:
            type: redis.lettuce
            keyConvertor: fastjson
            valueEncoder: kryo
            valueDecoder: kryo
            uri: redis://zdc123@10.40.64.117:6379/6


缓存这样使用的：
 /**
     * 内容页面缓存
     */
    @CreateCache(name = "content:", cacheType = CacheType.REMOTE, expire = 2, timeUnit = TimeUnit.HOURS)
    private Cache<String, Content> contentCache;


我看异常，没定位我的业务代码，哪里调用的。


----------------------------------------------------
00 2018-08-06T03:46:55.388692000Z 2018-08-06 11:46:55.386 |-ERROR [JetCacheDefaultExecutor] com.alicp.jetcache.AbstractCache [51] -| jetcache(RedisLettuceCache) PUT error. key=c0bdbddc22f945829b2ea94be8de9c9f.
00 2018-08-06T03:46:55.389295000Z io.lettuce.core.RedisCommandExecutionException: ERR invalid expire time in psetex
00 2018-08-06T03:46:55.389685000Z 	at io.lettuce.core.protocol.AsyncCommand.completeResult(AsyncCommand.java:118)
00 2018-08-06T03:46:55.390066000Z 	at io.lettuce.core.protocol.AsyncCommand.complete(AsyncCommand.java:109)
00 2018-08-06T03:46:55.390414000Z 	at io.lettuce.core.protocol.CommandHandler.complete(CommandHandler.java:598)
00 2018-08-06T03:46:55.390773000Z 	at io.lettuce.core.protocol.CommandHandler.decode(CommandHandler.java:556)
00 2018-08-06T03:46:55.391158000Z 	at io.lettuce.core.protocol.CommandHandler.channelRead(CommandHandler.java:508)
00 2018-08-06T03:46:55.391522000Z 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
00 2018-08-06T03:46:55.391874000Z 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
00 2018-08-06T03:46:55.392084000Z 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
00 2018-08-06T03:46:55.392297000Z 	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
00 2018-08-06T03:46:55.392581000Z 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
00 2018-08-06T03:46:55.392810000Z 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
00 2018-08-06T03:46:55.393050000Z 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
00 2018-08-06T03:46:55.393266000Z 	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
00 2018-08-06T03:46:55.393475000Z 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
00 2018-08-06T03:46:55.393681000Z 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
00 2018-08-06T03:46:55.393909000Z 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
00 2018-08-06T03:46:55.394118000Z 	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434)
00 2018-08-06T03:46:55.394323000Z 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
00 2018-08-06T03:46:55.394531000Z 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
00 2018-08-06T03:46:55.394735000Z 	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965)
00 2018-08-06T03:46:55.394964000Z 	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
00 2018-08-06T03:46:55.395169000Z 	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:645)
00 2018-08-06T03:46:55.395374000Z 	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:580)
00 2018-08-06T03:46:55.395584000Z 	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:497)
00 2018-08-06T03:46:55.395810000Z 	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:459)
00 2018-08-06T03:46:55.396019000Z 	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
00 2018-08-06T03:46:55.396223000Z 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
00 2018-08-06T03:46:55.396430000Z 	at java.lang.Thread.run(Thread.java:748)
