### ISSUE TITLE
为什么执行了两次一样的方法？

### ISSUE THREAD

**Issue by zjcnb** [alibaba/jetcache#131]
CreateCacheAnnotationBeanPostProcessor类中：
重写setBeanFactory方法中，为什么调用了父类的方法，又自己写了一遍呢？

  @Override
    public void setBeanFactory(BeanFactory beanFactory) throws BeansException {
        super.setBeanFactory(beanFactory);
        if (!(beanFactory instanceof ConfigurableListableBeanFactory)) {
            throw new IllegalArgumentException(
                    "AutowiredAnnotationBeanPostProcessor requires a ConfigurableListableBeanFactory");
        }
        this.beanFactory = (ConfigurableListableBeanFactory) beanFactory;
    }

@Override
	public void setBeanFactory(BeanFactory beanFactory) {
		if (!(beanFactory instanceof ConfigurableListableBeanFactory)) {
			throw new IllegalArgumentException(
					"AutowiredAnnotationBeanPostProcessor requires a ConfigurableListableBeanFactory: " + beanFactory);
		}
		this.beanFactory = (ConfigurableListableBeanFactory) beanFactory;
	}

**Comment by areyouok** [comment]
因为父类的beanFactory字段是私有的，我访问不到啊
