### ISSUE TITLE
@CreateCache可用，但@Cache不生效

### ISSUE THREAD

**Issue by rcarlosdasilva** [alibaba/jetcache#132]
```
        <dependency>
            <groupId>com.alicp.jetcache</groupId>
            <artifactId>jetcache-starter-redis</artifactId>
            <version>2.5.5</version>
        </dependency>
```
```
@CreateCache
private Cache<String, Object> cache;
```
可以正常使用，但使用@Cache到方法上，不生效
```
@Cached(name = "mis2018:city", key = "name_#cityName", expire = 86400)
@Override
public String getCityCodeByName(String cityName) {
```
```
@EnableMethodCache(basePackages = "package")
@EnableCreateCacheAnnotation
public class Application extends SpringBootServletInitializer {
```

**Comment by areyouok** [comment]
你把key属性去掉试试，是不是没有指定javac的-parameters参数

**Comment by rcarlosdasilva** [comment]
key属性去掉也没用，我debug了一下CachePointcut.matchesImpl()，发现在同一个包下，有5个类，只有三个类中的所有方法，被CacheConfigUtil.parse(cac, method);，什么情况？晕

**Comment by areyouok** [comment]
需要给出更多信息

**Comment by rcarlosdasilva** [comment]
配置都是按照wiki里做的，项目里已经引用了spring-boot-starter-data-redis，应该不会受影响吧，当前这个包下所有类都没有用到spring redis。我发现刚刚说的能执行到CacheConfigUtil.parse(cac, method);这里的三个类，都是通过AnnotationAwareAspectJAutoProxyCreator这个BeanPostProcessor执行的，但是其他类的getBeanPostProcessors()集合中就没有这个AnnotationAwareAspectJAutoProxyCreator，闹不明白了

**Comment by areyouok** [comment]
你可以把你的case简化一下，如果能复现，代码发上来。

**Comment by rcarlosdasilva** [comment]
重建项目是没有问题的，现在的项目是别人搭建的时间稍久的，先不捣鼓了，谢谢
