### ISSUE TITLE
valueEncoder，valueDecoder为java的时候，获取list集合的时候类转换失败

### ISSUE THREAD

**Issue by lhyf** [alibaba/jetcache#133]
可以存入，但是获取的时候转换失败
java.lang.ClassCastException: com.xxxx.config.server.pojo.TPubNamespace cannot be cast to com.xxx.config.server.pojo.TPubNamespace

controller 中：
        List<TPubNamespace> namespaces = pubNamespaceService.findAll();
        for(TPubNamespace namespace:namespaces){ // 这行代码报错
         .......
       }
service中：
    @Cached(name = "pubnamespace")
    public List<TPubNamespace> findAll() {
        List<TPubNamespace> namespaceList = pubNamespaceMapper.selectByExample(null);
        return namespaceList;
    }

TPubNamespace ：
public class TPubNamespace implements Serializable {

    private static final long serialVersionUID = 1L;
    private Integer id;
     xxxx...
}

第一调用controller 接口正常，第二次调用报错；将valueEncoder，valueDecoder改为 kryo 后，正常

**Comment by areyouok** [comment]
是开发环境吧。
把你的jetcache版本更新一下。或者把springboot的devtools禁用了。

**Comment by lhyf** [comment]
用的是jetcache-starter-redis 2.5.5 ,禁用devtools后正常运行了, 谢谢!

**Comment by areyouok** [comment]
新版本针对这个做过处理，看起来可能还是有问题，你能做一个简单的案例来复现吗？

**Comment by lhyf** [comment]
做了一个小demo, 已经上传了 ,异常发生在UserController.getAllUser()里面 
 https://github.com/lhyf/jetcache-demo.git

**Comment by areyouok** [comment]
谢谢，我有时间的时候看一下

**Comment by areyouok** [comment]
感谢，改好了，请用2.5.6版本

**Comment by lhyf** [comment]
好的，谢谢
