### ISSUE TITLE
你好，什么场景适合用异步访问Redis??

### ISSUE THREAD

**Issue by lemon-simple** [alibaba/jetcache#135]
我看到你支持了很多异步api，什么场景适合用异步访问Redis?? 我通常使用的都是同步访问

**Comment by areyouok** [comment]
只有lettuce才支持异步，如果你使用lettuce，jetcache会自动把一些操作异步提交，可以降低rt。
如果你是普通的业务开发，没有必要专门去使用jetcache的异步接口，异步开发毕竟太麻烦。
