### ISSUE TITLE
starter 2.5.6版本引入了2.8.1的jedis，而这个版本的jedis构造方法没有ssl的入参。。

### ISSUE THREAD

**Issue by JoshShaw** [alibaba/jetcache#138]
如题。。。

我这样解决的。。。
是不是要修复一下呀。。
![default](https://user-images.githubusercontent.com/17921547/43875791-97078adc-9bc4-11e8-8bd0-74d1d87fb9b4.JPG)

**Comment by areyouok** [comment]
你搞错了
jetcache-starter-redis下mvn dependency:tree 输出：
[INFO] com.alicp.jetcache:jetcache-starter-redis:jar:2.5.6
[INFO] +- com.alicp.jetcache:jetcache-autoconfigure:jar:2.5.6:compile
[INFO] |  \- org.springframework.boot:spring-boot-starter:jar:1.5.12.RELEASE:compile
[INFO] |     +- org.springframework.boot:spring-boot:jar:1.5.12.RELEASE:compile
[INFO] |     +- org.springframework.boot:spring-boot-autoconfigure:jar:1.5.12.RELEASE:compile
[INFO] |     +- org.springframework.boot:spring-boot-starter-logging:jar:1.5.12.RELEASE:compile
[INFO] |     |  +- ch.qos.logback:logback-classic:jar:1.2.3:compile
[INFO] |     |  |  \- ch.qos.logback:logback-core:jar:1.2.3:compile
[INFO] |     |  +- org.slf4j:jcl-over-slf4j:jar:1.7.25:compile
[INFO] |     |  +- org.slf4j:jul-to-slf4j:jar:1.7.25:compile
[INFO] |     |  \- org.slf4j:log4j-over-slf4j:jar:1.7.25:compile
[INFO] |     +- org.springframework:spring-core:jar:4.3.16.RELEASE:compile
[INFO] |     \- org.yaml:snakeyaml:jar:1.17:runtime
[INFO] +- com.alicp.jetcache:jetcache-anno:jar:2.5.6:compile
[INFO] |  +- com.alicp.jetcache:jetcache-core:jar:2.5.6:compile
[INFO] |  |  +- com.alicp.jetcache:jetcache-anno-api:jar:2.5.6:compile
[INFO] |  |  \- com.github.ben-manes.caffeine:caffeine:jar:2.6.2:compile
[INFO] |  +- org.springframework:spring-context:jar:4.3.16.RELEASE:compile
[INFO] |  |  +- org.springframework:spring-aop:jar:4.3.16.RELEASE:compile
[INFO] |  |  +- org.springframework:spring-beans:jar:4.3.16.RELEASE:compile
[INFO] |  |  \- org.springframework:spring-expression:jar:4.3.16.RELEASE:compile
[INFO] |  +- org.mvel:mvel2:jar:2.4.0.Final:compile
[INFO] |  \- org.slf4j:slf4j-api:jar:1.7.25:compile
[INFO] +- com.alicp.jetcache:jetcache-redis:jar:2.5.6:compile
[INFO] +- redis.clients:jedis:jar:2.9.0:compile
[INFO] |  \- org.apache.commons:commons-pool2:jar:2.4.2:compile
[INFO] +- com.alibaba:fastjson:jar:1.2.47:compile
[INFO] +- com.esotericsoftware:kryo:jar:4.0.2:compile
[INFO] |  +- com.esotericsoftware:reflectasm:jar:1.11.3:compile
[INFO] |  |  \- org.ow2.asm:asm:jar:5.0.4:compile
[INFO] |  +- com.esotericsoftware:minlog:jar:1.3.0:compile
[INFO] |  \- org.objenesis:objenesis:jar:2.5.1:compile
[INFO] +- org.junit.jupiter:junit-jupiter-api:jar:5.0.2:test
[INFO] |  +- org.opentest4j:opentest4j:jar:1.0.0:test
[INFO] |  \- org.junit.platform:junit-platform-commons:jar:1.0.2:test
[INFO] +- org.junit.platform:junit-platform-launcher:jar:1.0.2:test
[INFO] |  \- org.junit.platform:junit-platform-engine:jar:1.0.2:test
[INFO] +- org.junit.jupiter:junit-jupiter-engine:jar:5.0.2:test
[INFO] +- org.junit.vintage:junit-vintage-engine:jar:4.12.2:test
[INFO] |  \- junit:junit:jar:4.12:test
[INFO] |     \- org.hamcrest:hamcrest-core:jar:1.3:test
[INFO] \- org.apiguardian:apiguardian-api:jar:1.0.0:test

**Comment by JoshShaw** [comment]
奇怪了，
我引入的包，其依赖树中jedis的版本的确是2.8.1，slf4j的版本和你上面贴的也是不一样哦。
![default](https://user-images.githubusercontent.com/17921547/43880194-fc89be6a-9bd9-11e8-8d8a-e9e018900d70.JPG)

**Comment by areyouok** [comment]
我也觉得奇怪，不过jetcache是没有引入这么老的jedis版本的。
