### ISSUE TITLE
在接口上用注解@cache不生效

### ISSUE THREAD

**Issue by wallacepang** [alibaba/jetcache#139]
在接口上用注解@cache不生效，在类方法上可以
    @Cached(name="userCache.", key="#id", expire = 3,timeUnit = TimeUnit.HOURS)
    User getUserById(long id);

**Comment by areyouok** [comment]
在接口上是肯定可以工作的，单元测试中这样的场景太多了。
你一点信息都不给，我只能猜了：检查一下EnableMethodCache扫描的包是不是包括了接口所在的包？

**Comment by wallacepang** [comment]
环境 : spring boot 2.0.4 +jetcache 2.5.6
第一次 : 在接口上 用@cached(name="userCache.", key="#id", expire = 3,timeUnit = TimeUnit.HOURS)
User getUserById(long id);，然后用一个restful接口调用，缓存不生效

然后 在实现类上 用@cache 注解  缓存生效 redis中也有记录，接口和实现类在同一个包路径下面的

**Comment by areyouok** [comment]
javac的-parameters参数指定了没有，如果没有，把key属性删掉

**Comment by areyouok** [comment]
spring aop同一个类调用自己的方法，是不会被拦截的，这个你知道吧

**Comment by wallacepang** [comment]
@areyouok  感谢 是这个参数没有制定   javac的-parameters参数指定了没有  key 改成 args[0] 就可以

**Comment by areyouok** [comment]
你这个场景，如果不需要更新或失效缓存，可以不用设置key属性，jetcache可以自动生成的

**Comment by networksatyr** [comment]
要缓存的对象实现 Serializable 这个接口了吗？
