### ISSUE TITLE
是否有针对批量处理的优化

### ISSUE THREAD

**Issue by darknesstm** [alibaba/jetcache#143]
比如一个方法如下

`Map<Long, User> getUserMapByIds(Collection<Long> ids)`

希望能够基于单个id进行缓存，当方法被调用时，区分ids中已被缓存的部分，只传递未缓存的部分到实际的方法实现，最终合并2边的结果进行返回

同时也能和

`User getUserById(Long id)`进行联动，比如设置一个相同的 key 比如 `user::args[0]`

**Comment by areyouok** [comment]
这个得拿到Cache接口的实例自己做
