### ISSUE TITLE
注解@Cached中的key上面调用自定义方法处理key值

### ISSUE THREAD

**Issue by zpypy** [alibaba/jetcache#144]
使用@Cached注解，当指定key时，我希望这个存入redis的key，可以是用我自定义的方法生成的key，请问这种写法怎么用呢，我直接在key=“”，这里边调用自定义方法是不可行的，求解惑

**Comment by areyouok** [comment]
key里面可以写SpEL脚本，只能访问到方法的参数

如果你有这个需求得用```@CreateCache```

**Comment by zpypy** [comment]
我的意思是，使用@Cached注解，设置key时，可以把访问到的方法参数包装一层我自定义的方法然后赋给key吗？因为方法的参数是一个map，有时候这个map的值太多了，作为key不太好， 所以我写了一个方法，根据这个map生成一个唯一的字符串作为key值，请问用Cached能实现吗

**Comment by areyouok** [comment]
如果参数有方法，SpEL可以调用到

**Comment by areyouok** [comment]
key="bean('myBean')"

你试试
