### ISSUE TITLE
双机配置，使用local+remote缓存，本地缓存无法删除，数据不一致

### ISSUE THREAD

**Issue by truantmuse** [alibaba/jetcache#145]
你好，服务有两台机器，使用了本地缓存和redis，修改数据后，只删除了其中一台的本地缓存，造成了数据不一致，请教这个问题jetcache有做处理吗，是不是双机的暂时还不能使用本地缓存，谢谢~

**Comment by areyouok** [comment]
修改数据会更新local和remote cache，但是不会更新其他服务器的local cache。

如果你有这个问题，可以只用remote，或者给local设置一个较短的超时时间。
