### ISSUE TITLE
是否可以使用jetcache的"自动刷新缓存"做应用的数据闭环?

### ISSUE THREAD

**Issue by a596620989** [alibaba/jetcache#15]
比如商品详情页的依赖卖家数据(需要展示卖家信息), 而商品中心往往和卖家中心是两个独立的中心层服务. 我目前的想法通过jetcache把卖家的全量信息(数据量不大, 大概10w)都缓存到商品中心的本地内存中. 通过RefreshPolicy保证每十分钟和卖家中心同步. 这样即便卖家中心挂掉, 也不会导致商品详情页数据缺失(即便挂掉可以使用老的卖家数据).

从文档中, 我只看到用"自动刷新缓存"来避免缓存雪崩, 不知道贵司是否也有用jetcache解决数据闭环的问题?

**Comment by areyouok** [comment]
文档里提到了，最适用的场景应该是key数量比较少，访问量大，但是加载开销较大的情况。

你说的情况，不能简单的说能或者不能，你应该了解一下内部的实现机制，然后做出选择。自动加载相关的类主要是`RefreshCache`，你可以看一下。需要有以下考虑：

首先，业务上需要能够接受数据不是最新的，这个是基本条件了。

第二，10w个对象放到内存里面，内存会不会爆？这个可以根据你key、value的类型来估计，注意jetcache放到缓存里面的是包装类`CacheValueHolder`，如果是二级缓存，那么会包装两次。假设一个Key+Value有1K，10w条数据就是100M。除此之外，内存里面最多还会有10w任务在Executor中，以及最多10w个`RefreshCache.RefreshTask`对象放在`ConcurrentHashMap`中。这样看起来如果你的对象不是特别大，内存是可以装下的，但是内存问题从来都是积少成多，JVM堆还要装很多其它东西的。

第三，你的场景应该是不能只用本地缓存的，否则假设你有100个服务器，这100个服务器都会分别去刷新，带来无谓的重复刷新。更好的方式是使用两级缓存，JetCache会使用远程缓存做排重，每个时间周期只有会有一次加载。但是加载任务还是保存在每个服务器的内存中的，没法放到Redis里面。

第四，这么大量的加载任务，是否会堵塞加载线程池？JetCache默认使用10个线程的线程池，你可以通过`JetCacheExecutor.setHeavyIOExecutor`进行定制修改。要做好这个线程池的监控。

第五，有两个因素会降低内存和任务调度的压力。一是JetCache只会刷新get过的key，刷新任务是首次get的时候添加到本服务器的内存中的，如果你的商品数据存在大量从不访问的冷数据，那么它不会在内存中，也不会有刷新任务；二是长时间不访问的key，可以通过设置stopRefreshAfterLastAccess来停止它的刷新。
