### ISSUE TITLE
请教个问题：redis缓存在 dao层做？service层做？

### ISSUE THREAD

**Issue by lemon-simple** [alibaba/jetcache#152]
请教个问题：redis缓存在 dao层做？service层做？
一直并不是特别清楚，有没有说服力很高的成熟方案？

**Comment by lemon-simple** [comment]
举个例子，设计缓存，缓存结构应该基于mysql数据结构设计 ？还是根据service返回设计？

**Comment by areyouok** [comment]
这个没有具体的答案，哪层都可以

**Comment by lemon-simple** [comment]
@areyouok 您在缓存结构设计时怎么样去考虑呢？有什么优劣吗？

**Comment by caijianhui** [comment]
我觉得redis也是db的一种，应该放在dao层。虽然手redis没有关系型数据库那么复杂，需要写很多sql语句，但是我可以屏蔽了我不需要知道的redis key进行复用
