### ISSUE TITLE
redis缓存多数据库问题

### ISSUE THREAD

**Issue by zorkeAccount** [alibaba/jetcache#154]
集成redis缓存的时候支持指定固定的redis数据库db吗？springboot集成的话配置文件中怎么设置？

**Comment by areyouok** [comment]
支持什么属性看这里：
https://github.com/alibaba/jetcache/blob/master/jetcache-starter/jetcache-autoconfigure/src/main/java/com/alicp/jetcache/autoconfigure/RedisAutoConfiguration.java

可指定database

**Comment by zorkeAccount** [comment]
RedisAutoConfiguration.java中已解决！！私下自己还是得仔细阅读源码先
