### ISSUE TITLE
remove(key) 能删除key值对应的缓存，但是 key对应自动刷新的定时线程怎么移除呢？

### ISSUE THREAD

**Issue by CrossIce** [alibaba/jetcache#155]
现在有这样的一种情况就是 我用了redis分布缓存，有个key不需要，我需要把它从缓存中清除掉，用了remove()方法清除了 但是这个key值的定时线程 #TS 值 依然存在于redis中，依然会刷新key值出来

**Comment by areyouok** [comment]
在一个分布式系统中，很难有简单的办法去移除每个机器上的刷新任务。配合stopRefreshAfterLastAccess可以让刷新任务在长时间无访问的情况下自动停止。那个_#TS#在redis中也不代表刷新在进行。

**Comment by CrossIce** [comment]
我在源码中看到close() 方法但是这个方法是停止这个cache的所有key的定时线程，在单机环境下也无法做到只停止其中一个key的定时线程吗？

**Comment by areyouok** [comment]
明白了，只移除本机的任务是很容易的。不过如果要做，就希望能彻底解决一下。

**Comment by areyouok** [comment]
明白了，只移除本机的任务是很容易的。不过如果要做，就希望能彻底解决一下。

**Comment by CrossIce** [comment]
我现在的想法是 利用消息队列或者在刷新部分提供一个接口用于删除刷新的定时线程，在访问部分 往消息队列发消息或者是访问刷新部分的删除接口来删除刷新线程，不过这个只是对我目前所遇到的问题而言的解决方案，对jetcache这个缓存框架而言 可能需要更加完善稳定的方案。

**Comment by areyouok** [comment]
就你的场景，如果刷新是单机的，可以修改RefreshCache，覆盖REMOVE方法和REMOVE_ALL方法，移除刷新任务就可以了，比你用消息队列要简单。
