### ISSUE TITLE
请教细粒度缓存的方案

### ISSUE THREAD

**Issue by liudajiang** [alibaba/jetcache#156]
例如：
cacheA.key1: [user#1,user#2,user#3]
cacheA.key2: [user#2,user#3,user#4]
cacheA.key3: [user#3,user#4]
当修改user#2的数据,但不确定user#2被缓存在了那个key中
只能flush cacheA

有其他的解决方案么？

**Comment by areyouok** [comment]
没有好的办法，可以通过超时来控制。

jetcache甚至没有提供清空cache的方法，不过你可以给ExternalCacheConfig设置一个新的keyPrefix，能达到清空一个cache的效果。

**Comment by liudajiang** [comment]
@areyouok感谢百忙中回复
1.这种细粒度的问题，我工作中经常会遇到。
例如商品A存在于有用户私藏和热门商品两个缓存中
您在日常开发中会怎么解决？
 2.我希望对缓存进行分页，
例： cache="user_liked" key="{userId}_{pageNo}"
当分页变化，希望evict key="{userId}_*"
使用通配符肯定是不行的，使用springcache也做不到。
是我没找到好的分页方法，还是您在日常开发中遇不到缓存分页的场景？

请您赐教。谢谢

**Comment by areyouok** [comment]
通用的情况下，简单的说除了设置超时没有好的办法。

特定场景下可以根据业务做优化，比如论坛的分页，可以在板块有更新的时候，把帖子列表的缓存都失效掉。具体的做法可以给每个板块加一个更新时间戳。
