### ISSUE TITLE
手动更新定时缓存

### ISSUE THREAD

**Issue by clverhack** [alibaba/jetcache#157]
除了用cache api 外，能不能再定时刷新的基础上，加一个手动触发的动作，目前是否有这种操作

**Comment by areyouok** [comment]
```@CacheInvalidate```

**Comment by clverhack** [comment]
您是说通过这个注解，使得缓存失效，定时在刷新么？

**Comment by clverhack** [comment]
有没有手动触发缓存的机制。比如说我通过每个业务节点触发MQ , 由MQ 再通过查询把缓存更新一遍。

**Comment by areyouok** [comment]
```@CacheUpdate```

你找个空方法，加上这个注解，然后再调用这个方法更新缓存好了。

其实还可以通过```@CreateCache```创建一个缓存和```Cached```一样的，不过这样做略微有点坑，因为```@CreateCache```和```Cached```都可以指定缓存的一些属性，容易有误解。

**Comment by clverhack** [comment]
刚开始也是寻思用CacheUpdate来这么做的，我在其它应用写了一个调用方法，被调用方法用没被拦截到，像是没有效果。思来想去，还是用cache api 缓存来控制了，希望手控制分布式缓存方面可以在后续加强。感谢！！

**Comment by areyouok** [comment]
必须有效果的，不过同一个类内部互相调用是没有走aop的，所以会拦截不到

**Comment by clverhack** [comment]
CacheUpdate 的value 须是方法参数，业务场景需要将一个慢查询的结果缓存，这样这个参数需要有参数的方法结果查询。这样这种方式需要将cacheupdate 的方法被调用。
