### ISSUE TITLE
定时刷新参数覆盖的一个问题

### ISSUE THREAD

**Issue by clverhack** [alibaba/jetcache#159]
我用一个方法，里面调用两个定时刷新的方法，
定时刷新的参数第一个会被第二个覆盖掉。算不算是个问题啊

Map<String, Object> params1 = new HashMap<String, Object>();
  int projecTotal =service.countList(params);// **定时刷新1**
        if (projecTotal > 0) {
            int limit = paginator.getLimit();
            int offSet = paginator.getOffset();
            if (offSet == 0 || offSet > 0) {
                params.put("limitStart", offSet);
            }
            if (limit > 0) {
                params.put("limitEnd", limit);
            }
            List<> planList = service.searchList(params); // **定时刷新2**

**Comment by areyouok** [comment]
定时刷新是按key来的，不同的key是不同的任务，相同的key不会重复刷新。
