### ISSUE TITLE
为什么@Cached加上key属性之后缓存就不起作用了,去掉就好了

### ISSUE THREAD

**Issue by liaoqifeng** [alibaba/jetcache#160]

**Comment by areyouok** [comment]
你的编译器没有指定-parameters参数吧？

**Comment by liaoqifeng** [comment]
IDEA里面加了-parameters参数, 但是没用

**Comment by liaoqifeng** [comment]
解决了,编译器里面指定-parameters参数无效,要在pom文件的maven-compiler-plugin里面加上-parameters才会生效

**Comment by LSloveYJ** [comment]
<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-compiler-plugin</artifactId>
				<version>3.6.0</version>
				<configuration>
					<source>1.8</source>
					<target>1.8</target>
					<encoding>UTF-8</encoding>
					<compilerArgs>
						<arg>-parameters</arg>
					</compilerArgs>
				</configuration>
			</plugin>

**Comment by LSloveYJ** [comment]
<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-compiler-plugin</artifactId>
				<version>3.6.0</version>
				<configuration>
					<source>1.8</source>
					<target>1.8</target>
					<encoding>UTF-8</encoding>
					<compilerArgs>
						<arg>-parameters</arg>
					</compilerArgs>
				</configuration>
			</plugin>

**Comment by LSloveYJ** [comment]
如果使用maven-compiler-plugin  配置 <configuration><compilerArgs><target>1.8</target>
