### ISSUE TITLE
有配置关闭或者暂停缓存的属性吗？

### ISSUE THREAD

**Issue by fufenghua** [alibaba/jetcache#162]
就是在已经配置并大量注解使用缓存的情况下，在开发测试阶段想要关闭缓存，有没有这样一个配置项呢？设置true或者false之后则所有的缓存都不使用了？

**Comment by areyouok** [comment]
如果是禁用方法缓存的话：
GlobalCacheConfig里面有个jetcache.enableMethodCache开关。
另外你还可以把EnableMethodCache注解删掉也能达到效果。

**Comment by fufenghua** [comment]
> 如果是禁用方法缓存的话：
> GlobalCacheConfig里面有个jetcache.enableMethodCache开关。
> 另外你还可以把EnableMethodCache注解删掉也能达到效果。

谢谢
