### ISSUE TITLE
在客户端手动set key 为啥在代码里取不到值？

### ISSUE THREAD

**Issue by 888tyhj** [alibaba/jetcache#165]
1、![image](https://user-images.githubusercontent.com/11417048/45930219-d33cb600-bf8f-11e8-8400-eee39a271311.png)
编码的问题啊

2、这里的本地map 有啥作用吗

![image](https://user-images.githubusercontent.com/11417048/45930231-2282e680-bf90-11e8-8c5e-0bb09a81d877.png)

**Comment by areyouok** [comment]
jtcache不是把value原封不动的放到缓存里面的，而是有所包装。所以，你直接放一个裸value进去，然后用jetcache的get方法去读是不行的。
