### ISSUE TITLE
是否考虑实现内存缓存支持分布式

### ISSUE THREAD

**Issue by wzlee** [alibaba/jetcache#169]
希望支持实现分布式内存缓存，目前配置的cacheType=BOTH的话，内存缓存的数据无法同步

**Comment by areyouok** [comment]
redis已经有极好的性能，只有当调用量极高并且本地命中率足够高的情况才考虑使用BOTH，这种情况下，内存里面的缓存就是给redis挡一下，新版本的jetcache支持给local和remote设置不同的超时时间，你把local的超时时间设置短一点就好了。

发广播，通知所有服务器失效本地缓存，方案复杂且必要性不大。
