### ISSUE TITLE
cached集合的时候脏数据该如何处理

### ISSUE THREAD

**Issue by promiselonely** [alibaba/jetcache#171]
@Override
	@CacheUpdate(name = "cache.", key = "#t.id", value = "#t")
	public boolean update(T t) {
		return super.update(t);
	}

	@Override
	@CacheInvalidate(name = "cache.", key = "#t.id")
	public boolean delete(T t) {
		return super.delete(t);
	}

	@Cached(name = "cache.all.", key = "#c.simpleName", expire = 36000, cacheType = CacheType.REMOTE)
	public List<T> findAll(Class<T> c) {
		return super.findAll(c.getSimpleName());
	}

我想在update的时候更新findAll的cache或使其无效,请问有办法吗？

**Comment by areyouok** [comment]
用CacheInvalidate注解也可以让它失效，只要key一样就可以，不过你这里已经有一个CacheInvalidate注解了，现在还没有支持一个方法上多个注解。
