### ISSUE TITLE
Cached  cacheNullValue=true  无效，不能缓存null值

### ISSUE THREAD

**Issue by swcumt** [alibaba/jetcache#172]
@Cached 注解设置 cacheNullValue=true,还是不能缓存 null值

**Comment by areyouok** [comment]
这块是有单元测试的，肯定不会简单的不能用。你再看看或者给出更多的信息?

**Comment by geercode** [comment]
我好像也遇到这个问题了

**Comment by geercode** [comment]
@areyouok 二级缓存不生效,默认远程缓存是生效的

**Comment by geercode** [comment]
![image](https://user-images.githubusercontent.com/18181713/48059083-2e023800-e1f3-11e8-99d6-c7c80e9d79e3.png)
目测是这里出问题了

**Comment by areyouok** [comment]
感谢，已经修复了，发布前可以先自己打包2.5.10-SNAPSHOT版本用。
