### ISSUE TITLE
使用jetCache的时长问题

### ISSUE THREAD

**Issue by nangongh** [alibaba/jetcache#175]
所有JetCache作为缓存框架，前两次调用此方法，耗时都在30ms左右，后续调用都在1ms左右；已经配置了启动监听，服务启动时会把数据库里的内容加载到缓存。
![image](https://user-images.githubusercontent.com/44185165/46989970-de6ba780-d131-11e8-839b-6168642beab9.png)
所以，每次请求此方法都只会走缓存，不会进入方法体。但前两次耗时比较长，不知道原因，还望大神帮忙看看。可以邮件联系，邮箱是mutou0516@hotmail.com

**Comment by areyouok** [comment]
预热是需要时间的，头几次访问慢也正常，原因可能很多，比如序列化框架首次序列化一个类，需要初始化分析这个类，甚至动态生成字节码然后加载，JVM的JIT也需要跑几次才是才会激活，等等。

**Comment by nangongh** [comment]
我现在使用JetCache是有个同步接口:会将数据库的配置信息同步到缓存中。这样无论配置新增还是修改，都能通过同步接口更新缓存信息，但是配置一旦删除的话，因为数据库没有了信息，所以缓存没办法更新。我的想法是先获取缓存中所有的数据，清空掉。再访问数据库，同步数据到缓存。不知道JetCache有没有相应的API支持，今天看了许久，没有结论。

**Comment by areyouok** [comment]
没有清除所有数据的接口

**Comment by nangongh** [comment]
那像我这样的需求，有什么样的实现建议呢

**Comment by areyouok** [comment]
可以换一个前缀
