### ISSUE TITLE
支持redis cluster模式吗

### ISSUE THREAD

**Issue by ZEROyongyong** [alibaba/jetcache#178]

**Comment by areyouok** [comment]
jedis模式下不支持。

**Comment by yinjihuan** [comment]
什么模式下支持呢，我现在就遇到了这个问题

**Comment by yinjihuan** [comment]
是一定要用lettuce才行么

**Comment by areyouok** [comment]
根据jedis官方文档描述，它对于cluster的支持still under development，我就没有做

**Comment by yinjihuan** [comment]
still under development这个我也没试过，不知道行不行，之前一直用的spring data redis，里面是有个nodes的配置，我把所有节点都配上了，最好是能支持下，我刚刚改成了lettuce，如果能整合spring data redis就最好了
