### ISSUE TITLE
@Cached name use complex parameters

### ISSUE THREAD

**Issue by craftsman-li** [alibaba/jetcache#18]
方法缓存支持复杂的参数类型，也支持多参数，它使用keyConvertor将参数数组转换成底层缓存可以支持的key类型，当前唯一可用的keyConvertor是fastjson。fastjson使用getter/setter来分析类，因此复杂的参数类型也需要是一个javabean。

能不能给个例子？？    像下面这样写, 感觉不是使用json解析的,请给个例子吧... 
aaaa是一个List<String>入参
@Cached(expire = 1000, name = "#aaaa", keyConvertor = KeyConvertor.FASTJSON)

**Comment by areyouok** [comment]
现在确实只实现了一个fastjson KeyConvertor，你也可以实现自己的KeyConvertor，一般来说用fastjson就可以了。

通常我们在yml里面指定全局的keyConvertor，那么不用在Cached注解里面指定keyConvertor了。用List做入参是可以的，fastjson会把这个参数变成一个字符串（你应该知道一个list对象变成json字符串的时候是什么样子的，如果不知道可以自己动手试一下），这个字符串再加上一个前缀就是最终的cache key。

不过用list来做key是比较奇怪的，通常你自己直接操作缓存并不会这样做，这说明你加Cached注解的地方可能不是最优的。

**Comment by areyouok** [comment]
如果list里面的对象是固定的比较简单的类（有getter、setter方法）还好，比较复杂的类fastjson不能很好的把它转成string。

另外就是类里面最好不要有时间戳之类的字段，否则你每次都不会命中的。

**Comment by craftsman-li** [comment]
谢谢啦，我只是测试，对象嘛，所以就搞了个list做测试，真正用起来肯定不是list喽。谢谢啦

**Comment by rchlz** [comment]
@areyouok能不能实现一个gson的？现在gson用的也挺多

**Comment by areyouok** [comment]
开新的，不要挖坟。

更多的key convertor是可以考虑的，做哪些不做哪些也是问题。以前没有是因为之前觉得fastjson已经够用了。
