### ISSUE TITLE
valueEncoder 是否可以支持 json 格式

### ISSUE THREAD

**Issue by wallacepang** [alibaba/jetcache#181]
valueEncoder 可以自定义 序列化方式么？比如 json格式

**Comment by areyouok** [comment]
可以的。没有内置json序列化是因为它的兼容性不够好，不过你可以自己做。

**Comment by jdevsean** [comment]
请问怎么实现呢

**Comment by icemoff** [comment]
>  `RedisTemplate template = new RedisTemplate();
        template.setValueSerializer(jsonSerializer);`

期望像上面那种实现一个默认的，真实场景太需要这个了

**Comment by areyouok** [comment]
自定义序列化器看这里：
https://github.com/alibaba/jetcache/wiki/FAQ_CN
