### ISSUE TITLE
@Cached注解无效

### ISSUE THREAD

**Issue by zhanyue76** [alibaba/jetcache#184]
@Cached(name = "userCache",expire = 600)
    public String test(int key) {

        cache.put("call_myKey", "myValue:" + Math.random());
        String myValue = cache.get("call_myKey");
        LOG.info("test jet cache,myValue={}",myValue);
        return "myValue";
    }

EnableMethodCache配置没有问题

同样的代码有的项目就能存到redis中，有的就不行

**Comment by zhanyue76** [comment]
一个bean的方法在该类中被调用时无法缓存
如下：
 @Cached(name = "a:", key = "#arg")
public String a(String arg) {
          //TODO
    }
    public String b(String arg){
         a(arg);
    }

**Comment by areyouok** [comment]
这个问题问过很多次了，jetcache的方法缓存通过spring aop来实现的，spring aop使用cglib或者jdk proxy得到一个代理，你在代理上调用方法，相关的切面才会执行，一个类里面直接调用自己的另一个方法，没有经过代理，所以不会生效。
issue里面相关讨论很多，你可以看看。

aspectj通过在编译时对字节码进行增强，或通过java agent，可实现你想要的功能，不过配置起来也比较麻烦，jetcache暂未支持。
