### ISSUE TITLE
本地缓存的序列化方式是FastJson么

### ISSUE THREAD

**Issue by Ikki-Dai** [alibaba/jetcache#185]
请问 本地缓存的序列化方式用的是 fastjson 么，因为我有一个对象有一个字段是json string, 从本地缓存取出来后变成了 com.alibaba.fastjson.JSONObject

**Comment by areyouok** [comment]
local缓存不用序列化呀，直接内存引用就可以了，你还是把可重现的代码贴出来看看。

**Comment by Ikki-Dai** [comment]
看了一下，在本地缓存之后 代码有序列化为json 的操作，影响到了 本地缓存里的 对象，那我要把这行代码放到该对象 进行本地缓存之前去。是我疏忽了

**Comment by geercode** [comment]
……正常人类都不会再序列化去牺牲性能的吧
