### ISSUE TITLE
@CreateCache初始化为不同的实例

### ISSUE THREAD

**Issue by FloriaLI** [alibaba/jetcache#186]
我在一个工程的同一个子工程里面两个地方都用了@CreateCache,读取的是相同的配置文件，area都没有配置默认为default，name采用的相同的名字，cacheType都是LOCAL，但是这两个地方初始化成了两个不同的实例。

**Comment by areyouok** [comment]
两个spring context？

**Comment by FloriaLI** [comment]
在代码里@Autowired看了一下，context是同一个实例。

**Comment by areyouok** [comment]
你得给出重现步骤，在CreateCacheTest有针对这个案例的单元测试。

**Comment by areyouok** [comment]
时间太久，没有进一步的信息，我先关闭了。
