### ISSUE TITLE
有没有获取一个缓存所有内容的方法

### ISSUE THREAD

**Issue by gelonggld** [alibaba/jetcache#187]
有没有获取一个缓存所有内容的方法,还是必须解出原生对象才可以

**Comment by areyouok** [comment]
你想获取所有的key吗，没有这样的方法。

**Comment by leefj** [comment]
迫切需要这样的API,获取所有key，可以支持吗？ @areyouok

**Comment by areyouok** [comment]
不会支持的，获取所有key，性能太差，也不是所有的缓存都能支持
