### ISSUE TITLE
接口方法添加@Cached注解，其实现类内部方法调用此添加@Cached注解的方法，无法使用缓存

### ISSUE THREAD

**Issue by imiiot** [alibaba/jetcache#190]
代码结构示意如下，调用A 的 b方法，无法使用缓存：
public interface A {
    @Cached(name = "a.", cacheType = CacheType.LOCAL,localExpire = 60, localLimit = 100, keyConvertor = KeyConvertor.FASTJSON)
    List<Long> a();

    List<Long> b();
}

public class AImpl implements A {
    @Override
    public List<Long> a() {
        System.out.println("A Impl a is running");
        List<Long> longList = new ArrayList<>();
        longList.add(1L);
        return longList;
    }

    @Override
    public List<Long> b() {
        System.out.println("A Impl b is running");
        return a();
    }
}

**Comment by areyouok** [comment]
类内部直接调用，没有经过spring aop的代理，所以无法通过aop切面增加逻辑。

**Comment by imiiot** [comment]
ok，谢谢
