### ISSUE TITLE
关于 @Cached和@CacheInvalidate参数不一致的时候如何使用

### ISSUE THREAD

**Issue by zhanghongbin** [alibaba/jetcache#191]
缓存的方法
@Cached(name = "ResourceCategoryController.findAllCategory")
 public List<String> findAllCategory() 

去除缓存的方法
@CacheInvalidate(name = "ResourceCategoryController.findAllCategory")
 public boolean addCategory(String name, int order) 

但是去除缓存的方法有参数，如何能够直接根据name进行删除缓存，不把参数附加到name上当做key？

**Comment by areyouok** [comment]
你要指定key属性啊

**Comment by zhanghongbin** [comment]
> 你要指定key属性啊

我想让带@CacheInvalidate  方法生成 redis key的时候不带参数，如果指定key?

**Comment by areyouok** [comment]
这两个注解都可以指定key属性，如果你不指定，会自动生成

**Comment by zhanghongbin** [comment]
@CacheInvalidate 我注解的方法是带参数的，但我只想让他根据我指定的名字生成key,不想带上参数，如何去做？

**Comment by areyouok** [comment]
SpEL你给个固定字符串
