### ISSUE TITLE
最新版本与spring 5.0.x 兼容吗

### ISSUE THREAD

**Issue by geercode** [alibaba/jetcache#193]

**Comment by areyouok** [comment]
可以的，最新版本能支持5.1

**Comment by geercode** [comment]
我这边一直找不到jest或者lettuce的类，启动就有点问题啊，是不是版本有冲突之类的

**Comment by areyouok** [comment]
从4.0到5.1，所有的单测都能跑过的。

**Comment by geercode** [comment]
sorry,sorry.可能是我IDE的问题,redispool 跟lettuce的类老是找不见,问题已经解决了
