### ISSUE TITLE
看起来好像wiki有个地方写错了

### ISSUE THREAD

**Issue by geercode** [alibaba/jetcache#194]
[hiddenPackages应该是hidePackages才能生效](https://github.com/alibaba/jetcache/wiki/Config_CN)
或者应该把名字再统一一下  respect

**Comment by areyouok** [comment]
嗯，代码里面有名称不一致，我改一下，保持兼容

**Comment by areyouok** [comment]
已经改好了，下个版本可以同时支持yml中使用hidePackages和hiddenPackages
