### ISSUE TITLE
能否在key上去自定义定义当前调用的类+方法名称

### ISSUE THREAD

**Issue by fangting1989** [alibaba/jetcache#196]
因为部分的server进行了通用的提炼，所以每个类调用的方法都一样，这样我在定义基类缓存的时候就不能说写死某个类的名称了，而是要动态获取，现在已经支持了name的类名称+方法的自动生成，而这样无法对应到update，与delete方法上，所以能否支持参数配置获取，例如：原先springboot的 可以这样获取#root.target.getClass().getName()，看能否支持一下，辛苦

**Comment by areyouok** [comment]
你试试在key属性的script里面写targetObject，前面不加#

**Comment by fangting1989** [comment]
@areyouok 搞定了，谢谢，辛苦大神！！

**Comment by jiaweicat** [comment]
请教下，我们原来用的springboot的cache里有很多这样写的spel表达式,用来获取当前的方法名，#root.methodname,现在报错了，应该如何实现。
