### ISSUE TITLE
com.alicp.jetcache.support.CacheEncodeException

### ISSUE THREAD

**Issue by doudecheng** [alibaba/jetcache#197]
@CreateCache(expire = 100, cacheType = CacheType.BOTH, localLimit = 50)
    private Cache<String, MenuLine> menuLineCache;

menuLineCache.computeIfAbsent("mealAhead_test", (key) -> menuLineService.findMenuLine(BigDecimal.valueOf(3L)));
抛异常com.alicp.jetcache.support.CacheEncodeException: Java Encode error. msg=com.iflytek.meal.menu.entity.po.MenuLine

**Comment by areyouok** [comment]
实现Java序列化接口了吗？
