### ISSUE TITLE
Can we add a field to support null for cache?

### ISSUE THREAD

**Issue by wildwolfk** [alibaba/jetcache#20]
We currently is using jetcache for db query. 
Can u give a hint of how to set  @Cached when I wanna support anti cache?(e.g. record not found in table)

**Comment by areyouok** [comment]
```@Cached(expire=100, cacheNullValue=true)```

**Comment by areyouok** [comment]
https://github.com/alibaba/jetcache/wiki/Cached_EN

**Comment by wildwolfk** [comment]
Thx

**Comment by areyouok** [comment]
There is only one expire attribute on ```@Cached``` annotation.
However you can use ```@CreateCache``` to get a ```Cache``` instance, and then use this put method: 

```void put(K key, V value, long expire, TimeUnit timeUnit)```

see
https://github.com/alibaba/jetcache/wiki/CacheAPI_EN

**Comment by wildwolfk** [comment]
OK will u enable to contribute on cached for that?

**Comment by areyouok** [comment]
Thanks. The modification is not complex. I can add this feature if the requirements is common.
But can you tell why you need different expire time?

**Comment by wildwolfk** [comment]
the reason I wanna a different expire time is I use it to maintain some
inventory or promotion.
When it come to 0, there is two case,
1 people receive a warning and add more, so I wanna a short expire time for
it.
2 0 is forever 0 , then I hope to have a longer expire time for it.

huangli <notifications@github.com> 于2017年12月29日周五 下午1:57写道：
