### ISSUE TITLE
注解方式使用时，不指定超时时间，其他使用了超时时间的cached都不生效

### ISSUE THREAD

**Issue by kinglingspree** [alibaba/jetcache#202]
@Cached(name = "myCache:",key = "#key", cacheType = CacheType.REMOTE)
    String getRandomNum3(String key);

 
    @Cached(name = "myCache:", expire = 3600, key = "#key", cacheType = CacheType.REMOTE)
    String getRandomNum(String key);

此时getRandomNum3 不再有效，getRandomNum 也将失效，使用版本jetcache-starter-redis-lettuce 2.5.9

**Comment by areyouok** [comment]
你两个注解的name相同了，所以会生成同一个Cache实例，其中一个的配置把另一个就给覆盖了。

**Comment by kinglingspree** [comment]
覆盖为什么两个都失效呢,

**Comment by kinglingspree** [comment]
另外想问一下这个是否已用于生产

**Comment by areyouok** [comment]
你这里只有一个Cache实例（因为name是一样的），第一个配置把第二个覆盖了。

用于生产多年了。

**Comment by kinglingspree** [comment]
谢谢您这么耐心 😁
