### ISSUE TITLE
多次代理问题

### ISSUE THREAD

**Issue by gelonggld** [alibaba/jetcache#204]
刚才在一个`FileCountWorke`r的`bean`中发现使用了`@cached` 后`@autowired`的属性问空，经过排查发现如果不加`@cached`注解`bean` 会被初始化为 `FileCountWorker@xxxxx`  如果加了`@cached`注解则会被初始化为`FileCountWorker$$EnhancerBySpringCGLIB$$XXXX@xxxxx`  这时候这个代理对象里面的属性为空，搜了一下似乎是Aop的问题，不知道有办法解决吗

**Comment by gelonggld** [comment]
找到了kotlin 的问题，kotlin 里面的字段和方法必须为open

**Comment by areyouok** [comment]
嗯，jetcache基于aop，类最好不要申明为final
