### ISSUE TITLE
希望新增缓存实例的列表和当前缓存对象数量以及命中情况的Rest API或者方法

### ISSUE THREAD

**Issue by gumutianqi** [alibaba/jetcache#207]
实际项目中，可能会关注每个 Cache 实例的命中情况监控以及实例内的对象数量统计曲线，如果有了 API 或者方法，我们就可以自己扩展，甚至实现一个管理 jetcache 缓存的 dashboard webadmin 了

**feuture:**

```
1. 查询 Cache 实例列表；
2. 根据 Cache 实例 ID 查询配置项信息；
3. 动态更新 Cache 实例配置；
4. 根据 Cache 实例 ID 查询该实例内的缓存对象数；
5. 根据 Cache 实例 ID 查询该实例内的一定时间段的缓存命中情况；(也可以改用配置回调地址上报的方式)
```

**Comment by areyouok** [comment]
jetcache有个默认的monitor，他会统计缓存的命中率等信息，默认是输出到日志文件里面的。可以扩展它，也可以做自己的monitor。

实际上除了4不能做，1、2、3、5目前都可以做到，简单定制一下就可以。
