### ISSUE TITLE
如何获取泛型T对象的属性值？

### ISSUE THREAD

**Issue by azkoss** [alibaba/jetcache#208]
@Cached(name="service:",key = "targetObject.getClass().getSimpleName()+':'+#entity.id",  expire = 300,cacheType=CacheType.REMOTE)
	@Override
	public T save(T entity) throws Exception {
		try {
			return BaseMapper.save( entity);
		} catch (Exception e) {
			throw e;
		}
	}

**Comment by areyouok** [comment]
java的泛型编译以后就擦除了，就是Object。这里jetcache都是当Object处理的，没有必要获得T的实际类型。
