### ISSUE TITLE
@cache注解中能使用spel表达式自定义key吗

### ISSUE THREAD

**Issue by RomanticWd** [alibaba/jetcache#209]
类似于这种方式的spel，希望调用一个方法来处理此手机号。
```
@Cached(name="ls:dlc:scoring",key="#processMobile('#mobile')",cacheType=CacheType.REMOTE)
public String addRecord(String mobile) {
    return "test liu";
}
```
但是报错了：
```
org.springframework.expression.spel.SpelEvaluationException: EL1006E: Function 'processMobile' could not be found
```
是@cache注解不支持这种方式，还是说我有某些地方没有配置好。

**Comment by areyouok** [comment]
＃可以引用参数，参数类上如果有方法可以调用，但是不能引用这个bean上的方法。

**Comment by RomanticWd** [comment]
谢谢大佬，昨天翻之前的issue，看到使用targetObject解决了我的问题。我描述的不够清楚，我是想调用当前类中的一个方法去处理key。

**Comment by RomanticWd** [comment]
大佬，我目前还有一个问题：就是通过@cache创建缓存的时候没有设定超时时间，后面可以通过什么方法给这个缓存加上超时时间吗？

**Comment by areyouok** [comment]
这个需求，只能通过奇技淫巧了。createcache注解如果和cached注解的area和name都相同，会拿到同一个cache实例，你可以在createcache注解得到的cache实例上面做修改。

不过这样不太好哈，相当于是非标准api，不太有保证的，将来实现要是变了。。。。

**Comment by RomanticWd** [comment]
听了大佬的话，我是这样尝试的，但是却没有成功。。。
原先的@cache注解:
```
@Cached(name="ls:dlc:int",key="targetObject.processMobile(#mobile)",cacheType=CacheType.REMOTE,expire=60)
	public String addIntRecord(String mobile) {
		System.out.println("走本地方法");
		return "processMobile";
	}
```

@CreateCache注解
```
@CreateCache(name="ls:dlc:int",expire=100,cacheType=CacheType.REMOTE)
private Cache<String, String> userExpireCache;

public void updateIntRecord(String mobile) {
  userExpireCache.put("test", mobile);
  userExpireCache.put("test2", mobile, 60, TimeUnit.SECONDS);
}
```
按理两者name相同，@createcache创建的实例所设置的超时时间会覆盖掉@cache创建实例的超时时间，即@cache的超时时间由无限大变成100秒。但是最后的测试结果发现并没有改变。。。。

是我哪里弄错了吗？

**Comment by areyouok** [comment]
不一定是覆盖哦，哪个先初始化是不确定的，以先初始化的为准。

**Comment by areyouok** [comment]
你可以在postconstruct方法里面来修改超时时间，通过cache.config()

**Comment by RomanticWd** [comment]
大佬，我慌了。。。
你说的是以先初始化的为准，所以可以在postconstruct方法中修改超时时间。可目前我的需求是项目上线的时候可能是通过@cache注解对访问接口的请求生成缓存，这时候这些缓存我不需要它们过期。但是可能在上线一个月之后，我突然想让之前的这些缓存有个过期时间了。

这种情况大佬有什么建议吗？

**Comment by areyouok** [comment]
你把cache的name改一下，就相当于把以前的缓存废弃了（name会拼接到最终的redis key中）。

要是不想一个一个地方改的话，配置文件中还可以设置统一的key前缀。
