### ISSUE TITLE
是否考虑支持下移除缓存？

### ISSUE THREAD

**Issue by rchlz** [alibaba/jetcache#21]
spring cache没有支持ttl确实很不方便，但没有移除缓存更不方便。请问当缓存的对象发生了变化，怎么处理呢？

**Comment by areyouok** [comment]
现在没有计划支持，文档里面已经写了理由了，移除缓存是个非常灵活的行为，用注解做并不合适，真需要的话先用```@CreateCache```做吧。

https://github.com/alibaba/jetcache/wiki/Cached


https://github.com/alibaba/jetcache/wiki/CreateCache

**Comment by rchlz** [comment]
@areyouok 是不是有点多虑了，有总比没有好，复杂的场景毕竟是少数，即使复杂的场景，缓存失效顶多就是穿透到db，并无不妥，不一致性与正确性哪个更重要？

**Comment by areyouok** [comment]
实现基于注解的移除并不简单。

如果是简单基于主键的增删改查，查询上又缓存，要在update和delete的时候移除缓存还相对容易点。jetcache当前通过keyConvertor自动生成key，并不支持在注解中手工指定key，移除缓存的注解总要指定要移除哪个key吧，那么就需要支持在这个注解中指定key，这样改动就比较多。

如果不是见的的增删改查，有些方法返回的是一个查询视图。这种情况下，可能要把这个方法所有的缓存都移除掉。也许底层dao一个小小的udpate，上层很多查询方法都会受影响。

你期待的移除注解是什么样的，可以把使用它的代码写出来看看（包括```@Cached```的部分）。

**Comment by rchlz** [comment]
添加一个CacheEvict注解，简单的对key进行过期。
如果方法返回查询视图等复杂场景，那就不要为方法添加CacheEvict注解就行了。CacheEvict注解的使用也是取决于用户场景。
贴段代码，使用spring-cache的场景：
`@Cacheable(key="'vote-detail-' + #voteId", value = "voteCache")
    public VoteActivity getVoteActivity(int voteId){
    	return voteActivityMapper.select(voteId);
    }

    @CacheEvict(key="'vote-detail-' + #voteActivity.id", value = "voteCache")
    public SimpleResult<String> insertOrUpdate(VoteActivity voteActivity) {
    	
    	if(voteActivity != null && voteActivity.getId() != null && voteActivity.getId() > 0){
    		return this.update(voteActivity);
    	}else{
    		return this.insert(voteActivity);
    	}
    	
    }`

**Comment by areyouok** [comment]
我知道你的意思，我考虑一下。

**Comment by rchlz** [comment]
期待。

**Comment by areyouok** [comment]
将在2.4版本实现这个功能，主要代码已经提交在master。

现在还不能按SPEL表达式还不支持参数名称，需要用参数索引，比如"args[0]"，接下来看参数名称的支持要怎么做。

**Comment by rchlz** [comment]
看到wiki说明是支持spel了？比想象中的快，赞

**Comment by areyouok** [comment]
就是spel，用最新的2.4.1即可。
