### ISSUE TITLE
控制台出现了报错 JedisConnectionException:Unexpected end of stream 

### ISSUE THREAD

**Issue by xiaolongyuan** [alibaba/jetcache#213]
com.alicp.jetcache.AbstractCache         : jetcache(RedisCache) GET error. key=AAAAAAAAA. redis.clients.jedis.exceptions.JedisConnectionException:Unexpected end of stream.

**Comment by areyouok** [comment]
这是jedis的问题，你可以google一下看看。

**Comment by xiaolongyuan** [comment]
好的 感谢回复

**Comment by xiaolongyuan** [comment]
能建议下 redis  服务器 timeout  参数  和 Jedis的 timeout 怎么配置合适么？

**Comment by areyouok** [comment]
可以设置timeout的

**Comment by xiaolongyuan** [comment]
@areyouok 是的 我是想表达：这个参数建议值是多少  目前 redis自身配置timeout的300s  jetcache配置多少合适？ 感谢回复

**Comment by areyouok** [comment]
这个我谈不上多有经验，所以如何配置还是你自己来权衡吧
