### ISSUE TITLE
当注解用在接口上时指定key属性缓存就会失效

### ISSUE THREAD

**Issue by wushujia789** [alibaba/jetcache#214]
当注解用在接口上时指定key属性缓存就会失效
去掉了就可以了。
指定key属性时同样的配置  贴到实现类里面缓存就生效。
2.5.9版本
例子：
@Cached(name="userCache.", key="#userId", expire = 3600,cacheType = CacheType.BOTH, localLimit = 50)
	TSysUser getUserById(long userId);

**Comment by areyouok** [comment]
我猜你的javac没有指定-parameters参数

**Comment by wushujia789** [comment]
我编译和运行都是JDK1.8
可能我没有表述清楚，
同样的配置：
接口方法(无效)：
@cached(name="userCache.", key="#userId", expire = 3600,cacheType = CacheType.BOTH, localLimit = 50)
TSysUser getUserById(long userId);
实现类方法(有效)：
@cached(name="userCache.", key="#userId", expire = 3600,cacheType = CacheType.BOTH, localLimit = 50)
TSysUser getUserById(long userId){
}
接口方法(有效)key="#userId" 换成  key="args[0]":
@cached(name="userCache.", key="args[0]", expire = 3600,cacheType = CacheType.BOTH, localLimit = 50)
TSysUser getUserById(long userId);

**Comment by areyouok** [comment]
不是指定java8就可以，还要指定-parameters参数

**Comment by wushujia789** [comment]
非常感谢已经解决。
这里分享下步骤：
eclipse设置java8的javac 编译参数
先要将编译环境设置为jdk1.8，eclipse最好用新版本，然后就能看到该选项了，打包即可。
右键工程-->properties-->java Compiler   右边界面勾选Store information about method parameters(usable via reflection)


maven插件打包配置：在maven插件中增加-parameters参数
<plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.7.0</version>
                <configuration>
                    <source>1.8</source>
                    <target>1.8</target>
                    <encoding>UTF-8</encoding>
                    <compilerArgs>
                        <arg>-parameters</arg>
                    </compilerArgs>
                </configuration>
            </plugin>
</plugins>

**Comment by wushujia789** [comment]
另外再请教一个问题：
如果我有一个方法A需要开启事务的。但是该方法A中有调用另外一个方法B。且这个方法B设置了jetcache，这样就会出现脏读问题，jetcache里面有没有可以配置的注解在遇到开启事务时直接穿透缓存的。

**Comment by areyouok** [comment]
一个简单的办法是做两个方法，一个带缓存的，一个不带缓存。

Cached注解上面有enabled属性，设置为false可以配合EnableCache注解使用，我觉得设计的不是很好，文档里面就没怎么写。

**Comment by wushujia789** [comment]
非常感谢！
