### ISSUE TITLE
RedisLettuceCache.do_PUT_ALL方法bug

### ISSUE THREAD

**Issue by jingjian-1420** [alibaba/jetcache#216]
![image](https://user-images.githubusercontent.com/34017711/49373785-3be7a200-f73a-11e8-85f2-3c19408bddc7.png)
是否应该改成 下面这样?
future=future.thenCombine(resp, (failCount, respStr) -> "OK".equals(respStr) ? failCount : failCount + 1);

**Comment by jingjian-1420** [comment]
才能保证

**Comment by jingjian-1420** [comment]
才能保证
![image](https://user-images.githubusercontent.com/34017711/49373826-63d70580-f73a-11e8-97dd-999ef0badcc1.png)起作用？

**Comment by areyouok** [comment]
我修复了，你可以自己打包最新的snapshot版本用，当前master上是稳定的。

**Comment by areyouok** [comment]
2.5.10已经发布
