### ISSUE TITLE
@Cached注解中不指定name属性(暂定为A),@CacheInvalidate能指定到A缓存吗

### ISSUE THREAD

**Issue by rodzrk** [alibaba/jetcache#217]
源码中应该是这个控制的吧,如果不定义name,好像不能通过@CacheInvalidate删除
`    public void putByMethodInfo(String key, CacheInvokeConfig config) {
        methodInfoMap.put(key, config);
        CachedAnnoConfig cac = config.getCachedAnnoConfig();
        if (cac != null && !CacheConsts.isUndefined(cac.getName())) {
            cacheNameMap.put(cac.getArea() + "_" + cac.getName(), config);
        }
    }`

**Comment by areyouok** [comment]
为什么会有这个需求，如果要用CacheInvalidate就都该指定name

**Comment by kai-love-lin** [comment]
因为业务中使用的全类名加方法名作的key，如果需要指定的话，可能不太优雅，所以希望通过我们自己实现的CacheNameGenerator自动生成，同时我们有删除的需求，所以出现了这种情况

**Comment by areyouok** [comment]
最终的redis key是area+cacheName+key，所以你如果能两个注解的cache要一致

**Comment by kai-love-lin** [comment]
![qgn h dlrr0w70 oq8y g](https://user-images.githubusercontent.com/37720804/49573065-134ceb80-f978-11e8-935c-400bcd267c08.png)

我执行删除操作的时候，在这个地方发现他会去configMap下的cacheNameMap中找相对应的缓存，但是仅初始化的时候会对cacheNameMap进行put，如果初始未指定name，cacheNameMap中就不会存储，具体代码应该是我一开始发的那部分。

**Comment by areyouok** [comment]
你刚才贴出的代码是这样的，这些注解背后都对应一个Cache接口的实例，不同的cache实例会有不同的key前缀，为了操作Cached注解缓存的数据，CacheUpdate和CacheInvalidate需要使用相关的Cached注解定义的那个Cache实例，所以这两个注解是不初始化Cache实例的。

**Comment by kai-love-lin** [comment]
原因是我的@CacheInvalidate可能area+name不匹配，所以没有相对应的实例，因而为空是吗

**Comment by areyouok** [comment]
CacheInvalidate必须和一个Cached或者CreateCache的area+name相匹配

**Comment by kai-love-lin** [comment]
当前我的area未设置，采用的默认，@Cached中的name我没有指定，采用的默认的生成方式，key也是采用的默认生成方式，之后我执行存储操作，成功保存；

**Comment by areyouok** [comment]
我没有太理解你的意思，不过你的理解应该是不正确的。
使用最好手工指定name和key。

**Comment by rodzrk** [comment]
这个是我想错了,如果@Cache不指定name的话,CacheInvalidate找不到对应的该实例
![1](https://user-images.githubusercontent.com/37720804/50759119-084ee900-129f-11e9-8c30-2ee87278053f.png)
![2](https://user-images.githubusercontent.com/37720804/50759122-0c7b0680-129f-11e9-9989-a18bad418ed8.png)
