### ISSUE TITLE
JetCache怎么配置sentinel模式

### ISSUE THREAD

**Issue by crossbell** [alibaba/jetcache#218]
JetCache怎么配置哨兵sentinel模式呢？

**Comment by areyouok** [comment]
https://github.com/alibaba/jetcache/wiki/RedisWithJedis_CN

**Comment by areyouok** [comment]
https://github.com/alibaba/jetcache/wiki/RedisWithLettuce_CN

**Comment by 347154468** [comment]
请问使用jedis时的哨兵模式如何设置密码
