### ISSUE TITLE
使用Apollo Config启动时报错：com.alicp.jetcache.CacheConfigException: no remote cache builder: default 

### ISSUE THREAD

**Issue by Jason1220** [alibaba/jetcache#219]
经测试使用Apollo Config时报此错误，如果直接在程序中配置相同的配置可以正常工作；Debug时发现通过Apollo获取配置时没有初始化RedisAutoConfiguration。

**Comment by ZEROyongyong** [comment]
可采用spring的写法 springboot的写法会报此异常

**Comment by areyouok** [comment]
Apollo我还没用过，不太清楚遇到了什么问题，回头看一下，最近太忙了T_T

**Comment by Geek-S** [comment]
在yml中添加如下配置：
jetcache.local.default.type: caffeine
jetcache.remote.default.type: redis
就可以满足作者的Condition，就可以正常加载JetCache了

**Comment by Jason1220** [comment]
问题已解决。原因是Apolo的yml配置不支持SpringBoot，从yml切换为properties就好了。

**Comment by fsxtiger** [comment]
> 问题已解决。原因是Apolo的yml配置不支持SpringBoot，从yml切换为properties就好了。

请问应该如何解决，现在用也发现了这个问题
