### ISSUE TITLE
能不能实现一个gson的keyConvertor？现在gson用的也挺多

### ISSUE THREAD

**Issue by rchlz** [alibaba/jetcache#22]
考虑一下？gson好用啊

**Comment by areyouok** [comment]
更多的key convertor是可以考虑的，看需求。
之前只有fastjson是因为fastjson已经够用了。

**Comment by rchlz** [comment]
接着，spring cache的key支持spel表达式。虽然写起来麻烦但似乎也是比较优雅的一种解决方式，key比较灵活。
我不知道将整个bean对象序列化后作为key有没有不妥，这要是复杂对象光key占用的内存就不少，而且总感觉那么长的key怪怪的。

**Comment by areyouok** [comment]
Cached的出现其实最初是为了加在高层api上，这些高层api比如是给首页渲染数据的，开销非常大，调用很频繁，给它们加一个短期的缓存能显著提高性能。

这些高层api常常有很复杂的QueryObject，会按各种条件组合查询，如果要自己手工拼写key就太麻烦了，所以JetCache是自动生成的。各有优劣吧。

你要实现evict就要有手工指定key的功能。

**Comment by rchlz** [comment]
你说的这个其实toString就可以完成的，spel也支持方法调用，当然keyConvertor更简单些。不过这个实现用spel也没复杂多少，就多一个toString()而已。而spel带来的灵活性要高很多。

**Comment by areyouok** [comment]
现在已经可以通过spel指定key。虽然还没有内置别的keyConvertor，不过以后可以自定义keyConvertor了：

```java
@Cached(keyConvertor="bean:myConvertor", serialPolicy="bean:mySerialPolicy")
```
