### ISSUE TITLE
自动load有没有异步的load方式

### ISSUE THREAD

**Issue by lioutall** [alibaba/jetcache#220]
Cache<Long,UserDO> userCache = LinkedHashMapCacheBuilder.createLinkedHashMapCacheBuilder()
                .loader(key -> loadUserFromDatabase(key))
                .buildCache();

这里的loader是同步load的, 如果我定义static时, load会占用主线程时间, 如果load时间过久, 主线程就block.
在使用netty eventLoop时特别难受.

**Comment by areyouok** [comment]
自动load只支持小写的那些API，这些api都是同步的，所以没有办法支持异步加载。

目前能返回Result的（内含Future）的大写API都不使用loader，因为我要提供一个能直接访问缓存的方式。

**Comment by lioutall** [comment]
我昨天截错了代码, 应该截这段:
RefreshPolicy policy = RefreshPolicy.newPolicy(1, TimeUnit.MINUTES)
                .stopRefreshAfterLastAccess(30, TimeUnit.MINUTES);
Cache<String, Long> orderSumCache = LinkedHashMapCacheBuilder
                .createLinkedHashMapCacheBuilder()
                .loader(key -> loadOrderSumFromDatabase(key))
                .refreshPolicy(policy)
                .buildCache();
按我想来,  上面代码中loader本身就是无感知执行的,  大多数场景都是这样.
我添加一个loader就是想在缓存失效前去更新它, 至于它是同步, 还是异步, 肯定异步的资源利用率更高.
如果目前没有这个功能,  你能告诉我,  有没有添加这个异步loader的可能性.  我可以fork去实现.

**Comment by lioutall** [comment]
我的业务场景是,  微信的token 120分钟失效,   我每隔 115分钟去loader一次, loader时, 居然耗时5秒.
我的框架是异步框架,  分了`eventLoop`线程和`worker`线程.  `eventLoop`线程如果被阻塞,  会对整个框架造成极大的影响.  这个偶然的超时, 占用了一条`eventLoop`线程5秒.
缓存`cache`一般定义为 `static` `final`, 它在jvm里默认就使用`eventLoop`线程,  我连优化都不知从何下手.

**Comment by areyouok** [comment]
自动刷新是异步的，但是jetcache不知道什么时候开始去刷新哪个key，所以第一次get的时候才启动这个key的自动刷新任务（因为此时jetcache才拿到了key），以后就都是异步后台刷新了，长时间不使用的key，可以自动停止刷新（设置stopRefreshAfterLastAccess）。

你的需求，是不是系统启动的时候，同步或者异步get一下就好了？

**Comment by lioutall** [comment]
哦, 我明白你的意思了. 其实自动刷新已经是异步了, 只是执行刷新动作的线程选用错了. 应该选用`worker`线程.但是jetcache框架层不可能去做这个事情(选什么线程).
目前jetcache启动的时候是同步获取,  自动刷新就是异步获取.
把异步的实现方式提供抽象层,  让业务代码来实现, 应该就解决我说的这个问题了.
应该是这样:   LOADER( return future) .  只支持自动刷新,  走future.get().  
同步的loader还是得加上, 为了第一次刷新key.

**Comment by areyouok** [comment]
是的，get是同步的，所以如果没有命中的情况下，设置了loader肯定要等待loader的执行结果。后续的自动刷新是在jetcache自己的一个线程池里面执行的，这个线程池可以配置。

**Comment by lioutall** [comment]
那就是这个线程池了,   它的factory可以自定义吗?

**Comment by areyouok** [comment]
JetCacheExecutor，static方法自己set进去

**Comment by lioutall** [comment]
多谢啦
