### ISSUE TITLE
condition 如果返回判断结果为list 的size大小

### ISSUE THREAD

**Issue by zhanghongbin** [alibaba/jetcache#221]
我想通过condition 判断返回结果list的size >0 才进行缓存，表达式如何写

**Comment by areyouok** [comment]
表达式里面可以用result来引用返回值，不加#号。#号只能用于引用参数。

**Comment by zhanghongbin** [comment]
我的结果返回的是list ,用 condition = "result.size() > 0"  出错了  Method call: Attempted to call method size() on null context object  这是怎么回事

**Comment by areyouok** [comment]
你是不是应该先判空呢？

**Comment by zhanghongbin** [comment]
其它地方判断空了，就差size了，这个怎么写表达式？

**Comment by areyouok** [comment]
我刚才弄错了，你应该写在postCondition里面，condition是在缓存访问和实际方法执行之前进行判断的，所以此时还没有result。
