### ISSUE TITLE
新版本发布问题

### ISSUE THREAD

**Issue by Geek-S** [alibaba/jetcache#222]
中央仓库2.5.10版本，jetcache-parent没有发布，导致其它模块无法找到依赖

**Comment by areyouok** [comment]
昨天上传的时候是有点问题，我再看看

**Comment by areyouok** [comment]
可以email给我，pom里面有我的邮箱

**Comment by areyouok** [comment]
好像发布不上去了，等等看不行我发个新版本了

**Comment by areyouok** [comment]
用2.5.10.1吧，已经发布了
