### ISSUE TITLE
有办法可以操作本地缓存吗

### ISSUE THREAD

**Issue by kai-love-lin** [alibaba/jetcache#223]

**Comment by areyouok** [comment]
一句话让我怎么回答呢？

**Comment by kai-love-lin** [comment]
我现在想要使用LinkedHashMap作为本地缓存,如果使用@CacheInvalidate可以支持模糊匹配吗,如果不行,我想自己拿到这个map自定义一些操作

**Comment by areyouok** [comment]
如果你想直接操作Cache实例，最好是不要用方法缓存，而是使用CreateCache注解来获得Cache实例。
