### ISSUE TITLE
REMOTE缓存无效

### ISSUE THREAD

**Issue by Geek-S** [alibaba/jetcache#226]
使用CacheType.REMOTE时，缓存数据写到redis了，但是刷新还是会执行方法，麻烦看一下，是缺少配置吗？https://gitee.com/gs-s/gs-jetcache

**Comment by areyouok** [comment]
先看一FAQ吧。

**Comment by areyouok** [comment]
可能是你没有指定-parameters编译参数，我以后加到faq里面去。

**Comment by Geek-S** [comment]
找到原因了，是CacheType.REMOTE时，反序列化失败了，导致重新执行方法。

**Comment by romever** [comment]
> 找到原因了，是CacheType.REMOTE时，反序列化失败了，导致重新执行方法。

您好，麻烦问下您最后怎么解决的此问题？
