### ISSUE TITLE
FeignClient上面加Cached无法获取到缓存

### ISSUE THREAD

**Issue by optimistic9527** [alibaba/jetcache#228]
![image](https://user-images.githubusercontent.com/37545032/50463382-55d97500-09c6-11e9-8df3-acba44cd4732.png)

**Comment by wu191287278** [comment]
翻了一下代码， 看来一下jetcache 在beandefinetion阶段进行代理的，FeignClient 也是在beandefinetion 进行代理。 可能是在 jetcache 在beandefinetion 只处理了class 类，并没有处理接口类

**Comment by wu191287278** [comment]
尝试一下retrofit 缓存方法， 在feign拦截器上 做缓存处理。这样处理起来应该更得心应手些

**Comment by areyouok** [comment]
jetcache处理了接口可类，注解可以随意加在接口或者类上。
feign我自己没有试过，aop的顺序可以通过EnableMethodCache上的order属性来调整，或者可能要调整别的（比如Feign）的顺序。
