### ISSUE TITLE
CaffeineCacheBuilder 应该unwrap成什么类

### ISSUE THREAD

**Issue by 39012090** [alibaba/jetcache#229]
LinkedHashMapCacheBuilder unwrap 成 LinkedHashMapCacheBuilder，
CaffeineCacheBuilder 应该unwrap成什么类呢

**Comment by areyouok** [comment]
没太明白你的意思，只有Cache才能unwrap，你可以看看CaffeineCache类里面的unwrap方法：
https://github.com/alibaba/jetcache/blob/master/jetcache-core/src/main/java/com/alicp/jetcache/embedded/CaffeineCache.java

**Comment by 39012090** [comment]
了解，谢谢
