### ISSUE TITLE
remote模式，缓存与数据库数据不一致，如何处理

### ISSUE THREAD

**Issue by zuowenmou** [alibaba/jetcache#230]
您好，如题，有两个问题
   1. 缓存与数据库数据不一致，更新或保存时，数据库数据已更新，redis更新失败
       暂时解决方案：手动删除对应的redis的key
      问题：针对此问题，是否有事务控制？或有没有推荐的处理办法
   2.数据库新增属性字段时，缓存如何及时刷新？
        暂时解决方案：手动删除对应的redis的key

**Comment by gumutianqi** [comment]
@zuowenmou 这种情况，可以考虑采用MQ 的方式去更新缓存；并且保证缓存的时效性在数据有效性的可接受范围内就行了
