### ISSUE TITLE
支持redis集群么？

### ISSUE THREAD

**Issue by majintao** [alibaba/jetcache#236]
Redis Sentinel
Redis Cluster

**Comment by majintao** [comment]
集成springboot2.x 使用的

**Comment by areyouok** [comment]
看文档，用jedis可以支持Sentinel，用lettuce都支持

**Comment by majintao** [comment]
嗯，再问下 阿里内部有大范围使用jetcache么？    生产成熟度如何？

**Comment by areyouok** [comment]
我离职快两年了，之前我们部门在用，后来我没有专门调研过。
成熟度是很高了，近些月主要是一些次要bug修复。
