### ISSUE TITLE
Spring boot 在容器中连接集群时，服务启动过程被卡住，未报异常。

### ISSUE THREAD

**Issue by xubitao** [alibaba/jetcache#239]
服务的最后日志输出如下：

`2019-01-16 14:43:48.484 DEBUG 1 --- [           main] c.alicp.jetcache.anno.aop.CachePointcut  : check method match true: method=findTokenOrSaveToken, declaringClass=c.f.t.s.d.d.e.t.g.XXXService, targetClass=c.f.t.s.d.d.e.t.g.XXXService`

未报任何异常，但服务启动过程被卡住。不知道什是什么原因？
集群配置如下：
`jetcache:
  areaInCacheName: false
  remote:
    default:
      type: redis.lettuce
      keyConvertor: fastjson
      uri:
      - redis://10.70.128.11:6379
      - redis://10.70.128.12:6379
      - redis://10.70.128.13:6379
      - redis://10.70.128.24:6379`

**Comment by xubitao** [comment]
刚才配置的显示效果不太好。
jetcache:
  areaInCacheName: false
  remote:
    default:
      type: redis.lettuce
      keyConvertor: fastjson
      uri:
      - redis://10.70.128.17:6379
      - redis://10.70.128.19:6379
      - redis://10.70.128.18:6379
      - redis://10.70.128.21:6379

**Comment by areyouok** [comment]
可以jstack看一下线程在干嘛。
现在有个已知的问题，有的情况下使用了CachePenetrationProtect可能导致被卡住，参考编号 #234 ，用最新的master版本可以解决这个问题。
