### ISSUE TITLE
缓存自动刷新失败的情况下如何做监控，是否有hook，自定义一些后续操作？

### ISSUE THREAD

**Issue by JoshShaw** [alibaba/jetcache#241]
RT

**Comment by JoshShaw** [comment]
项目用的是Springboot，找了autoConfigureBeans这个入口添加自己实现的CacheMonitor，以实现缓存load时候的监控操作。
不过感觉这样不够优雅。

**Comment by areyouok** [comment]
你可以提供一个自己的ConfigProvider(这是个ConditionalOnMissingBean，定义在JetCacheAutoConfiguration类里面，你要是自己提供了，就会覆盖默认的)。你的SpringConfigProvider继承SpringConfigProvider，覆盖newContext方法，返回一个你自己的SpringCacheContext，SpringCacheContext上面可以覆盖的方法很多，比如buildCache，你可以在这里安装你的监控器。
