### ISSUE TITLE
非注解方式，如何获取已有的Cache对象（Builder api是否只能创建Cache时使用？）

### ISSUE THREAD

**Issue by dotyso** [alibaba/jetcache#242]
如果我已经用Builder api创建了Cache

如何在其它程序中再次取出这个Cache，而不指定过期时间等参数

**Comment by areyouok** [comment]
这个manager里面就是一个ConcurrentHashMap嘛，自己往ConcurrentHashMap里面放也不难。

也可以把cache做成一个bean，自动注入到需要它的bean里面。

**Comment by dotyso** [comment]
@areyouok 这里面有很多细节问题，如Cache失效了，如何从ConcurrentHashMap移除

希望未来增加一个CacheManager进行Cache管理功能

**Comment by areyouok** [comment]
这个CacheManager已经有里，在最新的master上有

**Comment by malcolmshen** [comment]
> 这个CacheManager已经有里，在最新的master上有

通过bulider.buildCache()创建的缓存，不会出现在CacheManager里面吗?
