### ISSUE TITLE
二级缓存问题

### ISSUE THREAD

**Issue by yinjihuan** [alibaba/jetcache#245]
想请问下用注解缓存数据，当设置CacheType.BOTH的时候会使用二级缓存，这个里面会优先使用本地还是远程呢？

还有就是如果我想做热点key的自动发现，有没有什么方法能够设置让某个key直接使用本地的缓存

**Comment by yinjihuan** [comment]
关于第二个问题，如果这样的话我必须把所有要缓存的方法都配置二级缓存，因为我无法预计我的哪个缓存数据会变成热点Key,其实我想表达的意思是能不能有动态配置的一个概念，当我基于访问数据发现某段时间这个Key被大量访问的时候才去开启本地缓存

**Comment by yinjihuan** [comment]
假设出现qps很高的情况下，我基于日志中输出的统计知道了哪些key访问的比较多，这个时候开启二级缓存是可以的，问题是得重启呀，我想的是动态调整。就是这么个需求。

**Comment by areyouok** [comment]
现在做不到运行时变更缓存的类型。
另外按key统计的需求很奇怪，你想表达的是不是按Cache实例统计？

**Comment by yinjihuan** [comment]
我在想想怎么处理，多谢、
