### ISSUE TITLE
unwrap获取jedisPool问题

### ISSUE THREAD

**Issue by zpypy** [alibaba/jetcache#247]
你好，我的项目不是springboot，所以需要使用Cache的unwrap来获取jedispool，有一个疑惑，我怎么拿到cache实例调用unwrap方法呢？
JedisPool jedisPool=cache.unwrap(JedisPool.class);
cache怎么得到呢？我尝试用下面这个方法得到cache：
Cache<String, Integer> cache =  RedisCacheBuilder.createRedisCacheBuilder()
                .expireAfterWrite(200, TimeUnit.SECONDS)
                .buildCache();
结果报错了：
Caused by: com.alicp.jetcache.CacheConfigException: keyPrefix is required

**Comment by areyouok** [comment]
和你是不是springboot没有关系。CacheBuilder是用来创建Cache实例的，如果你要创建RedisCache，创建RedisCache实例需要提供jedispool和keyprefix作为入参。

你试试用CreateCache注解就拿到Cache实例了。

**Comment by zhuhelei** [comment]
@zpypy ，怎么拿到的

**Comment by Skqing** [comment]
同问，怎么拿到？

**Comment by Skqing** [comment]
> 拿到了，感谢

解决了不发答案，不厚道啊

**Comment by areyouok** [comment]
用CreateCache注解，area和name属性设置为和Cached一样，就会拿到同一个Cache实例。

另外， 新版可以通过CacheManager.defaultManager().getCache(String area, String cacheName)拿到

**Comment by Skqing** [comment]
多谢
