### ISSUE TITLE
Cache.Both的更新策略是怎么样的想了解下谢谢

### ISSUE THREAD

**Issue by coolieo** [alibaba/jetcache#248]
1.想了解下更新策略
2.目前最新的版本是否支持，不同层级的缓存设置不同的TTL

**Comment by areyouok** [comment]
1、更新的时候先更新本地，再更新remote
2、支持。注解上有localExpire属性，可以单独指定本地缓存的超时时间。

**Comment by coolieo** [comment]
1. 更新远程后采用什么机制通知其他集群的本地更新的？
2. 更新本地成功，更新远程失败产生的集群本地不一致性怎么解决啊？

**Comment by areyouok** [comment]
1、目前没有这样的机制。你可以给本地缓存设置一个比较小的超时时间；也可以自己定制，Cache实例上面可以添加monitor来监听。
2、没有处理，需要设置好TTL。

**Comment by yy-Eddy** [comment]
你好 areyouok :  我想问下,关于您说的分布式下如何定制缓存更新后 一级缓存失效的处理?
2:想问下 什么时候可以支持缓存上的key支持多参数(也就是说key属性是一个数组类型) 
3:关于缓存后的key问题,我在测试时候 没有找到redis对应key,是否框架中有另外加一层前缀 (因为我们之前有用j2cache)

**Comment by areyouok** [comment]
1、cache上可以加monitor，你在monitor里面需要自己收发消息实现所有服务器都更新

2、现在缓存失效和更新的时候，设置multi属性，是支持多参数的，Cached注解不支持。你可以自己拿到Cache实例来通过API操作，不是所有东西都要用注解。

3、有统一前缀

**Comment by yy-Eddy** [comment]
1. 是实现CacheMonitor接口吗?实现好的类 如何让它生效?

2. cache实例是
        @CreateCache(expire = 6,timeUnit = TimeUnit.SECONDS,cacheType = CacheType.REMOTE)
	private Cache<String, String> userCache;
这种形式获得一个全局通用的cache实例吗.(我现在是每个service类都有这样注入)

3. 刚才在JetCacheInterceptor里面开始debug断点 没找到您写的前缀, 有点渣, 还请明示

**Comment by areyouok** [comment]
1、提供一个你自己的SpringConfigProvider bean，覆盖newContext方法，返回一个覆盖了buildCache方法的SpringCacheContext，你可以在这里把定制的monitor添加上去，保证全局有效。
2、多个类里面CreateCache注解的name属性和area属性一样，会生成同一个cache实例
3、看ExternalCacheConfig.keyPrefix

**Comment by subenkun** [comment]
能提供一个monitor的demo吗？

**Comment by yy-Eddy** [comment]
hi huangli : 关于第一个你的回答,我今天下午跟随源码,也看了SpringConfigProvider,SpringCacheContext,GlobalCacheConfig等相关类.实际添加监控是通过  defaultCacheMonitorManager.add的对吗? 那为什么没有把这个当做一个bean.我这里按照你说 继承了CacheContext类并覆盖了buildCache方法,可是不能拿到DefaultCacheMonitorManager对象 我没办法加入到监控列表内.

**Comment by areyouok** [comment]
> hi huangli : 关于第一个你的回答,我今天下午跟随源码,也看了SpringConfigProvider,SpringCacheContext,GlobalCacheConfig等相关类.实际添加监控是通过 defaultCacheMonitorManager.add的对吗? 那为什么没有把这个当做一个bean.我这里按照你说 继承了CacheContext类并覆盖了buildCache方法,可是不能拿到DefaultCacheMonitorManager对象 我没办法加入到监控列表内.

这个defaultCacheMonitorManager是用来做定期统计的，如果你的monitor是用来做1级缓存失效的，没必要加到这个manager里面去。你调用super.buildCache以后，在返回值里面加上你的monitor就好了。

**Comment by yy-Eddy** [comment]
> > hi huangli : 关于第一个你的回答,我今天下午跟随源码,也看了SpringConfigProvider,SpringCacheContext,GlobalCacheConfig等相关类.实际添加监控是通过 defaultCacheMonitorManager.add的对吗? 那为什么没有把这个当做一个bean.我这里按照你说 继承了CacheContext类并覆盖了buildCache方法,可是不能拿到DefaultCacheMonitorManager对象 我没办法加入到监控列表内.
> 
> 这个defaultCacheMonitorManager是用来做定期统计的，如果你的monitor是用来做1级缓存失效的，没必要加到这个manager里面去。你调用super.buildCache以后，在返回值里面加上你的monitor就好了。


是的是的,我使用更新注解跟踪源码 最终的通知是在AbstractCache的notify方法 获取config().getMonitors()的所有添加到监控集合里面的的对象循环通知.但是我按照你说的加入实现CacheMonitor接口的对象到Monitors后 在更新时的cache对象里面的config看不到初始化时候加入的那个LocalCacheMonitor对象:

public class LocalCacheContext extends CacheContext{

	private ApplicationContext applicationContext;
	
	public LocalCacheContext(GlobalCacheConfig globalCacheConfig,ApplicationContext applicationContext) {
		super(globalCacheConfig);
		this.applicationContext = applicationContext;
	}

	@Override
	protected Cache<?, ?> buildCache(CachedAnnoConfig cachedAnnoConfig, String area, String cacheName) {
		Cache<?,?> cache = super.buildCache(cachedAnnoConfig, area, cacheName);
		CacheMonitor localCacheMonitor = new LocalCacheMonitor();
		cache.config().getMonitors().add(localCacheMonitor);
		return cache;
	}
}


public class LocalCacheMonitorProvider extends ConfigProvider {

	private ApplicationContext applicationContext;

	public LocalCacheMonitorProvider() {
		this(null);
	}

	public LocalCacheMonitorProvider(ApplicationContext applicationContext) {
		if (this.applicationContext == null) {
			this.applicationContext = applicationContext;
		}
	}

	@Override
	public LocalCacheContext newContext(GlobalCacheConfig globalCacheConfig) {
		return new LocalCacheContext(globalCacheConfig, applicationContext);
	}
}


@Component
public class JetcacheSupport implements InitializingBean, DisposableBean, ApplicationContextAware {

	private ApplicationContext applicationContext;
	
	@Autowired
	private GlobalCacheConfig globalCacheConfig;

	@CreateCache()
	private Cache<String, String> monitorsCache;
	
	@Override
	public void setApplicationContext(ApplicationContext applicationContext) throws BeansException {
		this.applicationContext = applicationContext;
	}
	
	@Override
	public synchronized void destroy() throws Exception {
		System.out.println("end");
	}
	
	@Override
	public synchronized void afterPropertiesSet() throws Exception {
		System.out.println("start");
		LocalCacheMonitorProvider localCacheMonitorProvider = this.localCacheProvider();
		LocalCacheContext localCacheContext = localCacheMonitorProvider.newContext(this.globalCacheConfig);
		CachedAnnoConfig cachedAnnoConfig = getCachedAnnoConfig(getMonitorsCacheField().getAnnotation(CreateCache.class));
		localCacheContext.buildCache(cachedAnnoConfig, cachedAnnoConfig.getArea(), cachedAnnoConfig.getName());
	}
	
	private LocalCacheMonitorProvider localCacheProvider() {
		LocalCacheMonitorProvider localCacheMonitorProvider = new LocalCacheMonitorProvider(this.applicationContext);
		return localCacheMonitorProvider;
	}

	private Field getMonitorsCacheField() {
		Field monitorsCacheField = null;
		try {
			monitorsCacheField = getClass().getDeclaredField("monitorsCache");
		}catch (Exception e) {
			e.printStackTrace();
		}
		return monitorsCacheField;
	}
	
	private CachedAnnoConfig getCachedAnnoConfig(CreateCache ann) {
		CachedAnnoConfig cac = new CachedAnnoConfig();
        cac.setArea(ann.area());
        cac.setName(ann.name());
        cac.setTimeUnit(ann.timeUnit());
        cac.setExpire(ann.expire());
        cac.setLocalExpire(ann.localExpire());
        cac.setCacheType(ann.cacheType());
        cac.setLocalLimit(ann.localLimit());
        cac.setSerialPolicy(ann.serialPolicy());
        cac.setKeyConvertor(ann.keyConvertor());
        return cac;
	}
}

**Comment by areyouok** [comment]
我没看懂你的JetcacheSupport 是要干什么，buildCache方法是jetcache自动调用，你通过覆盖定制一下，返回的cache里面安装上你的monitor就行了，buildCache方法不需要你来调用。

**Comment by yy-Eddy** [comment]
> 我没看懂你的JetcacheSupport 是要干什么，buildCache方法是jetcache自动调用，你通过覆盖定制一下，返回的cache里面安装上你的monitor就行了，buildCache方法不需要你来调用。


JetcacheSupport 是为了初始化后生成一个ConfigProvider子类 调用你说的newContext然后产生一个LocalCacheContext，这样就可以调用buildCache方法。 因为不知道覆盖的这个buildCache方法如何被调用，所以有了上面这一系列操作。 如您所说 那我是不是只需要继承CacheContext并重写buildCache方法即可？ 自定义ConfigProvider的子类也不需要了。你那里会自动调用所有继承CacheContext类的子类（或者说所有重写的buildCache方法）是吗

**Comment by areyouok** [comment]
JetCacheAutoConfiguration里面，springConfigProvider方法是ConditionalOnMissingBean，所以你只要配置一个自己的SpringConfigProvider（加上```@Bean```注解）就可以，提供自己的ConfigProvider的目的是为了提供定制的SpringCacheContext、然后覆盖buildCache方法就可以里，没有你那么麻烦。
