### ISSUE TITLE
@CacheInvalidate 同时删除多个缓存key的使用方法是什么

### ISSUE THREAD

**Issue by zuowenmou** [alibaba/jetcache#250]
你好，@CacheInvalidate 如何同时删除多个缓存key的具体方法怎么实现

**Comment by zuowenmou** [comment]
例如：
@CacheInvalidate(name="getA",key="id")
list  getA(int id){
}
@CacheInvalidate(name="getB",key="id")
bean getB(int id){
}
@CacheInvalidate(name="getA",key="id")
@CacheInvalidate(name="getB",key="id")
insertA_B(int id){
}
该如何做

**Comment by areyouok** [comment]
有个multi属性，你看看javadoc文档？
```
    /**
     * If evaluated key is an array or an instance of java.lang.Iterable,
     * set multi to true indicates jetcache to invalidate each element of the iterable keys.
     */
```

**Comment by zuowenmou** [comment]
@CacheInvalidate(name="getB",key="ids", multi=true)
update(List ids){
}
