### ISSUE TITLE
叶大神，求救

### ISSUE THREAD

**Issue by redwolf0007** [alibaba/jetcache#252]
我的应用里面使用JetCache的时候，配置文件也有，并且在启动类也有@EnableMethodCache(basePackages = "xxx.xxx.xxx")和@EnableCreateCacheAnnotation注解，但是就是老是报异常：no local cache builder: default，怎么也不行，我仅仅是在接口的方法上面写了@Cached(name = "GameMetaManager.getGameSomeInfoByToken", expire = 600, cacheType = CacheType.LOCAL)，然后写一个类implements这个接口，然后@Override目标方法而已，就是无限的报那个异常，叶大神救命

**Comment by areyouok** [comment]
你的全局配置文件里面没有配置本地cache

**Comment by redwolf0007** [comment]
叶大神，您说的“全局配置文件里面没有配置本地cache”这个我还是不太明白如何配置，因为是第一次使用，所以请您见谅

1.我的项目里面包含了application-jetcache.yml配置文件

**Comment by areyouok** [comment]
看起来配置了，不过你贴的代码没有缩进，我也不一定能看出来
看看pom引入了相关的starter没有，另外你的配置文件不会没加载吧

**Comment by redwolf0007** [comment]
叶先生，我昨天反复测试@Cached这样的接口方法上加注解的方式，怎么都提示之前的错误，但是我后来尝试了JetCache的其他使用方式，却成功了，如下：
@Component
public class GameMetaManagerImpl implements GameMetaManager
{
    @Autowired
    MetaGameChannelImpl metaGameChannelImpl;

    Cache<String, ChannelDO> cacheChannelDOMap;

    @PostConstruct
    private void initCache()
    {
        cacheChannelDOMap = LinkedHashMapCacheBuilder.createLinkedHashMapCacheBuilder()
                .expireAfterWrite(600, TimeUnit.SECONDS)
                .buildCache();
    }

    @Override
    public ChannelDO getGameSomeInfoByToken(String accessToken)
    {
        ChannelDO channelDO = null;
        channelDO = cacheChannelDOMap.get(accessToken);
        if(channelDO == null)
        {
            List<AgtechGameChannel> agtechGameChannelList = metaGameChannelImpl.selectAgtechGameChannelByAccessToken(accessToken);
            if(agtechGameChannelList.size() > 0)
            {
                channelDO = agtechGameChannelList.get(0).convertToChannelDO();
                cacheChannelDOMap.put(accessToken,channelDO);
            }
        }
        return channelDO;
    }
}
如果我的这样的方式能够成功的话，是不是就说明JetCache的配置文件还是加载了的，而且我项目的POM文件里面是有Starter的，如下：
<dependency>
            <groupId>com.alicp.jetcache</groupId>
            <artifactId>jetcache-starter-tair</artifactId>
            <version>${jetcache.version}</version>
            <exclusions>
                <exclusion>
                    <artifactId>ch.qos.logback</artifactId>
                    <groupId>logback-core</groupId>
                </exclusion>
                <exclusion>
                    <groupId>ch.qos.logback</groupId>
                    <artifactId>logback-classic</artifactId>
                </exclusion>
                <exclusion>
                    <artifactId>slf4j-log4j12</artifactId>
                    <groupId>org.slf4j</groupId>
                </exclusion>
            </exclusions>
</dependency>
<dependency>
            <groupId>com.alicp.jetcache</groupId>
            <artifactId>jetcache-core</artifactId>
            <version>${jetcache.version}</version>
</dependency>
问题很灵异，“no local cache builder: default”的问题我还在继续研究中，谢谢叶先生百忙之中的解答

**Comment by redwolf0007** [comment]
上面的POM引用是因为包含了特殊字符，所以格式变化了，叶先生请见谅

**Comment by areyouok** [comment]
markdown的格式你学习一下啊

**Comment by areyouok** [comment]
没有进一步信息，我先关闭了
