### ISSUE TITLE
出现Error creating bean with name 'metaDataSourceAdvisor': Cannot resolve reference to bean 'methodSecurityMetadataSource' 

### ISSUE THREAD

**Issue by eanfs** [alibaba/jetcache#253]
Error creating bean with name 'metaDataSourceAdvisor': Cannot resolve reference to bean 'methodSecurityMetadataSource' while setting constructor argument; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'org.springframework.security.config.annotation.method.configuration.GlobalMethodSecurityConfiguration': Initialization of bean failed; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'objectPostProcessor' defined in class path resource [org/springframework/security/config/annotation/configuration/ObjectPostProcessorConfiguration.class]: Unsatisfied dependency expressed through method 'objectPostProcessor' parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'jetcache2.internalCacheAdvisor' defined in class path resource [com/alicp/jetcache/anno/config/JetCacheProxyConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.alicp.jetcache.anno.aop.CacheAdvisor]: Factory method 'jetcacheAdvisor' threw exception; nested exception is java.lang.NullPointerException

**Comment by areyouok** [comment]
信息不足

**Comment by areyouok** [comment]
没有进一步信息，我先关闭了

**Comment by AshitaKaze** [comment]
2

**Comment by ahmedshehab123** [comment]
3

**Comment by ahmedshehab123** [comment]
any update about this issue
