### ISSUE TITLE
叶大神，有个小问题，求救

### ISSUE THREAD

**Issue by Anthony-chi** [alibaba/jetcache#254]
叶大神，我们公司用jetcache，缓存用的都是remote远程缓存，用的redis，我们习惯于用如下注解
@Cached(name = "listCommunity", cacheType = CacheType.REMOTE, expire = CacheConstant.EXPIREAFTERWRITEINMILLIS)

一个注解就可以方便的配置缓存。

有没有这样一种注解，根据注解的入参name删除远程基于key的redis缓存呢，这样可以很灵活的通过key删除任意一个缓存，达到随时按要求更新缓存效果。

**Comment by areyouok** [comment]
有的，先看看wiki
