### ISSUE TITLE
当入参为java bean类型的入参时，@Cached注解生成的remote的redis缓存后，下次调接口并没有走缓存

### ISSUE THREAD

**Issue by Anthony-chi** [alibaba/jetcache#256]
主要是入参为java class的bean时，就会出现这种情况。
redis已经有了缓存数据，可是调接口查询的时候并没有从缓存获取。

**Comment by areyouok** [comment]
复杂的类型你自己指定key比较好，class对象的转换成key字符串的结果不是固定的

**Comment by Anthony-chi** [comment]
我指定key和name了，我把方法签名贴出来吧。

@Override
    @Cached(name = CacheConstant.QUERYBYDEVICEGROUPIDANDDEVICENAME, key = "#queryByDeviceGroupIdAndDeviceName", cacheType = CacheType.REMOTE, expire = CacheConstant.EXPIREAFTERWRITEINMILLIS)
    public PagerResult<RaDeviceDTO> queryByDeviceGroupIdAndDeviceName(Long deviceGroupId, DeviceGroupingRelationDTO deviceGroupingRelationDTO, List<String> roleIds) {
        return this.raUserDeviceGroupService.queryByDeviceGroupIdAndDeviceName(deviceGroupId, deviceGroupingRelationDTO, roleIds);
    }

**Comment by areyouok** [comment]
你的key写错了，你的方法并没有一个参数叫queryByDeviceGroupIdAndDeviceName

**Comment by Anthony-chi** [comment]
@Cached(name = CacheConstant.QUERYBYGROUPTYPEANDROLES, key = "#deviceGroupingRelationDTO.deviceIds", cacheType = CacheType.REMOTE, expire = CacheConstant.EXPIREAFTERWRITEINMILLIS)

好的，key这样写没问题了，如果我想key里配多个属性呢，因为java类入参的话，参数可能是多个。

**Comment by Anthony-chi** [comment]
我找到方法了，符合SpEL表达式规范就行了，谢谢

**Comment by areyouok** [comment]
先看看wiki，wiki上面的文档我已经写的很全了
