### ISSUE TITLE
CreateCache在Controller层为null

### ISSUE THREAD

**Issue by liujiuwu** [alibaba/jetcache#258]
@Slf4j
@RestController
@RequestMapping("/api/demos")
public class DemoRest {
    @CreateCache(name = "userCache", expire = 180, cacheType = CacheType.BOTH, localExpire = 120)
    private Cache<Long, String> userCache;

spring 4.3中使用
<dependency>
                <groupId>com.alicp.jetcache</groupId>
                <artifactId>jetcache-redis</artifactId>
                <version>2.5.11</version>
            </dependency>
            <dependency>
                <groupId>com.alicp.jetcache</groupId>
                <artifactId>jetcache-redis-lettuce4</artifactId>
                <version>2.5.11</version>
            </dependency>

@Configuration
@EnableMethodCache(basePackages = "com.xxx.mall")
@EnableCreateCacheAnnotation
public class JetCacheConfig {

    @Bean
    public SpringConfigProvider springConfigProvider() {
        return new SpringConfigProvider();
    }

    @Bean
    public GlobalCacheConfig config(SpringConfigProvider configProvider, RedisClient redisClient) {
        Map localBuilders = new HashMap(1);
        EmbeddedCacheBuilder localBuilder = LinkedHashMapCacheBuilder.createLinkedHashMapCacheBuilder().keyConvertor(FastjsonKeyConvertor.INSTANCE);
        localBuilders.put(CacheConsts.DEFAULT_AREA, localBuilder);

        Map remoteBuilders = new HashMap(1);
        RedisLettuceCacheBuilder remoteCacheBuilder = RedisLettuceCacheBuilder.createRedisLettuceCacheBuilder()
                .keyConvertor(FastjsonKeyConvertor.INSTANCE)
                .valueEncoder(JavaValueEncoder.INSTANCE)
                .valueDecoder(JavaValueDecoder.INSTANCE).redisClient(redisClient);

        remoteBuilders.put(CacheConsts.DEFAULT_AREA, remoteCacheBuilder);

        GlobalCacheConfig globalCacheConfig = new GlobalCacheConfig();
        globalCacheConfig.setConfigProvider(configProvider);
        globalCacheConfig.setLocalCacheBuilders(localBuilders);
        globalCacheConfig.setRemoteCacheBuilders(remoteBuilders);
        globalCacheConfig.setStatIntervalMinutes(1);
        globalCacheConfig.setAreaInCacheName(false);
        return globalCacheConfig;
    }
}

@Service类可以使用@CreateCache创建缓存，但是在@RestController中 始终为null

请问这是什么原因？

**Comment by areyouok** [comment]
AutoWired注解可以注入其它bean应该就可以用CreateCache，两者的注入原理是基本一样的。

你看看日志里面是不是有什么报错？

**Comment by areyouok** [comment]
时间太久，没有进一步的信息，我先关闭了。
