### ISSUE TITLE
缓存穿透问题

### ISSUE THREAD

**Issue by yhan219** [alibaba/jetcache#259]
我看了下CachePenetrationProtect注解只支持单jvm加载保护，还是解决不了缓存穿透问题。我看CacheRefresh注解是有redis锁的，是否同时加以下三个注解就能解决缓存穿透问题
```
    @Cached(cacheType = CacheType.BOTH)
    @CacheRefresh(refresh = 1,timeUnit = TimeUnit.HOURS)
    @CachePenetrationProtect
```
另外`@CacheRefresh`注解的timeout单位是否就是timeUnit

**Comment by areyouok** [comment]
> 另外@CacheRefresh注解的timeout单位是否就是timeUnit
是

CacheRefresh可以保证你的缓存总是能命中，除非缓存发生淘汰

**Comment by yhan219** [comment]
好的，谢谢，我跑一下试试
