### ISSUE TITLE
方法内修改参数对象导致缓存无效

### ISSUE THREAD

**Issue by chenchi2038** [alibaba/jetcache#261]
```
@Cached(cacheType = CacheType.LOCAL)
public List<Viewpoint> query(QueryRequest request)
```

在query方法内部修改了request的某个属性，会导致get和put缓存值使用了不同的key（request的json字符串），从外部看来，用同样的request参数多次调用，每次都会实际执行query方法，就好像缓存没有起作用。

不知道这算是使用错误，还是bug。

**Comment by areyouok** [comment]
不会的，同一次调用，get和put是一个key。你的缓存没有命中的原因是，第二次调用和第一次调用生成的key不一样，也就是第一次put和第二次get的key不一样。

这个我没有办法的，在query内部改request本来就不是一个好习惯。这种情况下你可以通过key属性指定你要的key。

**Comment by areyouok** [comment]
时间太久，没有进一步的信息，我先关闭了。

**Comment by harvies** [comment]
> 不会的，同一次调用，get和put是一个key。你的缓存没有命中的原因是，第二次调用和第一次调用生成的key不一样，也就是第一次put和第二次get的key不一样。
> 
> 这个我没有办法的，在query内部改request本来就不是一个好习惯。这种情况下你可以通过key属性指定你要的key。

通过key属性指定key后后期新增字段就不能缓存了
