### ISSUE TITLE
关于ProxyCache的设计问题

### ISSUE THREAD

**Issue by coolieo** [alibaba/jetcache#262]
Hi @areyouok 。
   ProxyCache这个接口从名字或是方法行为上都好像在设计一个代理类。
1.个人理解代理类 是对外访问有做些额外的限制之类的，但是ProxyCache我在core的模块没有看到Proxy的本意？
2.如果LoadingCache是为了采用Decorator的设计。那么如下的结构是不是会合理点？（这里可能没理解ProxyCache的本意，故如下调整，特请教作者谢谢）
![ProxyCache](https://user-images.githubusercontent.com/18713777/54281978-e3942c00-45d5-11e9-8925-d831d6176d51.png)

**Comment by areyouok** [comment]
ProxyCache也可以叫DecoratorCache，但是它不应该继承AbstractCache，AbstractCache上实现了一些默认的方法，ProxyCache是不该有的。

另外还会有一些微妙的变化，比如如果ProxyCache包装继承AbstractCache并且包装了get方法，那么就把AbstractCache里面的get方法给覆盖了，将无法产生Cache事件。
