### ISSUE TITLE
synchronized 与 ConcurrentHashMap 需要同时使用吗？

### ISSUE THREAD

**Issue by smqhws** [alibaba/jetcache#264]
我注意到在CacheContext.java 第 121 行，操作一个 ConcurrentHashMap 对象时采取了加锁操作，这个是出于什么考虑？若是bug的话CreateCacheAnnotationBeanPostProcessor.java 第 77 行也存在这种操作，其他地方没有留意，可能需要再排查。

**Comment by areyouok** [comment]
synchronized里面的代码有很多行啊，加锁保证只有一个线程进去初始化
