### ISSUE TITLE
想自定义key的前缀，但是只能对于非String参数(KEY)的缓存才有效

### ISSUE THREAD

**Issue by wushujia789** [alibaba/jetcache#267]
public class CustomFastjsonKeyConvertor extends FastjsonKeyConvertor{
	private String preKey = "";
	public CustomFastjsonKeyConvertor(String preKey) {
		if(preKey!=null && !"null".equalsIgnoreCase(preKey)) {
			this.preKey = preKey ;
		}
	}
	
	public static FastjsonKeyConvertor getInstance(String preKey) {
		return new CustomFastjsonKeyConvertor(preKey);
	}
	
	@Override
	public Object apply(Object originalKey) {
        if (originalKey == null) {
            return null;
        }
        if (originalKey instanceof String) {
            return this.preKey+originalKey;
        }
        return this.preKey+JSON.toJSONString(originalKey);
    }
}

**Comment by wushujia789** [comment]
public class JetCacheConfig {

    @Bean
    public Pool<Jedis> pool(){
    	GenericObjectPoolConfig pc = new GenericObjectPoolConfig();
        pc.setMinIdle(Util.toint(Property.getProperty("jet.redis.pool.minIdle")));
        pc.setMaxIdle(Util.toint(Property.getProperty("jet.redis.pool.maxIdle")));
        pc.setMaxTotal(Util.toint(Property.getProperty("jet.redis.pool.maxTotal")));
        String password = Property.getProperty("jet.redis.pass") ;
        if(Util.isNull(password)){
        	password = null ;
        }
        return new JedisPool(pc, Property.getProperty("jet.redis.ip"), Util.toint(Property.getProperty("jet.redis.port")),Util.toint(Property.getProperty("jet.redis.timeout")),password,Util.toint(Property.getProperty("jet.redis.database")));
    }

    @Bean
    public SpringConfigProvider springConfigProvider() {
        return new SpringConfigProvider();
    }

    @Bean
    public GlobalCacheConfig config(SpringConfigProvider configProvider, Pool<Jedis> pool){
    	FastjsonKeyConvertor localFastjsonKeyConvertor = FastjsonKeyConvertor.INSTANCE ;
    	FastjsonKeyConvertor remoteFastjsonKeyConvertor = CustomFastjsonKeyConvertor.getInstance(Property.getProperty("jet.redis.preKey")) ;
        Map localBuilders = new HashMap();
        //EmbeddedCacheBuilder localBuilder = LinkedHashMapCacheBuilder.createLinkedHashMapCacheBuilder().keyConvertor(localFastjsonKeyConvertor);
        EmbeddedCacheBuilder localBuilder = CaffeineCacheBuilder.createCaffeineCacheBuilder().keyConvertor(localFastjsonKeyConvertor);
        localBuilders.put(CacheConsts.DEFAULT_AREA, localBuilder);
        
        
        Map remoteBuilders = new HashMap();
        RedisCacheBuilder remoteCacheBuilder = RedisCacheBuilder.createRedisCacheBuilder().keyConvertor(remoteFastjsonKeyConvertor)
                                                                                          .valueEncoder(JavaValueEncoder.INSTANCE)
                                                                                          .valueDecoder(JavaValueDecoder.INSTANCE)
                                                                                          .jedisPool(pool);
        remoteBuilders.put(CacheConsts.DEFAULT_AREA, remoteCacheBuilder);

        GlobalCacheConfig globalCacheConfig = new GlobalCacheConfig();
        globalCacheConfig.setConfigProvider(configProvider);
        globalCacheConfig.setLocalCacheBuilders(localBuilders);
        globalCacheConfig.setRemoteCacheBuilders(remoteBuilders);
        globalCacheConfig.setStatIntervalMinutes(15);
        globalCacheConfig.setAreaInCacheName(false);

        return globalCacheConfig;
    }
}

当cache的key值为String类型时不会进入CustomFastjsonKeyConvertor这个类的断点，Long型或者其他非String型的KEY值时会进入断点

**Comment by wushujia789** [comment]
package com.alicp.jetcache.external;

import com.alicp.jetcache.AbstractCache;
import com.alicp.jetcache.CacheConfigException;
import com.alicp.jetcache.CacheException;

import java.io.IOException;

/**
 * Created on 2016/10/8.
 *
 * @author <a href="mailto:areyouok@gmail.com">huangli</a>
 */
public abstract class AbstractExternalCache<K, V> extends AbstractCache<K, V> {

    private ExternalCacheConfig<K, V> config;

    public AbstractExternalCache(ExternalCacheConfig<K, V> config) {
        this.config = config;
        checkConfig();
    }

    protected void checkConfig() {
        if (config.getValueEncoder() == null) {
            throw new CacheConfigException("no value encoder");
        }
        if (config.getValueDecoder() == null) {
            throw new CacheConfigException("no value decoder");
        }
        if (config.getKeyPrefix() == null){
            throw new CacheConfigException("keyPrefix is required");
        }
    }

    public byte[] buildKey(K key) {
        try {
            Object newKey = key;
            if (key instanceof byte[]) {
                newKey = key;
            } else if(key instanceof String){
                newKey = key;
            } else {
                if (config.getKeyConvertor() != null) {
                    newKey = config.getKeyConvertor().apply(key);
                }
            }
            return ExternalKeyUtil.buildKeyAfterConvert(newKey, config.getKeyPrefix());
        } catch (IOException e) {
            throw new CacheException(e);
        }
    }

}
这里有必要key instanceof String加这个判断么？直接走else不行么？

**Comment by areyouok** [comment]
key前缀yml里面可以统一配置，不能满足你的需求么？

**Comment by wushujia789** [comment]
有些公共的代码在common包里面，被多个工程引用，又当心key出现冲突，所以才有此需求。

**Comment by areyouok** [comment]
不同的工程部署时可以配置不同的key前缀

**Comment by wushujia789** [comment]
您指的key前缀在yml里面是怎么配置？

**Comment by areyouok** [comment]
ExternalCacheAutoInit.java里面读取了一个keyPrefix，这个属性不常用，我就没写到文档里面

**Comment by evancyz** [comment]
> 这个属性不常用，我就没写到文档里面

感觉是个common的需求。。

**Comment by weaponready** [comment]
```java
    public byte[] buildKey(K key) {
        try {
            Object newKey = key;
            if (key instanceof byte[]) {
                newKey = key;
           } else if(key instanceof String){  //  这里有必要key instanceof String加这个判断么？直接走else不行么？
                newKey = key;
            } else {
                if (config.getKeyConvertor() != null) {
                    newKey = config.getKeyConvertor().apply(key);
                }
            }
            return ExternalKeyUtil.buildKeyAfterConvert(newKey, config.getKeyPrefix());
        } catch (IOException e) {
            throw new CacheException(e);
        }
    }
```
> 这里有必要key instanceof String加这个判断么？直接走else不行么？

同样的困扰! 想在这里加租户隔离信息,发现String类型的key无法走自定义KeyConverter了...

**Comment by wenhaiLi-HappyPD** [comment]
> ExternalCacheAutoInit.java里面读取了一个keyPrefix，这个属性

大佬好哇，我现在遇到同样的问题，请问如何在yml里面配置一个keyPrefix

**Comment by pengliang0601** [comment]
> keyPrefix
你好，请问如果keyPrefix是动态生成的有办法么。 我的业务场景是这样的，系统是一个多租户版本，租户标识存在登录信息里面的，当请求进来后根据登录标识来做数据隔离

**Comment by wenhaiLi-HappyPD** [comment]
***@***.***注解重写部分核心源码。JetCacheInterceptor的invoke里面改写，手动加入前缀。但是这样改的话，目前自动刷新的源码没抓摸透，自动刷新又是另外一部分代码了。如果不使用自动刷新也没必要使用JetCache。换个组件吧


文海
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "alibaba/jetcache"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年12月10日(星期六) 下午3:43
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [alibaba/jetcache] 想自定义key的前缀，但是只能对于非String参数(KEY)的缓存才有效 (#267)





  
keyPrefix
 你好，请问如果keyPrefix是动态生成的有办法么。 我的业务场景是这样的，系统是一个多租户版本，租户标识存在登录信息里面的，当请求进来后根据登录标识来做数据隔离
