### ISSUE TITLE
expire能否支持添加随机时间

### ISSUE THREAD

**Issue by Vincent-Zeng** [alibaba/jetcache#269]
作者您好，请教expire参数能否支持附加一个随机时间，以减少key大规模失效的概率。

**Comment by areyouok** [comment]
这个需求很奇怪，你put的时候也不会同时put呀。

除非能证明这是个典型场景，否则我不会做的。

**Comment by areyouok** [comment]
如果是个例需求，可以fork了自己实现

**Comment by Vincent-Zeng** [comment]
@areyouok 比如客户端上报状态，高峰时几k的qps，基本就是同一时间put了，不知道是不是比较普遍的场景。我这里只是想到会有这样的情况，提出来供您参考下，也还没实际遇到过。

**Comment by Vincent-Zeng** [comment]
@areyouok 如果没必要，那就close吧。

**Comment by areyouok** [comment]
几千qps是对应几千个不同的key吗，如果这个量级的写入都不怕，失效时的读又怕什么呢？
另外还看这些key是否会一直被访问，难道一直有几千qps的读去分别访问这些key？

**Comment by Vincent-Zeng** [comment]
@areyouok 你说的对 一般这种上报接口会异步实现 这样看来应该是个伪需求 关问题吧
