### ISSUE TITLE
缓存自动刷新对二级缓存不起作用

### ISSUE THREAD

**Issue by chenchi2038** [alibaba/jetcache#27]
```
    @Cached(name = ":message", key = "#id", expire = 2, cacheType = CacheType.BOTH)
    @CacheRefresh(refresh = 1, stopRefreshAfterLastAccess = 1800)
    public String getMessage(int id) {
        log.info("get message {}", id);
        return String.format("message %d is %s", id, System.currentTimeMillis());
    }
```
缓存类型设置为local或者remote的时候，自动刷新都能起作用，但是设置为both的时候，缓存就没有自动刷新了，是不支持么？

**Comment by areyouok** [comment]
设计上并没有不支持。

正常情况下，cacheType = CacheType.BOTH的时候，刷新是全局的，也就是在应用服务器集群中，一个周期只有一台服务器在刷（这样是为了降低后端数据库的负担），它只能刷新自己的本地缓存和redis，而其它服务器的本地缓存是无法刷新的。

我查看了一下代码，有不细致的地方，BOTH的情况下，刷新程序只刷新了远程缓存，而对自己的本地缓存未刷新，所以。。。

这个问题我稍后改一下。

**Comment by chenchi2038** [comment]
我看了源代码，在com.alicp.jetcache.anno.support.CacheContext类的buildCache方法中，
构建多级缓存时，确实没有调用setRefreshPolicy来设置刷新策略。

**Comment by areyouok** [comment]
改好了。稍后会发布正式的版本，你也可以直接用master自己编译一个来用，当前master是稳定的，自从2.4.1发布以来没有功能改动。

**Comment by areyouok** [comment]
可用

mvn versions:set -DnewVersion=2.4.2-SNAPSHOT

来更新版本号。

**Comment by chenchi2038** [comment]
响应速度真快，点赞

**Comment by areyouok** [comment]
2.4.2已经发布了
