### ISSUE TITLE
通过@Cache缓存方法返回的对象，但是保存在redis中的是乱码，而且keyConverter已经是fastjson，如何可以把对象按json字符串的形式存储？

### ISSUE THREAD

**Issue by leoxu1719** [alibaba/jetcache#273]

**Comment by areyouok** [comment]
key convertor和value Encoder/Decoder是两个东西，jetcache现在默认的 Encoder/Decoder是基于java序列化的，你也可以定制自己的，可以参考这里：

https://github.com/alibaba/jetcache/blob/master/samples/simple-samples/src/main/java/FastjsonValueEncoder.java
