### ISSUE TITLE
能否失效一个area？

### ISSUE THREAD

**Issue by zuowenmou** [alibaba/jetcache#274]
如题，一个area会有多个key，但能否删除一个area呢

**Comment by areyouok** [comment]
没有直接的方法可以让它们全部失效，可以更换cache的name，这样生成的key前缀就不同了

**Comment by zuowenmou** [comment]
> 没有直接的方法可以让它们全部失效，可以更换cache的name，这样生成的key前缀就不同了

是否考虑做个area失效的功能。从设计角度讲：这样会更灵活控制。

**Comment by areyouok** [comment]
没有好的办法可以实现这个功能，所以暂时没有这个打算
