### ISSUE TITLE
分布式时，同一个key进行失效和查询，会不会出现数据库数据不存在，缓存数据还有的情况

### ISSUE THREAD

**Issue by zuowenmou** [alibaba/jetcache#276]
如题，分布式时，同一个key进行失效和查询，会不会出现数据库数据不存在，缓存数据还有的情况？

**Comment by zuowenmou** [comment]
代码逻辑，比如：
一、删除数据
       A1.删除数据库
       A2.失效缓存
二、查询数据
      B1.查询数据库
      B2.添加缓存
这四步执行顺序交叉时，如B1-A1-A2-B2，这个时候有可能出现数据不一致情况

**Comment by zuowenmou** [comment]
这个问题解决思路应该怎样呢

**Comment by areyouok** [comment]
这个问题和jetcache本身没有关系了，你可以看这篇文章
https://coolshell.cn/articles/17416.html
