### ISSUE TITLE
注解@CacheInvalidate能不能通过name前缀批量删除缓存呢

### ISSUE THREAD

**Issue by qewsd** [alibaba/jetcache#279]
@CacheInvalidate(name = "test",key="*",multi = true)
    void test();
例如这样 将缓存前缀是test的全部删除，如何做到呢，redis有这个功能，jetcache可以做到吗

**Comment by Skqing** [comment]
估计要用API去实现了，注解好像没有

**Comment by qewsd** [comment]
api有实现方式吗？

**Comment by areyouok** [comment]
不能支持，你可以拿到jedis或luttece的command自己搞
