### ISSUE TITLE
spring boot下按现有代码没法添加自定义monitor么？

### ISSUE THREAD

**Issue by marcosweng** [alibaba/jetcache#281]

**Comment by areyouok** [comment]
JetCacheAutoConfiguration里面，springConfigProvider方法是ConditionalOnMissingBean，所以你只要配置一个自己的SpringConfigProvider（加上```@Bean```注解），覆盖newContext方法就可以提供自己定制的SpringCacheContext，然后在你的SpringCacheContext里面覆盖buildCache方法就可以了，先调用super.buildCache，在返回的Cache上安装你的monitor然后再返回即可。

**Comment by areyouok** [comment]
整体来说还是略复杂，以后简化下

**Comment by yinjihuan** [comment]
调用super.buildCache，然后加monitor，这样无法知道当前缓存的key是什么啊，只有area和cacheName
