### ISSUE TITLE
为什么我加了缓存之后，redis 每分钟set 数量大幅降低

### ISSUE THREAD

**Issue by teli5200** [alibaba/jetcache#283]
@CreateCache(expire = 120, cacheType = CacheType.BOTH)
    private Cache<String, Object> onDemandCache;

配置如上，redis 每分钟set 数量由之前的 每分钟 6000，降低到 每分钟 129 ，但是业务看来并没有什么问题，但是 数据库压力翻倍 
本地缓存  为 caffeine

**Comment by teli5200** [comment]
之前是 lettuce 同步方式，过期时间都是一样

**Comment by areyouok** [comment]
你给的这些信息不足以判断的

**Comment by areyouok** [comment]
时间太久，没有进一步的信息，我先关闭了。
