### ISSUE TITLE
并发情况redis 获取缓存失败

### ISSUE THREAD

**Issue by linchuyao** [alibaba/jetcache#284]
![image](https://user-images.githubusercontent.com/32710423/56635724-2b0fdc80-6699-11e9-99d4-8769aa20b9bb.png)

**Comment by areyouok** [comment]
你可以先调用大写的GET、PUT方法检查一下返回值。

**Comment by linchuyao** [comment]
使用lettuce
@CreateCache(name = “test:verifyCode”,
        expire = 300,
        cacheType = CacheType.REMOTE)
    private Cache<String, String> verificationCodeCache;

verificationCodeCache.put(key, verificationCode);

String trueVerificationCode = verificationCodeCache.get(key);
 log.info("***************获取注册短信验证码{}",trueVerificationCode);

![image](https://user-images.githubusercontent.com/32710423/56780005-29b4f000-6810-11e9-828e-1f9485c0a35a.png)

**Comment by areyouok** [comment]
lettuce的put方法是异步的，因为put方法没有返回值，put方法返回的时候，操作可能还没有完成。
你用大写的PUT方法，然后检查一下返回值，就同步堵塞了。

**Comment by areyouok** [comment]
没有进一步的反馈，我先关闭了，如果能提供进一步的信息，可以再打开。
