### ISSUE TITLE
使用lettuce作为客户端,初始化失败

### ISSUE THREAD

**Issue by XoEvn** [alibaba/jetcache#285]
报错信息:Invocation of init method failed; nested exception is com.alicp.jetcache.CacheException: LettuceObjects is not initialized
yaml文件
jetcache:
    statIntervalMinutes: 1
    areaInCacheName: false
    local:
      default:
        type: caffeineCache
        keyConvertor: fastjson
    remote:
      default:
        type: redis.lettuce
        keyConvertor: fastjson
        uri: redis://127.0.0.1:6379/

**Comment by areyouok** [comment]
你给的信息不完整

**Comment by XoEvn** [comment]
你好，解决了。是没有添加依赖，没有添加jetcache-start-lettuce，谢谢。这款框架很好，希望能越来越好！
在2019年04月27日 10:33，huangli 写道：

你给的信息不完整
