### ISSUE TITLE
redis可以支持Lua脚本吗？

### ISSUE THREAD

**Issue by alexyangbjb** [alibaba/jetcache#286]
redis可以支持Lua脚本吗？

**Comment by alexyangbjb** [comment]
是否提供执行Lua脚本的接口

**Comment by areyouok** [comment]
redis支持脚本，但是jetcache没有支持，可以unwrap拿到jedis或者luttece client，然后执行脚本。

**Comment by alexyangbjb** [comment]
> redis支持脚本，但是jetcache没有支持，可以unwrap拿到jedis或者luttece client，然后执行脚本。

明白
