### ISSUE TITLE
用CreateCache创建的cache能遍历所有的Key吗？

### ISSUE THREAD

**Issue by alexyangbjb** [alibaba/jetcache#288]
用CreateCache创建的cache能遍历所有的Key吗？

**Comment by areyouok** [comment]
不能

**Comment by alexyangbjb** [comment]
> 不能

如果我要遍历的话，有接口可以拓展吗？

**Comment by areyouok** [comment]
可以unwrap拿到jedis或者luttece client。
然后就该问redis能不能了，redis确实提供了keys命令，但是因为性能原因不建议用。

**Comment by alexyangbjb** [comment]
> 可以unwrap拿到jedis或者luttece client。
> 然后就该问redis能不能了，redis确实提供了keys命令，但是因为性能原因不建议用。

谢谢 明白

**Comment by alexyangbjb** [comment]
> 可以unwrap拿到jedis或者luttece client。
> 然后就该问redis能不能了，redis确实提供了keys命令，但是因为性能原因不建议用。

大神我再问一下，如果我拿到了luttece client之后，并使用之后需要关闭操作吗？
RedisClient redisClient = (RedisClient) testCache.unwrap(RedisClient.class);
RedisCommands<String, String> async = redisClient.connect().sync();

这里的connect需要关闭吗？

**Comment by areyouok** [comment]
你自己创建的东西，就自己关闭。
你可以unwrap出来一个RedisCommands或者RedisAsyncCommands用，不用你关闭。
