### ISSUE TITLE
请教一个本地缓存最大数量的问题

### ISSUE THREAD

**Issue by CodingOX** [alibaba/jetcache#294]
你好，想请教一个关于本地缓存最大数量如何界定的问题。
1、比如我全局设置了最大为100个，但是在某个方法上设置为200个。
那么是不是指这个方法对应的缓存最大为200个？还是所有其他的缓存加一起最大数量变成了200个？
2、再比如我在另外一个方法设置了本地缓存最大300个，那么又是指什么了？

**Comment by areyouok** [comment]
1、方法上的设置覆盖全局设置
2、不同的方法是不同的Cache实例，各自独立

**Comment by CodingOX** [comment]
3Q
