### ISSUE TITLE
使用lettcue，redis连接断开，GET操作一直进行重连

### ISSUE THREAD

**Issue by bobchen124** [alibaba/jetcache#295]
使用lettcue，redis连接断开，GET操作一直进行重连，业务程序无法感知，该怎么解决？

**Comment by bobchen124** [comment]
主要配置如下：
jetcache.statIntervalMinutes=16
jetcache.areaInCacheName=false
jetcache.local.default.type=caffeine
jetcache.local.default.keyConvertor=fastjson
jetcache.remote.default.valueEncoder=kryo
jetcache.remote.default.valueDecoder=kryo
jetcache.remote.default.poolConfig.minIdle=10
jetcache.remote.default.poolConfig.maxIdle=10
jetcache.remote.default.poolConfig.maxTotal=64

jetcache.remote.default.type=redis.lettuce
jetcache.remote.default.keyConvertor=fastjson

jetcache.remote.default.uri[0]=redis://172.16.10.164:6379
jetcache.remote.default.uri[1]=redis://172.16.10.165:6379
jetcache.remote.default.uri[2]=redis://172.16.10.166:6379

**Comment by areyouok** [comment]
什么版本？新版有默认超时时间的

**Comment by bobchen124** [comment]
> 什么版本？新版有默认超时时间的

2.5.4版本，也试了超时时间，好像不起作用，应该使用哪个版本？怎么配置？

**Comment by areyouok** [comment]
用最新的正式版2.5.12

**Comment by bobchen124** [comment]
> 用最新的正式版2.5.12

换了版本，但是ResulCode返回是no_exists，无法判断redis已经断开连接，有什么好的用法判断redis连接断开吗？或者返回ResulCode有个类型标识连接断开呢？

**Comment by areyouok** [comment]
不会的，连接不上会返回FAIL
