### ISSUE TITLE
后续远程Cache是否会支持IgniteCache

### ISSUE THREAD

**Issue by ankeway** [alibaba/jetcache#296]
后续远程Cache是否会支持IgniteCache

**Comment by areyouok** [comment]
我暂时没有这个计划。
你需要的话自己实现个？不是很麻烦

**Comment by ankeway** [comment]
> 我暂时没有这个计划。
> 你需要的话自己实现个？不是很麻烦

有没有钉钉群或者联系方式

**Comment by areyouok** [comment]
没有群，联系方式源代码里面有，就在issue里面也可以讨论
