### ISSUE TITLE
缓存失效问题

### ISSUE THREAD

**Issue by jiangmin168168** [alibaba/jetcache#297]
比如针对一个表，有两查询方法，一个更新方法：

Product getById(id); 这个获取单条数据有缓存，缓存条件就是主键
List<Product> search(xxx);这个列表加缓存，缓存条件不定
void updateById(id);更新时，失效缓存

问题，在处理updateById时，需要失效两个缓存，一个是单条记录的缓存，目前没有问题，如何去失效列表的缓存呢，需要实时失效，不能依赖过期时间的话，有什么方案吗？

**Comment by areyouok** [comment]
这个只能业务自己解决了

**Comment by areyouok** [comment]
用CreateCache注解，使用Cache实例自己搞。

具体怎么处理是你的业务逻辑了。

**Comment by jiangmin168168** [comment]
不是，在失效search方法的缓存时，需要知道有哪些已经查询过的条件，这个需要使用方全记下来才行，看看有没有简单一些的方法，那个removeAll需要传递key，这块是关键点
