### ISSUE TITLE
缓存设置了CacheType.BOTH的形式，在分布式环境下的情况

### ISSUE THREAD

**Issue by leoxu1719** [alibaba/jetcache#298]
请问一下，如果缓存设置了CacheType.BOTH的形式，在分布式环境下，也是会先读节点上的缓存，再取远程缓存吗？ 如果是先读本地缓存，会有数据不一致的问题？

**Comment by areyouok** [comment]
会有，你可以把本地的缓存超时时间设置的短一点。
