### ISSUE TITLE
@CacheInvalidate 能否支持方法调用前触发和方法调用后触发

### ISSUE THREAD

**Issue by naturalyui** [alibaba/jetcache#301]
您好，我在使用```@CacheInvalidate (condition="")```时想通过入参来选择是否删除缓存,但是发现缓存是在整个方法调用结束后才被删除，就会造成此方法中会读取到之前的缓存。

如果是我使用方式上的问题，希望大神可以指点一下。
如果本身就是这样希望大神在未来版本对@CacheInvalidate支持方法执行前触发和方法执行后触发的配置:)

这是我的引用:
```maven
<dependency>
   <groupId>com.alicp.jetcache</groupId>
    <artifactId>jetcache-starter-redis-lettuce</artifactId>
    <version>2.5.11</version>
</dependency>
```

**Comment by areyouok** [comment]
标准的缓存操作模式就是先操作数据库，再失效缓存，这个不会改的，也不会增加选项。

如果你有这方面的需求，可以考虑把方法拆分的细粒度一点，或者使用CreateCache注解拿到Cache实例自己搞。

**Comment by naturalyui** [comment]
好的谢谢，我使用CreateCache来完成我的需求了
