### ISSUE TITLE
不使用spring，如何在java 服务中使用jetcache

### ISSUE THREAD

**Issue by SparkandScala** [alibaba/jetcache#302]
在没有使用spring 框架中的java 服务中，是否可以使用jetcache，已经配置了JetCacheConfig，但是好像并没有生效。

**Comment by SparkandScala** [comment]
使用注解可以吗？

**Comment by areyouok** [comment]
jetcache的注解是基于spring aop的，要是连spring都没有用，就不能用jetcache注解了。只能用jetcache api。
