### ISSUE TITLE
想要针对缓存失效、缓存更新的事件做一些额外的定制应当如何扩展？

### ISSUE THREAD

**Issue by fxfh0504** [alibaba/jetcache#303]
RT

**Comment by areyouok** [comment]
参考CacheContext类的buildCache方法，覆盖这个方法（或buildLocal、buildRemote），在这里可以把CacheMonitor注入进去。

**Comment by areyouok** [comment]
2.6.0.M3以后这个定制有简化，在spring context中提供一个自己的CacheMonitorManager（可继承DefaultCacheMonitorManager，复用一些方法）或CacheMessagePublisher都可以。

**Comment by Luomeng1004** [comment]
@areyouok 监听到消息的PUT和REMOVE，如何删除本地缓存中对应key的数据呢？我看删除的话，又会触发事件，导致循环处理。

**Comment by areyouok** [comment]
> @areyouok 监听到消息的PUT和REMOVE，如何删除本地缓存中对应key的数据呢？我看删除的话，又会触发事件，导致循环处理。

现在没有提供默认实现，如果自己处理的话这个还有点麻烦，我想想怎么搞吧。

**Comment by gang0713** [comment]
这个问题在2.6.0里有解决吗？
