### ISSUE TITLE
通过缓存方法获取结果后，对结果进行修改，所有操作直接会影响到原来的缓存

### ISSUE THREAD

**Issue by zyk492322922** [alibaba/jetcache#304]
比如：一个缓存方法缓存了一个List，其中元素都是对象，通过缓存方法拿到一个包含若干对象的List集合后，进行遍历业务处理，接下来所有修改操作（如修改其中某些对象的属性）都会直接影响缓存中的结果，后续再次调用缓存方法返回的结果和第一次不一致。

**Comment by areyouok** [comment]
你用local缓存是会这样，因为jetcache不会把缓存里面的数据clone一份给你。

clone既不高效，另外也不是每个类都能clone。
