### ISSUE TITLE
您好，能否帮忙分析下，我们现在的用的jetcache统计是否准确？

### ISSUE THREAD

**Issue by zuowenmou** [alibaba/jetcache#306]
`		jetcache stat from 2019-05-30 07:00:00,002 to 2019-05-30 07:30:00,002 cache                                                                    qps    rate            get            hit           fail         expire avgLoadTime maxLoadTime -----------------------------------------------------------------+----------+-------+--------------+--------------+--------------+--------------+-----------+----------- ApplyTrumpSettingsMapper.querySettingInfo.                              1.07  91.95%          1,926          1,771              0              0         0.5           1 CourierBoxManager.getCourierBoxInfos.                                   0.00   0.00%              0              0              0              0         0.0           0 CourierClockRecordsManager.queryOneRecordInfo.                          0.57   6.00%          1,033             62              0              0         0.4           2 CourierCriminalCheckRecordsManager.queryOneEntityById.                  0.00   0.00%              0              0              0              0         0.0           0 CourierFaceSupplierSettingsSingle                                      14.73  99.75%         26,509         26,442              0              0         0.0           0 CourierTransportCheckRecordDetailSingle                                 0.00   0.00%              0              0              0              0         0.0           0 CourierTransportCheckRecordsSingle                                      0.00   0.00%              0              0              0              0         0.0           0 ...nAddressCmManager.queryTrainAddressCityManagerByCityManagerId.       0.15  59.63%            270            161              0              0         0.7           3 TrainAddressRepositoryManager.queryTrainAddressById.                    0.62  96.62%          1,124          1,086              0              0         0.6           1 cityAndBusTypeCommonSwitchSettingsCache                                17.96  99.94%         32,328         32,307              0              0         0.0           0 cityAndBusTypeCommonSwitchSettingsCache_local                          17.96  76.18%         32,328         24,629              0            174         0.0           0 cityAndBusTypeCommonSwitchSettingsCache_remote                          4.28  99.73%          7,699          7,678              0              0         0.0           0 courierApplySendOrderRecordsCache                                       0.00   0.00%              0              0              0              0         0.0           0 courierApplySendOrderRecordsListCache                                   3.32  17.48%          5,973          1,044              0              0         0.0           0 courierApplySendOrderSettingsCacheByCityId                              3.33   6.38%          6,000            383              0              0         0.0           0 courierApplySendOrderSettingsCacheBySettingId                           0.68  96.40%          1,221          1,177              0              0         0.0           0 courierApplySendOrderSettingsListCache                                  3.12 100.00%          5,617          5,617              0              0         0.0           0 queryReturnOrderAddressById                                             0.00   0.00%              0              0              0              0         0.0           0 queryReturnOrderAddressByUserId                                         3.26   0.00%          5,873              0              0              0         0.0           0 -----------------------------------------------------------------+----------+-------+--------------+--------------+--------------+--------------+-----------+-----------  `

**Comment by zuowenmou** [comment]
有几个问题：

> 1.我们按半小时的频率进行输出日志，QPS是不是半小时的平均值？

> 2.这些打印出的日志，该如何解读？每一列前后有什么关系或者影响么？

**Comment by areyouok** [comment]
1，是的
2，每一行是一个cache实例的统计数据，列头的名称应该已经说明了含义了，请问是哪个列不明白呢？

**Comment by zuowenmou** [comment]
> 1，是的
感谢解答

> 1. rate，这个命中率的计算方式是怎样的？是否如下逻辑
        若一个查询接口的请求量为：100次，查询缓存80次，查询数据库20次，这个命中率是：80%

> 2.这些指标数据存储到哪里去了？我们是否可以做个扩展，进行数据的二次处理？

**Comment by zuowenmou** [comment]
下面是个人的理解：

>  qps：在规定时间内所处理流量多少的衡量标准

> rate：命中率

> get:？

> hit：？

> fail：错误数量？还是错误率？

> expire：按设定的输出日志频率时间段内的，失效key的个数

> avgLoadTime：按设定的输出日志频率时间段内的，平均加载时间（单位：毫秒）

> maxLoadTime：最大加载时间

**Comment by areyouok** [comment]
所有的数据都是统计周期内，get就是get的次数，hit是缓存命中的次数，fail是缓存访问失败的次数，expire是缓存访问过期的次数。

**Comment by areyouok** [comment]
这些数据指标没有存储，打到日志文件里面然后就丢弃了，可以扩展。

你可以提供一个自己的ConfigProvider(这是个ConditionalOnMissingBean，定义在JetCacheAutoConfiguration类里面，你要是自己提供了，就会覆盖默认的)。你的SpringConfigProvider继承SpringConfigProvider，覆盖newContext方法，返回一个你自己的SpringCacheContext，SpringCacheContext上面可以覆盖的方法很多，比如buildCache，你可以在这里安装你的监控器。

**Comment by zuowenmou** [comment]
> 缓存访问过期的次数。
非常感谢。
还有最后一问：关于命中率的计算方式是怎样的？
命中次数除以总次数么？
