### ISSUE TITLE
我重写了FastJsonValueEncoder和FastJsonValueDecoder之后，缓存似乎是失效的

### ISSUE THREAD

**Issue by fugy15810536407** [alibaba/jetcache#308]
我想使用Fastjson来序列化，把你给的FastJsonValueEncoder和FastJsonValueDecoder加上之后，在在Redis上的缓存在有效期内时，我重启项目之后，也就是本地缓存清了之后，调用查询方法，居然真实查询了，没用到Redis上的缓存

**Comment by belier-cn** [comment]
反序列化失败后就会调用目标方法，你可以打下断点看看反序列化的情况

**Comment by fugy15810536407** [comment]
不是反序列化的问题，是根本没有用到Redis的缓存数据：我设置的Redis是2分钟，Local是1分钟，重启项目或本地时间过期后，就会重新查询；在本地有效期内，就会使用缓存数据。估计是fastjson方式的两级缓存实现有问题，我还没找出来在哪里。

**Comment by areyouok** [comment]
如果别的序列化方式是ok的，你可以先看看Encoder/Decoder代码里面有无出错。

**Comment by areyouok** [comment]
没有进一步的信息，我先关闭了。如果能提供更多信息并且需要继续排查可以reopen

**Comment by xy8864** [comment]
deserialize的时候需要用CacheValueHolder包装一下
