### ISSUE TITLE
没有考虑异步通知刷新缓存

### ISSUE THREAD

**Issue by hadoop835** [alibaba/jetcache#31]

**Comment by areyouok** [comment]
没有看懂，什么意思？你是说多级缓存刷新了以后，要发个通知吗？现在的Cache接口没有通知的能力。

**Comment by hadoop835** [comment]
我想说的数据发生变化。缓存能感知到数据变化吗？

**Comment by areyouok** [comment]
现在的Cache接口，是没有变更通知功能的。

如果要做的话，内存中实现的缓存（caffeine/linkedhashmap）没有问题，redis也没有问题，但是tair没有这方面的api，所以实现不出来。
