### ISSUE TITLE
建议EnableMethodCache增加basePackageClasses

### ISSUE THREAD

**Issue by simonuser** [alibaba/jetcache#310]
目前只能通过basePackages指定包名限定，而不能通过类名或接口名称来限定，不太方便

**Comment by areyouok** [comment]
虽然叫basePackages，但是指定类名也可以工作的。

参考CachePointcut类。

**Comment by simonuser** [comment]
> 
> 
> 虽然叫basePackages，但是指定类名也可以工作的。
> 
> 参考CachePointcut类。

这个好像只能指定具体某个类，不能指定一个公用接口，比如BaseService，这样所有实现该接口的类都支持缓存注解。

**Comment by areyouok** [comment]
不想缓存的方法，不要加注解行么？

这需求太特殊了。

**Comment by simonuser** [comment]
> 
> 
> 不想缓存的方法，不要加注解行么？
> 
> 这需求太特殊了。

可能我没描述清楚啊，有这样一种

package example.service1;
public class MyService1 implements BaseService {
@Cached(name = "myData1", expire = 5)
    public MyData1 getMyData1() throws ServiceException {
    ..............
    }
}

package example.service2;
public class MyService2 implements BaseService {
@Cached(name = "myData2", expire = 5)
    public MyData2 getMyData2() throws ServiceException {
    ..............
    }
}


如果采用basePackages的方式，需要写成：
@EnableMethodCache(basePackages = {"example.service1","example.service2"})

而不能只用
@EnableMethodCache(assignableTypes = {"example.BaseService"})

**Comment by areyouok** [comment]
注解可以加在接口上，也可以加在类上，我认为可以满足你的需求。

**Comment by simonuser** [comment]
> 
> 
> 注解可以加在接口上，也可以加在类上，我认为可以满足你的需求。

我试了一下，应该不可以啊

**Comment by areyouok** [comment]
> > 注解可以加在接口上，也可以加在类上，我认为可以满足你的需求。
> 
> 我试了一下，应该不可以啊

你的basePackages得包含接口所在的包

**Comment by areyouok** [comment]
没有进一步的反馈，这个问题我先关闭了
