### ISSUE TITLE
jetcache-starter-redis

### ISSUE THREAD

**Issue by zmlgit** [alibaba/jetcache#311]
1, 默认加载remote配置，这点能否设成可选的，本地测试的时候似乎不需要这个远程配置
2,能否改成Spring的ConfiguationProperties的形式，如果不跟代码，很难确定配置怎么写，ConfiguationProperties带有IDEA有自动提示功能。版本2.5.12

**Comment by areyouok** [comment]
第一个问题，难道你的cache类型都是local吗?我自己的单元测试里面有个MockRemoteCache，如果需要可以考虑移动到jetcache-core里面。

第二个问题，没有一个简单的办法好改哦。

**Comment by zmlgit** [comment]
其实我想要的是一个jetcache-starter，可以选择是否开启一二级缓存。找来找去也就这是个starter

**Comment by areyouok** [comment]
有个enableMethodCache总开关，可以把1、2级方法缓存都关掉

**Comment by zmlgit** [comment]
这个关掉之后，如果不配置二级缓存，会报错吧

**Comment by areyouok** [comment]
如果你只用方法缓存是不会报错的，如果用到CreateCache注解还是会报错
