### ISSUE TITLE
2.5.12使用时缺少配置项 asyncResultTimeoutInMillis

### ISSUE THREAD

**Issue by nightwolf11** [alibaba/jetcache#312]
大佬，是否能更新一下文档说明啊～配置看不懂了。。。

**Comment by areyouok** [comment]
出错了吗？有默认值啊，不该出错的。

**Comment by nightwolf11** [comment]
已解决：
1、在2.5.12的 jetcache-redis-lettuce-2.5.12.pom pom文件将lettuce-core 5.0.8.RELEASE改成5.1.6版本；   
2、项目pom单独引入下方依赖，解决classnotfound问题
<dependency>
            <groupId>io.projectreactor</groupId>
            <artifactId>reactor-core</artifactId>
            <version>3.2.8.RELEASE</version>
        </dependency>
