### ISSUE TITLE
是否有类似CacheManager来管理cache

### ISSUE THREAD

**Issue by tengwei-lewis** [alibaba/jetcache#313]
比如：我在spring中用可以注入CacheManager，自由操作某个cache

**Comment by nightwolf11** [comment]
2.5.12 2.6.0都有啊

**Comment by areyouok** [comment]
CacheManager.defaultManager

**Comment by areyouok** [comment]
原先的CacheManager，需要先访问一下Cached的方法，才能拿到Cache，现在在2.5.13里面改进了。
