### ISSUE TITLE
一个操作会让2个缓存失效，这个支持吗？

### ISSUE THREAD

**Issue by CodingOX** [alibaba/jetcache#314]
我有一个方法，执行后，需要让2个缓存失效。
我尝试着添加`@CacheInvalidate`2次，无法编译。
这个。。。请教下作者大大，有没有什么比较优雅的处理方式！？

**Comment by areyouok** [comment]
这个暂时还没支持呢。

目前得拿到Cache实例来操作，可以通过CreateCache注解或者CacheManager拿到Cached注解所使用的Cache实例。

**Comment by liuxianpeng0816** [comment]
> 这个暂时还没支持呢。
> 
> 目前得拿到Cache实例来操作，可以通过CreateCache注解或者CacheManager拿到Cached注解所使用的Cache实例。

您好 怎么通过CreateCache注解或者CacheManager拿到Cached注解所使用的Cache实例

**Comment by areyouok** [comment]
CacheManager.defaultManager.getCache(area, cacheName)

需要用新版

**Comment by stanleyls** [comment]
> 这个暂时还没支持呢。
> 
> 目前得拿到Cache实例来操作，可以通过CreateCache注解或者CacheManager拿到Cached注解所使用的Cache实例。

单元测试中CreateCache 设置了相同的name，但是并没有获取到Cached实例，还需要设置什么么？

**Comment by CodingOX** [comment]
> > 这个暂时还没支持呢。
> > 目前得拿到Cache实例来操作，可以通过CreateCache注解或者CacheManager拿到Cached注解所使用的Cache实例。
> 
> 单元测试中CreateCache 设置了相同的name，但是并没有获取到Cached实例，还需要设置什么么？
第一个参数是area 默认的是default，第二才是name，获取cache后通过key进行参数获取，你可以尝试下！

```
Cache cache = CacheManager.defaultManager().getCache("default", RedisKey.USER_FOCUS_COUNT);
```

**Comment by areyouok** [comment]
如果你第一个参数传default的话，调用单参数的那个方法就好了
