### ISSUE TITLE
2.5.12 lettuce客户端，springboot 1.5.21 classnotfind：reactor/core/scheduler/Schedulers  reactor-core-2.0.8.RELEASE.jar 缺类：

### ISSUE THREAD

**Issue by nightwolf11** [alibaba/jetcache#315]

**Comment by nightwolf11** [comment]
已解决：
1、在2.5.12的 jetcache-redis-lettuce-2.5.12.pom pom文件将lettuce-core 5.0.8.RELEASE改成5.1.6版本；   
2、项目pom单独引入下方依赖，解决classnotfound问题
<dependency>
            <groupId>io.projectreactor</groupId>
            <artifactId>reactor-core</artifactId>
            <version>3.2.8.RELEASE</version>
        </dependency>

**Comment by majiajue** [comment]
tks
