### ISSUE TITLE
大佬好，请问：Jetcache如何指定远程redis的数据库编号？

### ISSUE THREAD

**Issue by wangdy0909** [alibaba/jetcache#318]
有没有配置项呢，文档里没有找到相关的设置。

**Comment by areyouok** [comment]
如果你用jedis，可以直接设置database属性。如果用lettuce，uri里面可以指定编号，参考lettuce的文档https://github.com/lettuce-io/lettuce-core/wiki/Basic-usage

**Comment by areyouok** [comment]
功能肯定是有的。没有进一步反馈我先关闭了。
