### ISSUE TITLE
[Question]关于警告 PART_SUCCESS 的含义和可能会导致的问题

### ISSUE THREAD

**Issue by CodingOX** [alibaba/jetcache#319]
```
... c.a.j.s.DefaultCacheMonitor Line:139 - jetcache REMOVE return unexpected code: PART_SUCCESS
```
1. 请问这个警告的含义是什么？
2. 可能会导致什么问题？

**Comment by areyouok** [comment]
当时我断言REMOVE的时候是不可能部分成功的，只有批量操作才会部分成功，所以DefaultCacheMonitor 就这样写了。

刚才看了一下，这个断言是不对的，多级缓存的REMOVE操作会发生部分的情况，一般来说肯定是本地操作成功，远程操作失败。

**Comment by areyouok** [comment]
出现这个错误就是有REMOVE操作失败了，远程操作偶尔有失败是正常的，你可以看下整体失败比例，如果是个别失败就不用管。

**Comment by areyouok** [comment]
没有进一步反馈，我先关闭了
