### ISSUE TITLE
黄哥，Cache API能否支持computeIfPresent(K key,  Function<K,V> func)呢

### ISSUE THREAD

**Issue by leapcat** [alibaba/jetcache#32]
黄哥，我在使用Cache<K,V>时，有一个更新已存在Key值的需求场景，如下图。不知道可否有相应接口支持原子性的操作：

![image](https://user-images.githubusercontent.com/15992666/37705333-a3e21f9e-2d36-11e8-8a6d-2db2e8294830.png)

**Comment by leapcat** [comment]
我知道了，我应该使用全局锁来做更新，之前用Synchronize也不对。我现在用了第二种方式。
另外黄哥，我还有个问题：如果

**Comment by areyouok** [comment]
cacheType = CacheType.LOCAL时是本地锁。BOTH/REMOTE是分布式锁。

不过我还是要提醒你，如果你的业务对一致性准确性要求非常高，就不适合在redis里面做，必须在数据库中做。

**Comment by leapcat** [comment]
明白！
