### ISSUE TITLE
List<User> findList(List<Long> userIds) 用jetcache缓存有什么好的建议么

### ISSUE THREAD

**Issue by stanleyls** [alibaba/jetcache#323]
List<User> findList(List<Long> userIds) 用jetcache缓存
1、有什么好的建议么
2、如何更新List<User>

**Comment by Jump-Boy** [comment]
同问，定义了单个Bean的缓存，现在需要缓存多个Bean，还想用单个Bean的缓存，进行ALL操作，如GET_ALL，REMOVE_ALL，这种方法我看形参是Set，请问Spel表达式支持吗，如想直接批量操作 开头为“id_”的key，如“id_1”，“id_2”的缓存都能被操作，请问怎么写，谢谢大佬

**Comment by areyouok** [comment]
我猜你的意思是想按list里面每个元素单独缓存，这种情况没不支持，也没法实现，自己处理吧。

你的方法里面做个循环，调用一个加了缓存注解的循环，不就实现了么？

**Comment by siqiniao** [comment]
> 我猜你的意思是想按list里面每个元素单独缓存，这种情况没不支持，也没法实现，自己处理吧。
> 
> 你的方法里面做个循环，调用一个加了缓存注解的方法，不就实现了么？

但是这种for循序的方式，跟批量的比起来，效率会低很多
