### ISSUE TITLE
使用lettuce连接，导致连接数增加

### ISSUE THREAD

**Issue by fangjiaxiaobai** [alibaba/jetcache#324]
`@CreateCache(cacheType = CacheType.REMOTE, expire = 120, name = "follow::Lock::")
    private Cache followLock;`

`RedisClient redisClient = (RedisClient) followLock.unwrap(RedisClient.class);
 RedisCommands<String, String> sync = redisClient.connect().sync();
while (!sync.setnx(lockKey, LOCK_VALUE)) {
                log.warn("something....");
                try {
                    Thread.sleep(1000);
                } catch (InterruptedException e) {
                    e.printStackTrace();
                }
}`

**Comment by areyouok** [comment]
你的代码里面连接没释放
