### ISSUE TITLE
支持读写分离吗

### ISSUE THREAD

**Issue by xingchenliang** [alibaba/jetcache#326]
支持配置主从redis 进行读写分离吗。

**Comment by areyouok** [comment]
lettuce客户端一直支持，jedis客户端从2.5.12版本开始支持。

release notes里面有写：
https://github.com/alibaba/jetcache/wiki/Changelog

**Comment by areyouok** [comment]
配置例子可参考

https://github.com/alibaba/jetcache/blob/master/jetcache-test/src/test/resources/config/application-redis.yml
