### ISSUE TITLE
一个对象，使用不同的key缓存，cacheName 不一致，怎么做到同时更新

### ISSUE THREAD

**Issue by wuyongCloud** [alibaba/jetcache#327]
目前在使用spring-redis的cache. 一个user对象，更新或者插入的时候，两个key一起缓存或者更新，
像下面这个例子，CacheInvalidate 也可做到类似的效果，但不是解决这个问题的最佳选择，看起来cachename 无法指定多个，假如只用一个cachename,key 为id 或者mobile 有可能会重复。
   @Cacheable(value = "userCache:mobile",key ="#p0")
    public UacUser findByMobile(String mobile){
        return null;
    }

    @Cacheable(value = "userCache:id",key ="#p0")
    public UacUser findByMobile(Long id){
        return null;
    }

    @Caching(evict = {
        @CacheEvict(value = "userCache:id",key="#user.id"),
        @CacheEvict(value = "userCache:mobile",key="#user.mobile")
	})
    public void updateUser(UacUser user){

    }

    @Caching(put = {
            @CachePut(value = "userCache:id", key = "#result.id"),
            @CachePut(value = "userCache:mobile", key = "#result.mobile")
    })
    public UacUser save(UacUser user){
        return null;
    }

**Comment by areyouok** [comment]
这个暂时没有支持

**Comment by liudajiang** [comment]
我认为设计缓存时应该参考数据库索引的理念，所有数据只能通过主键定位，索引只能查到数据的主键，再又主键定位到数据。
缓存设计时定位到entity的缓存只能有一个(findById),其他缓存只能缓存id，而非具体数据
