### ISSUE TITLE
jetcache使用redis时不用设置超时时间吗

### ISSUE THREAD

**Issue by 979752857** [alibaba/jetcache#329]
大牛你好，jetcache使用redis时不用设置超时时间吗，我看客户端默认的超时时间好像时60s，会不会有点长了，如果需要调整的话怎么处理

**Comment by areyouok** [comment]
没有60秒一说，你在哪看到的。
jedis默认超时时间是2秒，lettuce把uri交给用户设置了，默认异步超时是1秒。
