### ISSUE TITLE
value identity number配置

### ISSUE THREAD

**Issue by areyouok** [alibaba/jetcache#33]
现在value做序列化的时候，在前面先写了4个字节作为标识符，昨天的一个提交使得decoder能够自动按标识符解码。

不过，如果需要使用jetcache和其他的程序同时读写一个key，就不应该写入identity number。这应该做成一个配置。

**Comment by leapcat** [comment]
黄哥，最新提交的版本，mvnrepo.alibaba-inc.com/nexus 会及时收进去么？
