### ISSUE TITLE
refresh刷新机制疑问

### ISSUE THREAD

**Issue by liudajiang** [alibaba/jetcache#330]
大神你好，粗浅的看了一下refresh代码，发现每台实例都会注册定时任务，
虽然reload会使用全局锁保证唯一执行,但是每台实例的触发时间不会完全吻合，
会出现如下情况
A实例refresh刚完成，B实例又触发到，与预先配置的间隔时间不一致

请问会不会出现这种情况呢

**Comment by areyouok** [comment]
你再仔细看看代码，不会的，每次刷新会存一个最近刷新的时间进去，不到指定时间间隔是不会刷的。
