### ISSUE TITLE
CacheMonitorManager问题

### ISSUE THREAD

**Issue by xiaobing395845388** [alibaba/jetcache#332]
CacheContext init()里 defaultCacheMonitorManager = new DefaultCacheMonitorManager(globalCacheConfig.getStatIntervalMinutes(),
                        TimeUnit.MINUTES, globalCacheConfig.getConfigProvider().statCallback());

这样外部无法自定义cacheMonitorManager  以及statCallback

**Comment by areyouok** [comment]
你提供一个自己的SpringConfigProvider（bean），覆盖statCallback方法，就可以了。

如果是2.6版本，定制会更容易，你可以直接在Spring Context中提供CacheMonitorManager或MetricsCallback bean来覆盖默认的。

**Comment by SparkandScala** [comment]
can you give a example about how to use the 
public DefaultCacheMonitorManager(int resetTime, TimeUnit resetTimeUnit, Consumer<StatInfo> statCallback)  not use spring.
