### ISSUE TITLE
注解@Cached的name参数可以是传递的参数吗

### ISSUE THREAD

**Issue by handy518** [alibaba/jetcache#334]
@Service
public class JetcacheTest {
    @Cached(name = "#checkParams.uid", key = "#checkParams.uid")
    public Integer test(CheckParams checkParams) {
        return 0;
    }
}
第一个问题：如上面的代码的Redis缓存key值是#checkParams.uid123(假如uid=123),怎么样让Redis缓存key值为123123呢？
@Service
public class JetcacheTest {
    @Cached(key = "#checkParams.uid")
    public Integer test(CheckParams checkParams) {
        return 0;
    }
}
第二个问题：name不写的Redis缓存key值是多少呢？(看到官网说的是类名+方法名,但是没有过去到值)

**Comment by areyouok** [comment]
name属性应该是常量，不要写表达式，没有写的按类名方法名自动生产一个。

**Comment by handy518** [comment]
如何按类名方法名自动生产一个，有规律吗？

**Comment by areyouok** [comment]
有规律的，类名加方法名加参数类型
