### ISSUE TITLE
阿里云redis全局缓存时间不生效，本地redis5.0.4不存在这个问题

### ISSUE THREAD

**Issue by offSwitch** [alibaba/jetcache#336]
![image](https://user-images.githubusercontent.com/11695496/62195853-6d8b3880-b3af-11e9-82db-4e8193708145.png)
![image](https://user-images.githubusercontent.com/11695496/62195993-c529a400-b3af-11e9-87b7-1e0e6fa7d30f.png)
![image](https://user-images.githubusercontent.com/11695496/62196189-22bdf080-b3b0-11e9-9aff-5ae9310f6835.png)

相同的key，阿里云redis，时间是3天，本地是15分钟。
配置：
jetcache.areaInCacheName=false
jetcache.remote.default.type=redis
jetcache.remote.default.keyConvertor=fastjson
jetcache.remote.default.valueEncoder=kryo
jetcache.remote.default.valueDecoder=kryo
jetcache.remote.default.poolConfig.minIdle=5
jetcache.remote.default.poolConfig.maxIdle=20
jetcache.remote.default.poolConfig.maxTotal=50
jetcache.remote.default.host=
jetcache.remote.default.port=6379
jetcache.remote.default.password=
jetcache.remote.default.expireAfterWriteInMillis=900000

**Comment by areyouok** [comment]
你给的信息不足，你再看看有没有错误日志吧

**Comment by offSwitch** [comment]
没有错误日志，并没有报错。

**Comment by areyouok** [comment]
你可以在RedisCache里面相关的地方打个断点，如果不方便调试可以自己加一行日志看看

**Comment by offSwitch** [comment]
![image](https://user-images.githubusercontent.com/11695496/63205734-7122fd00-c0db-11e9-93eb-cf843d321ab1.png)
这个地方复用了一个cache，在一次调用里面，如果第一次@Cached指定了expire,那么就会覆盖全局的配置，第二次没有指定expire，使用的就是覆盖之后的expire

**Comment by offSwitch** [comment]
在两个不同的方法上都有@Cached,第一个加载缓存验证数据是否正确，第二个缓存请求的数据。缓存时间不一样

**Comment by offSwitch** [comment]
![image](https://user-images.githubusercontent.com/11695496/63207389-a50c1b80-c0f7-11e9-81df-b02804efc1c4.png)
![image](https://user-images.githubusercontent.com/11695496/63207393-b05f4700-c0f7-11e9-84b7-80f36353a1b4.png)

**Comment by areyouok** [comment]
你不会是两个Cached用同一个name吧？

**Comment by offSwitch** [comment]
对，如果是多个Cached用同一个name，没有设置expire的Cached不能去加载全局的配置？
其次JetCache Cached 能支持阻塞多个请求，只放行一个请求吗？

**Comment by areyouok** [comment]
同一个name就是同一个实例，只能有一种配置。

有个单机的加载保护，加CachePenetrationProtect注解
