### ISSUE TITLE
jetcache配置redis认证

### ISSUE THREAD

**Issue by lichaoliu** [alibaba/jetcache#339]
看官网例子中，都是没有带redis认证的，[例子](https://github.com/alibaba/jetcache/wiki/Config_CN)。
项目启动，报错需要redis认证，试了好几种配置都不行，作者能不能给个例子，知道一下，怎样配置认证，不知道怎样配置，谢谢了。
![image](https://user-images.githubusercontent.com/20872105/62408697-53e03000-b5ff-11e9-95d3-014366c5716a.png)

**Comment by areyouok** [comment]
看源代码：
https://github.com/alibaba/jetcache/blob/master/jetcache-starter/jetcache-autoconfigure/src/main/java/com/alicp/jetcache/autoconfigure/RedisAutoConfiguration.java

**Comment by lichaoliu** [comment]
谢谢作者, 可以用
