### ISSUE TITLE
json value序列化器

### ISSUE THREAD

**Issue by areyouok** [alibaba/jetcache#34]
jetcache老版本中是有三个序列化器的：java、kryo、fastjson。

但是fastjson做序列化兼容性不是特别好，某次升级以后单元测试就无法通过了，最后把它废弃了。
现在默认的序列化器是性能最差，但是兼容性最好，大家也最熟悉的java序列化器。

我一直在想要不要找个json的序列化器回来，毕竟json可读性是最好的。

**Comment by areyouok** [comment]
重新检查了一下fastjson的序列化方案，由于安全原因，1.2.25版本以后需要手工注册才能在反序列化的时候自动识别类型：
```java
ParserConfig.getGlobalInstance().addAccept("com.taobao.pac.client.sdk.dataobject.");
```
当初就是因为这个原因FastjsonValueEncoder/Decoder去掉了。

实测fastjson能处理很多数据类型，但是针对数组经常反序列化出来类型不对（在不提供类型参数的情况下，jetcache做反序列化的时候Decoder并不知道目标类型，故无法提供）。

这样如果提供fastjson encoder/decoder，担心会留坑，用户乍一看好像可以工作，用多了等到特定情况下就出现bug。

还是不支持算了，高级用户覆盖SpringConfigProvider自己玩吧。

**Comment by Viyond** [comment]
fastjson设置setAutoTypeSupport 为true时，可以不注册accept的类型列表；
当然gson和jackson都可以考虑作为json序列化工具呢。

**Comment by areyouok** [comment]
那样会有安全问题吧。我目前是已经放弃了。

感觉json做一个通用的序列化还是会有限制，现在jetcache自定义序列化器很方便，所以用户可以自己搞。

未来为了跨语言，我会再内置一个序列化器，序列化成json格式，但是只支持几种基本类型。

**Comment by zhangdc007** [comment]
> 重新检查了一下fastjson的序列化方案，由于安全原因，1.2.25版本以后需要手工注册才能在反序列化的时候自动识别类型：
> 
> ```java
> ParserConfig.getGlobalInstance().addAccept("com.taobao.pac.client.sdk.dataobject.");
> ```
> 
> 当初就是因为这个原因FastjsonValueEncoder/Decoder去掉了。
> 
> 实测fastjson能处理很多数据类型，但是针对数组经常反序列化出来类型不对（在不提供类型参数的情况下，jetcache做反序列化的时候Decoder并不知道目标类型，故无法提供）。
> 
> 这样如果提供fastjson encoder/decoder，担心会留坑，用户乍一看好像可以工作，用多了等到特定情况下就出现bug。
> 
> 还是不支持算了，高级用户覆盖SpringConfigProvider自己玩吧。

需要在注解 Cache 这些的处理代码里，把返回值类型传进来才可以，不然通用的JSON 序列化器比较麻烦，
