### ISSUE TITLE
某个方法级缓存，能否动态的设置是否走缓存，只对当前线程有效

### ISSUE THREAD

**Issue by wuyongCloud** [alibaba/jetcache#342]

**Comment by areyouok** [comment]
Cached注解上面有个enabled属性，设置为false

**Comment by wuyongCloud** [comment]
可能我表达的有问题，我是说一个方法级别的缓存，绝大多数都是查询缓存，某些场景，不想查询缓存，通过调用这个方法前手动设置个参数，可以让当前线程不查询缓存

**Comment by areyouok** [comment]
现在的代码只能支持相反的情况，默认禁用，按需打开
