### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by areyouok** [alibaba/jetcache#35]
* golang version: implements jetcache core api
* python version:  implements jetcache core api
* (2.X) java version: interoperable with golang and python version
* (3.X) java version: enhance Cache API and implement jsr-107 specification

**Comment by rchlz** [comment]
3.x计划啥时候出？

**Comment by areyouok** [comment]
@rchlz 没有时间表

顺序上说我想先实现一个golang的版本，正好我也学习操练一下go。理想情况是让jetcache成为跨语言，跨底层缓存实现的通用缓存操作接口，并且不同语言能同时操作同一个缓存服务器，就像gRPC能让不同的语言通信一样。现有jetcache的java/kryo encoder编码的数据显然还不能用其它编程语言来解码。

完整的jsr107内容比较多，工作量也很大的。实现思路还是我以前说过的那样，新搞一个AdvancedCache继承Cache接口，然后让Cache接口的Redis实现来实现它，tair下就不能实现这个高级接口了。
