### ISSUE TITLE
使用了@CreateCache,但是没有定义@Cache,使用CacheManager.defaultManager().getCache(cacheName)获取为null

### ISSUE THREAD

**Issue by yunhuizhu** [alibaba/jetcache#356]
1. 使用jetcache-starter-redis-lettuce 2.5.14 
使用了@CreateCache,但是没有定义方法注解@Cache,使用CacheManager.defaultManager().getCache(cacheName)获取为null。
发现需要有@Cache方法注解才能获取到cache。不会自动创建cache，因ConfigMap里面只有使用了@Cache注解之后才有的map键值对。

**Comment by areyouok** [comment]
CreateCache创建的也会注册，不过因为它是懒加载的，所以可能暂时还没注册上。

不过你用CreateCache注解不是已经拿到Cache实例了吗？为什么还要去CacheManager里面拿呢

**Comment by yunhuizhu** [comment]
> CreateCache创建的也会注册，不过因为它是懒加载的，所以可能暂时还没注册上。
> 
> 不过你用CreateCache注解不是已经拿到Cache实例了吗？为什么还要去CacheManager里面拿呢

谢谢，主要是一开始是自定义了清除所有的缓存方法的，根据cache的name获取cache，之后进行缓存手动清除。现在是直接在util工具类中使用spring工具类获取注入的类，之后进行操作。

**Comment by ChengHoHang** [comment]
@CreateCache最好也可以提供个配置，支持启动的时候就把实例放入manager中。目前有个场景要在切面处根据name获取cache实例，如果要用spring去管理又很奇怪
