### ISSUE TITLE
AbstractCache 类中双重锁 有点线程安全问题

### ISSUE THREAD

**Issue by lxk696** [alibaba/jetcache#359]
private ConcurrentHashMap<Object, LoaderLock> loaderMap;

    ConcurrentHashMap<Object, LoaderLock> initOrGetLoaderMap() {
        if (loaderMap == null) {
            synchronized (this) {
                if (loaderMap == null) {
                    loaderMap = new ConcurrentHashMap<>();
                }
            }
        }
        return loaderMap;
    }

双重锁 都要考虑 编译期优化导致出现线程安全的问题， 变量应该使用volatile 吧？

**Comment by lxk696** [comment]
private volatile   ConcurrentHashMap<Object, LoaderLock> loaderMap;

**Comment by lxk696** [comment]
AbstractCache.buildLoaderLockKey( )   是用了 堆外内存 ByteBuffer.wrap( ) 来做，为什么不考虑像redission一样用redis 做分布式锁 来控制

**Comment by areyouok** [comment]
volatile的问题你说的对，我已经修了。

现在的加载保护做的比较保守，是进程级别的单线程加载，没有做成集群级别的单线程加载。如果要做到后者需要使用到有通知能力的分布式锁，要做到非常可靠还是挺复杂的，就暂时没有做。

另外ByteBuffer.wrap并不是使用对外内存的。

**Comment by lxk696** [comment]
好的，谢谢了，感谢解答
