### ISSUE TITLE
@Cached能否预防缓存击穿 和多级缓存设置不同的expire

### ISSUE THREAD

**Issue by darren-fu** [alibaba/jetcache#36]
@areyouok
首先这是个非常好的项目，解决了一些缓存使用过程中的痛点，并且封装的很易用。
提两个需求，看看是否合理
1. @Cached注解目前不能预防缓存击穿，并发访问时，会造成并发加载，能否做到至少在一个JVM中的缓存加载的锁控制
2. 目前多级缓存（本地+redis）在@Cached中设置的expire是相同的，是否可以在@Cached中直接设置不同的expire呢？常规来说本地缓存有效期应该比远程缓存要短很多才合理

**Comment by areyouok** [comment]
感谢关注。

第一个问题，是可以优化的，具体实现的时候可能有些细节问题要处理。在做这个优化之前，对于重量级对象，加上缓存以后可以配合自动刷新来用。自动刷新是全局唯一的，JetCache能自动移除长时间不访问的Key对应的刷新任务。不过，由于自动刷新任务是自该Key首次被访问以后才创建的，所以极端情况下可能需要预热。

第二个问题，也可以考虑。之前版本本地和远程的超时时间是不对齐的，我后来还特地进行了对齐，当时是为了保证经过指定的超时时间后一定失效。不过你说的也有道理。

**Comment by darren-fu** [comment]
期待实现，或者可以告知一下从哪些个地方去入手优化这两个需求，我来实现提PR
刚接触这个项目，对代码不熟悉-_-~

**Comment by darren-fu** [comment]
嗯，那我就偷个懒，等待下一个RELEASE-_-!~

**Comment by areyouok** [comment]
缓存未命中时的单机加载保护已经在master上实现了。

**Comment by darren-fu** [comment]
大赞，勤劳的Author

**Comment by Viyond** [comment]
关注。。

**Comment by areyouok** [comment]
2已经实现了，在master，基本的测试已经通过。

**Comment by darren-fu** [comment]
赞

**Comment by darren-fu** [comment]
期待RELEASE

**Comment by areyouok** [comment]
2.5.0已经发布，如果生产环境从2.3.3以及以下版本升级需要注意兼容性问题。

https://github.com/alibaba/jetcache/wiki/Compatibility_CN
