### ISSUE TITLE
jetcache-starter-redis-lettuce启动报错

### ISSUE THREAD

**Issue by slowvic** [alibaba/jetcache#366]
jetcache2.5.14，springboot2.1.6以上，启动报以下错误
java.lang.IllegalStateException: Failed to introspect Class [com.alicp.jetcache.autoconfigure.RedisAutoConfiguration$RedisAutoInit] from ClassLoader [sun.misc.Launcher$AppClassLoader@18b4aac2]
只好使用jedis作为客户端.

**Comment by areyouok** [comment]
现在jetcache的单元测试是在2.1.4.RELEASE下做的，2.1.6应该也可以用。

你需要提供更多信息。

**Comment by slowvic** [comment]
我的错，文档没看全。
问题已解决。
