### ISSUE TITLE
CacheInvalidate注解删除的方法有返回值result,key对应赋值的类型是map，删除之后再调用获取对应key的时候怎么变成了result的类型。

### ISSUE THREAD

**Issue by yunhuizhu** [alibaba/jetcache#368]
CacheInvalidate注解删除的方法有返回值result,key对应赋值的类型是map。
有一个key为officeMap的map类型的缓存，
机构增删改的请求的地方给加上了CacheInvalidate注解，请求方法都返回的result类型，调用了增删改查之后，再调用cache的时候提示不能把result类型转为map。
疑问：清除缓存会把方法返回值赋值给新的方法？不是应该直接删除操作吗？

**Comment by areyouok** [comment]
没有看懂这个问题，能不能给段代码描述一下？

**Comment by yunhuizhu** [comment]
注解CacheInvalidate方法：
 @ApiOperation("用户批量删除接口")
    @CacheInvalidate(name ="sysCache" ,key ="'OfficeMap'")
    public Result<SysUser> deleteBatch(@RequestParam(name = "ids", required = true) String ids)
获取的方法：
 Map<String, SysOffice> officeMap = (Map<String, SysOffice>) CacheUtils.get(CACHE_OFFICE_MAP);
之后提示result不能转为map,但是我定义的地方是map的。
@areyouok

**Comment by yunhuizhu** [comment]
已经解决，是我自己的问题，自定义了删除操作，但是删除的时候未使用好，导致混乱。关闭该问题。
