### ISSUE TITLE
Kryo 5.x compatible

### ISSUE THREAD

**Issue by linxux** [alibaba/jetcache#375]
https://github.com/alibaba/jetcache/blob/c8eba1a98246ad48e41343dbd50a3d5027a36631/jetcache-core/src/main/java/com/alicp/jetcache/support/KryoValueEncoder.java#L58

Hi guys, thank you for the great work.

`KryoValueEncoder` is broken when I try to upgrade the Kryo version to `5.0.0-RC4` in my application.
So I have rollback to `4.0.2`.
Any plan to handle this issue?

Please refer to Kyro commit - [Revamped pooling.](https://github.com/EsotericSoftware/kryo/commit/a4b10daeafeaa96c79e2a020a33285adf39e2471#diff-75a80aa3165cf6da67bd5f97bbc95eed)
src/com/esotericsoftware/kryo/io/Output.java

**Comment by areyouok** [comment]
Thank you for reporting this problem. Is this commit work for you? 
https://github.com/alibaba/jetcache/commit/8b24dc936fc46773a5cebc8351697968a02d5aae

**Comment by linxux** [comment]
@areyouok Great. Thank you for your quick response.

**Comment by areyouok** [comment]
this issue has fixed in 2.5.15 release
