### ISSUE TITLE
报告jedis依赖bug

### ISSUE THREAD

**Issue by JoshShaw** [alibaba/jetcache#377]
jetcache/jetcache-support/jetcache-redis/pom.xml

jedis 2.9.x版本中close()方法有一个多线程bug，非常严重，高并发下极易发生连接泄露，需要将版本调整为2.10.2才能解决。
见jedis的issue：https://github.com/xetorthio/jedis/issues/1920

**Comment by areyouok** [comment]
2.6系列版本来更新吧，这个自己可以升吧，另外就是要和spring data保持版本一致

**Comment by areyouok** [comment]
2.6更新jedis3.1，2.5.15更新jedis2.10.2，2.5.15已经发布

**Comment by kingwudy** [comment]
2.10.2是怎么避免指令重排序问题的修复的时候有人提出了这个疑问 https://github.com/redis/jedis/commit/02f2cc5cce2f44efeaaafe351a2facf66988ddbf#diff-df2421269af8d142bf842cb0141f3a95R3639

**Comment by kingwudy** [comment]
> jetcache/jetcache-support/jetcache-redis/pom.xml
> 
> jedis 2.9.x版本中close()方法有一个多线程bug，非常严重，高并发下极易发生连接泄露，需要将版本调整为2.10.2才能解决。 见jedis的issue：[redis/jedis#1920](https://github.com/redis/jedis/issues/1920)

@areyouok  请教一下，2.10.2的修复方式，貌似不能避免指令重排序之后仍然导致泄露
PS：当时也有人也提出了这个疑问，貌似没被采纳https://github.com/redis/jedis/commit/02f2cc5cce2f44efeaaafe351a2facf66988ddbf#diff-df2421269af8d142bf842cb0141f3a95R3639
