### ISSUE TITLE
[功能申请 希望增加valueEncoder]集成GenericFastJsonRedisSerializer

### ISSUE THREAD

**Issue by PlexPt** [alibaba/jetcache#379]
参考com.alibaba.fastjson.support.spring.GenericFastJsonRedisSerializer

目前的kryo方式可读性较差

**Comment by areyouok** [comment]
这个fastjson序列化器以前是有的，后来我去掉了，通过定制自己的序列化反序列化器，你可以很容易做出来。

**Comment by areyouok** [comment]
具体请参考wiki里面的FAQ

**Comment by PlexPt** [comment]
tks
