### ISSUE TITLE
请问@CacheInvalidate能删除多个缓存吗，或者清除同一个name下的缓存，类似于Spring cache的@CacheEvict 的allEntries参数？谢谢

### ISSUE THREAD

**Issue by truantmuse** [alibaba/jetcache#38]

**Comment by areyouok** [comment]
现在不能。

redis下如果要实现这个功能，需要用hset的方式存进去，以后即使支持了，也不会默认用hset的方式存数据，所以在声明缓存的时候，可能需要有额外的配置指定要使用redis的hash类接口。

另外传统上tair的mdb引擎并不支持这样的功能。

当前的替代办法是使用Cache接口的unwrap方法得到原始的对象，例如JedisPool，然后自己操作。

**Comment by truantmuse** [comment]
可以使用RedisLettuceCache这个类的do_REMOVE_ALL这样的方法来自己实现删除多个指定key的缓存吗；或者一个update方法后，如何在本项目的基础上最方便实现删除多个受影响的缓存呢，还请指导下，初次实现缓存功能，谢谢啦

**Comment by areyouok** [comment]
RedisLettuceCache是Cache接口的具体实现，do_REMOVE_ALL是内部方法。

使用API的话，直接操作Cache接口就可以了。Cache接口上的removeAll方法可以删除多个key。

Cache API请看：
https://github.com/alibaba/jetcache/wiki/CacheAPI_CN

基于注解创建Cache实例：
https://github.com/alibaba/jetcache/wiki/CreateCache_CN

**Comment by truantmuse** [comment]
@Cached(name = "course:", key = "#id")
    public CourseDomain get(Long id) {
        return coursewareMapper.get(id);
    }



    public void update(Long id,String name) {
        courseMapper.update(id, name);
        set<String> keys =....;
        cache.removeAll(keys);
    }

这里，操作cache接口得拿到一个RedisLettuceCache的实例吧，通过注解添加的缓存，怎么拿到cache的实例呢；正常的逻辑是不是从连接池拿到LettuceClusterClient去操作缓存啊

**Comment by truantmuse** [comment]
嗯嗯明白了，但是在Springboot的一个service中添加
@CreateCache(name="course:")
private Cache cache;

结果是null，会是什么原因呢

**Comment by areyouok** [comment]
EnableCreateCacheAnnotation加了没有
```java
@SpringBootApplication
@EnableMethodCache(basePackages = "com.company.mypackage")
@EnableCreateCacheAnnotation
public class MySpringBootApp {
    public static void main(String[] args) {
        SpringApplication.run(MySpringBootApp.class);
    }
}
```

**Comment by truantmuse** [comment]
name相同的cache都是同一个cache实例吧；我在删除一个缓存的时候，通过这个缓存对应的cache实例通过cache.remove(key)方法删除，但是redis中并没有删除是为什么啊

**Comment by truantmuse** [comment]
cache.remove()方法返回为false

**Comment by truantmuse** [comment]
谢谢大神，已解决！

**Comment by JanYork** [comment]
请问一下，如果我需要去批量删除Key，使用CacheManager+QuickConfig 去创建实例来实现，那岂不是每一个要用到这个缓存的类都得init一下，感觉代码一下子冗余了，有没有更好的方法呀
