### ISSUE TITLE
The dependencies of some of the beans in the application context form a cycle

### ISSUE THREAD

**Issue by zxgangandy** [alibaba/jetcache#384]
The dependencies of some of the beans in the application context form a cycle:

───┐
|  globalCacheConfig defined in class path resource [com/alicp/jetcache/autoconfigure/JetCacheAutoConfiguration.class]
↑     ↓
|  springConfigProvider

**Comment by zxgangandy** [comment]
报bean循环引用的错误

**Comment by zxgangandy** [comment]
spring boot 版本； 2.1.9.RELEASE 
jetcache版本：2.6.0.M3

**Comment by areyouok** [comment]
Unit test under spring 5.1.6.RELEASE and boot 2.1.4.RELEASE passed for 2.6.0.M3

Can you give some code to reproduce this issue?

**Comment by zxgangandy** [comment]
是因为配置没加载的原因，谢谢 @areyouok

**Comment by Skqing** [comment]
我也出现这个问题了，boot 2.6.5

**Comment by areyouok** [comment]
try 2.6.3
