### ISSUE TITLE
中文文档错别字

### ISSUE THREAD

**Issue by iqeq00** [alibaba/jetcache#388]
最近准备用这个组件，来替换自己原来的自定义实现，于是浏览下文档，发现了点小问题。
错别字，不是什么大问题。

在中文文档：[高级Cache API ](https://github.com/alibaba/jetcache/wiki/AdvancedCacheAPI_CN)这一章节内，自动load（read through）区域内。

原文：LoadingCache的get和getAll方法，在缓存未命中的情况下，会调用loader，如果loader抛出**一场**，get和getAll会抛出CacheInvokeException。

这个“一场”，应该是“异常”吧。

**Comment by areyouok** [comment]
谢谢反馈，已经修正
