### ISSUE TITLE
请问一台机器本地缓存失效后通知集群所有机器失效本地缓存是在哪里实现的？要配置什么吗

### ISSUE THREAD

**Issue by BeyongTheMemory** [alibaba/jetcache#39]

**Comment by areyouok** [comment]
没有这样的通知。如果你使用两级缓存，一个应用服务器没法更新其他应用服务器的内存缓存。

只有两个办法，一是基于TTL超时，二是不要使用两级缓存。

**Comment by BeyongTheMemory** [comment]
这个后续有考虑实现吗？比如一台机器进行update操作更新缓存后别的机器都失效本地缓存

**Comment by areyouok** [comment]
暂时没有这个计划。

这个不好实现，如果要做的话要实现通知，然而tair好像没有通知功能。即使只支持redis，做起来也比较复杂，使用起来也会复杂吧。

如果Redis压力不是特别大，cacheType设置成REMOTE就好了。

#36 里面提出应该给本地缓存设置一个更短的超时时间，我觉得这可以作为一个替代方案。后续会实现#36

**Comment by BeyongTheMemory** [comment]
嗯，我们之前有使用zk通知的方案，但是感觉还是太重了还引入了不少问题。支持不同过期时间也蛮好的

**Comment by Viyond** [comment]
关注。。

**Comment by clarkhan** [comment]
我们之前借助消息队列做了简单实现，更新后通过消息通知到集群所有机器。  
同步的策略可以是失效本地缓存（待请求后被动同步）或收到消息后主动同步 redis。

我觉得通知这块的实现方式用消息队列、还是用 redis pub/sub 什么的都可抽象出去。cache 这边基于这种抽象去实现更新、多级缓存同步是不是一种可行的思路。

**Comment by areyouok** [comment]
不同过期时间已经在2.5.0实现。如果生产环境从2.3.3以及以下版本升级需要注意兼容性问题。

https://github.com/alibaba/jetcache/wiki/Compatibility_CN

**Comment by clarkhan** [comment]
@areyouok 你好,基于 redis 的通知还考虑实现么?

**Comment by areyouok** [comment]
@clarkhan 现在能支持给本地缓存设置一个较短的超时时间，暂不考虑通知了。
