### ISSUE TITLE
A项目使用@Cache重建缓存；B项目使用@CacheInvalidate 无法删除

### ISSUE THREAD

**Issue by 569258yin** [alibaba/jetcache#397]
A 项目：
![image](https://user-images.githubusercontent.com/13885222/69595349-3c0f3a80-103a-11ea-8e21-727fa0277718.png)
删除缓存是可以的
B 项目:
![image](https://user-images.githubusercontent.com/13885222/69595384-58ab7280-103a-11ea-853f-8bbcfde81c4f.png)

无法删除缓存；

请问这个是本来就不能做到的，还是我的配置存在问题？按理说应该不会受到项目不同的限制啊

**Comment by 569258yin** [comment]
@areyouok

**Comment by EasonFeng5870** [comment]
读取源码好像是不行的

**Comment by areyouok** [comment]
CacheInvalidate注解依赖Cached的定义，所以你这样是不行的。

注解只是更加简单的一种使用方式。如果有更灵活的要求直接使用Cache接口的实例吧，更灵活更强大，不容易出问题。

**Comment by 569258yin** [comment]
> CacheInvalidate注解依赖Cached的定义，所以你这样是不行的。
> 
> 注解只是更加简单的一种使用方式。如果有更灵活的要求直接使用Cache接口的实例吧，更灵活更强大，不容易出问题。

好的，明白了，我现在做法是手动清除的缓存

**Comment by scwanglijun** [comment]
> > CacheInvalidate注解依赖Cached的定义，所以你这样是不行的。
> > 注解只是更加简单的一种使用方式。如果有更灵活的要求直接使用Cache接口的实例吧，更灵活更强大，不容易出问题。
> 
> 好的，明白了，我现在做法是手动清除的缓存

如何手动清缓存呗 ？

**Comment by 569258yin** [comment]
> > > CacheInvalidate注解依赖Cached的定义，所以你这样是不行的。
> > > 注解只是更加简单的一种使用方式。如果有更灵活的要求直接使用Cache接口的实例吧，更灵活更强大，不容易出问题。
> > 
> > 
> > 好的，明白了，我现在做法是手动清除的缓存
> 
> 如何手动清缓存呗 ？

使用代码手动调用呀

、、、
@CreateCache(name = xxx, cacheType = CacheType.REMOTE)
private Cache<String, String> xxxCache;

xxxCache.remove("123");
、、、

**Comment by Thunders-King** [comment]
哈喽，想讨论一下，为什么CacheInvalidate必须要和Cached绑定呢，因为感觉应该是有一些场景是不需要Cached 注解 get到一些数据的。
或者说，是否这样设计的前提是缓存的获取和删除应该统一管理呢
