### ISSUE TITLE
@CreateCache与CacheManager问题

### ISSUE THREAD

**Issue by hb0730** [alibaba/jetcache#399]
在使用CacheManager时，因为@CreateCache是懒式的方式，CacheManger获取为空，是否可以提供，CacheManager的方式的创建，而非Builder的创建，因为@CreateCache方式的创建时非常好的，或许可以提供与@CreateCache一样的方式显示调用创建

**Comment by areyouok** [comment]
有人反馈过这个问题，现在的麻烦在于如果要创建就需要有相关的配置参数。
Cached和CreateCache这两个注解可以提供这些参数，但如果需要在多个地方使用同一个Cache又面临重复定义。

可能需要一个专门的统一定义Cache的机制。

**Comment by hb0730** [comment]
那是否后期有此计划，可能做成工具类时需要这种方式
