### ISSUE TITLE
 @CacheInvalidate multiple keys

### ISSUE THREAD

**Issue by mortias** [alibaba/jetcache#400]
Hi, 

Let's say in Redis I have these cache keys where the name = "findAllByRating." and the key = "#rating"
  findAllByRating.3 (=> some list of data rated by 3)
  findAllByRating.4 (=> some list of data rated by 4)
  findAllByRating.5 (=> some list of data rated by 5)

How can I invalidate all of them with the name "findAllByRating." regardless of the key?
meaning is there a Key SpeL wildcard I can use? If the key attribute is not there, nothing is removed from the cache.

 @CacheInvalidate(name = "findAllByRating.", key = " ????? ")

tx!

**Comment by areyouok** [comment]
there is no method to remove all k/v in a Cache.

how ever you can change the name of a Cache instance.

**Comment by mortias** [comment]
And i can't rely on the spring cache annotations to do something like this?

@Caching(evict = {
    @CacheEvict("primary"),
    @CacheEvict(value = "secondary", key = "#p0")
})

@CacheEvict(value = { "cache1", "cache2" }, allEntries = true)

**Comment by areyouok** [comment]
jetcache does not using hash commands in redis, so it can not clear a cache.

**Comment by mortias** [comment]
FYI, the clue is to create the cache, keep the keys and then evict them
    @CreateCache(name = "findAllByRating.", cacheType = CacheType.REMOTE)
    private Cache<String, List<DoctorEntity>> ratingCache;
ratingCache.REMOVE_ALL(newHashSet("1","2","3","4","5"));
