### ISSUE TITLE
@CacheInvalidate, @CacheUpdate的name为什么是必填项

### ISSUE THREAD

**Issue by chenxiaolei** [alibaba/jetcache#403]
@Cached的name在未指定的情况下可以由CacheNameGenerator自动生成.
@CacheInvalidate, @CacheUpdate是不是也应该可以才对.

自定义了name的生成方式, 准备抽象一个CRUD缓存service类,发现被这2个注解卡住了

**Comment by areyouok** [comment]
如果CacheInvalidate, CacheUpdate注解不设置name，无法确定它要清除或者更新哪个Cache。

如果你有自己的定制，那么也可以把这两个注解的name修改为可选的。

**Comment by chenxiaolei** [comment]
额, 这里我只是奇怪name为什么没有在这些注解中保持一致性,蛮奇怪的, 你说的换成@Cache也没错
```
如果Cache注解不设置name，无法确定它要创建哪个Cache。
```

**Comment by areyouok** [comment]
因为Cached可以单独工作，所以可以自动生成name。而CacheInvalidate、CacheUpdate必须和Cached配合才能工作，所以这两个注解必须用name属性来指定和它搭档的Cached是哪个。

在一定的限制条件下，可以不用name属性，但是这些限制条件并不通用。如果你自己尝试去定制，就会发现这些限制是什么，如果在你的应用场景下可以接受这些限制，那么你就可以改成不需要name属性。

**Comment by chenxiaolei** [comment]
如果把限制说清楚, 再由用户来决定是否接受该限制就再好不过了
行吧, 我自己先改改看看.

**Comment by chenxiaolei** [comment]
仔细扫了下源代码，算是看明白为什么CacheInvalidate、CacheUpdate不能单独工作了。
1, 我寻思至少CacheInvalidate允许单独工作是不是更好点，因为有时候项目中的Remote缓存并非由Jetcache创建的，是否可以调整为『未定义Cached的独立CacheInvalidate视为对Remote缓存的清除动作』. 
2, CacheInvalidate、CacheUpdate的name必填限制去除,，我改了下，把Cached的name的自动生成, 从CacheContext.createCacheInvokeContext，前置调整到CachePointcut.matchesImpl中去, 跑了一下暂时还没有发现问题
