### ISSUE TITLE
希望可以出个可以json value的beta版本

### ISSUE THREAD

**Issue by Gleans** [alibaba/jetcache#410]
或者出个demo
看了好多Issues之后,勉强改成json,但是还是无法解析到,还是每次都走数据库,只能先用着java的,这样就无法方便在redis看到具体数据
看着是自定义bean继承,然后指向
```java
import com.alicp.jetcache.anno.SerialPolicy;
import org.springframework.stereotype.Component;

import java.util.function.Function;

@Component
public class JetCacheJson implements SerialPolicy {

    @Override
    public Function<Object, byte[]> encoder() {
        return FastjsonValueEncoder.INSTANCE;
    }

    @Override
    public Function<byte[], Object> decoder() {
        return FastjsonValueDecoder.INSTANCE;
    }
}
```
比较菜,还无法知道具体需要配置哪些,希望作者有时间写个demo,支持在redis存json的

**Comment by areyouok** [comment]
要看看源代码，早期的版本和现在会有点区别，你不看代码肯定会糊涂。
你看看源代码SpringConfigProvider/ConfigProvider，如果不知道自己的encoder为什么没生效，你可以看看为什么现有的encoder能生效嘛。ConfigProvider.parseValueEncoder打个断点看看

**Comment by areyouok** [comment]
另外，wiki里面中文版的FAQ是写了怎么做的，虽然给出的不是最新的写法，但是可以工作的

**Comment by Gleans** [comment]
好的,谢谢噢。
