### ISSUE TITLE
2.6.0.M3 的jedis初始化问题

### ISSUE THREAD

**Issue by zhangdc007** [alibaba/jetcache#413]
1:使用 2.6.0.M3，按照https://github.com/alibaba/jetcache/wiki/RedisWithJedis
globalCacheConfig.setConfigProvider(configProvider); 这一句报错，看源码是删除了，希望文档更新
2：jedis 3.1的时候，pool的位置移动了，导致无法注入
在3.1版本的jedis ,pool位置移动到 ，redis.clients.jedis.util.Pool;
但是2.6.0.M3没有跟进修改，导致无法使用高版本jedis

**Comment by areyouok** [comment]
感谢反馈，第一个不兼容的问题我以前没注意到，不过现在既然2.6还没有发布，文档就先不更新了，以免2.5的用户会遇到问题。

第二个问题，jedis有一些不兼容的修改，所以可能无法保证适应jedis的每一个版本，我现在的策略是和jetcache默认配套的spring版本（你可以到根下的pom查看当前配套的spring版本）保持一致，现在master上最新的代码可以支持3.1，你可以自己打包试试看。

打包方式参考这篇wiki的最下面：
https://github.com/alibaba/jetcache/wiki/DevNote_CN

**Comment by zhangdc007** [comment]
1：我用2.6.0.M3版本，删除了globalCacheConfig.setConfigProvider(configProvider);后，执行报错，先改成2.5.11 ，按照文档初始化正常
2：jedis我在pom里指定了 2.9.3版本，可以正确使用

目前看没啥问题，后续要升级，我再自己打包，谢谢
