### ISSUE TITLE
cacheType为BOTH时，做为二级缓存，数据缓存本地和远程有优先级吗？

### ISSUE THREAD

**Issue by 3tem** [alibaba/jetcache#42]
编写demo中，数据优先存在local中，并没有存在redis中

**Comment by areyouok** [comment]
写的时候是都写，读的时候优先从本地读。

你检查一下代码有没有问题。

**Comment by 3tem** [comment]
谢答，可以了，是优先从本地读，这样的话，过期时间是一样的，有没有计划将本地和远程的过期时间分开设置？

**Comment by areyouok** [comment]
see #36

**Comment by areyouok** [comment]
编号36的issue已经实现
