### ISSUE TITLE
解析容器名+端口形式配置错误

### ISSUE THREAD

**Issue by truantmuse** [alibaba/jetcache#43]
jetcache:
  areaInCacheName: false
  remote:
    default:
      type: redis.lettuce
      keyConvertor: fastjson
      uri:
        - redis://grokzen__redis-cluster:7000
        - redis://grokzen__redis-cluster:7001
        - redis://grokzen__redis-cluster:7002

我的配置如图，在CI中redis集群地址为这种形式，但是在解析过程中出错，报错如下：

`Suppressed: io.lettuce.core.RedisConnectionException: Unable to connect to grokzen__redis-cluster:7002:6379`

应该是RedisLettuceAutoConfiguration中的RedisURI.create(URI.create(k.toString()))这个地方，URI解析出错，能有什么解决办法吗，谢谢

**Comment by areyouok** [comment]
能把配置贴好吗？

**Comment by truantmuse** [comment]
jetcache:
  areaInCacheName: false
  remote:
    default:
      type: redis.lettuce
      keyConvertor: fastjson
      uri:
        - redis://grokzen__redis-cluster:7000
        - redis://grokzen__redis-cluster:7001
        - redis://grokzen__redis-cluster:7002

**Comment by truantmuse** [comment]
URI.create(k.toString())这个无法方法解析grokzen__redis-cluster:7000这种形式的地址

**Comment by areyouok** [comment]
为什么会不能解析？

**Comment by areyouok** [comment]
我试了一下好像是不能有下划线，你们的名字改一下？

**Comment by truantmuse** [comment]
好的了解

**Comment by areyouok** [comment]
那用jedis吧，或者本地host做个别名不知道行不行

**Comment by truantmuse** [comment]
得用集群，只能lettuce，我看怎么解决吧~

**Comment by areyouok** [comment]
```java
        String s = "redis://grokzen--redis-cluster:7000";
        URI uri = URI.create(s);
        System.out.println(uri);
        System.out.println(uri.getScheme());
        System.out.println(uri.getHost());
        System.out.println(uri.getPort());
```
主机名包含下划线java.net.URI就会解析不出来。

**Comment by truantmuse** [comment]
有什么办法删除同一个cache实例下的所有缓存啊，能解释下cache实例与一个redis中的一个缓存对象的关系吗；name相同、不管key，就是同属一个实例吧~

**Comment by areyouok** [comment]
同一个area下，相同的name会指向同一个JetCache的```Cache```实例。PUT的时候jetcache会自动加一个前缀，如果设置了areaInCacheName: false，那么name做作为key前缀。

没有办法删除一个Cache下所有的key。没有支持redis的hset类方法。

如果想要以前的key全部失效，可以换个name。
