### ISSUE TITLE
JetCache版本升级Lettuce Client默认配置问题

### ISSUE THREAD

**Issue by lhqwer129** [alibaba/jetcache#430]
![image](https://user-images.githubusercontent.com/35949905/71650732-fc332580-2d52-11ea-94d9-3ca077545089.png)
最近将JetCache jar包版本升级后，发现最新版本将Lettuce ClientOptions的disconnectedBehavior参数值默认设为“REJECT_COMMANDS"，而老版本是"DEFAULT"，导致服务升级最新版本后偶现“RedisException: Currently not connected. Commands are rejected”的异常，这个是由于与redis连接断开导致的，而老版本由于disconnectedBehavior参数为"DEFAULT"，rejectCommandsWhileDisconnected参数的值为false，即使服务与redis断开连接，也不会抛出该异常，想问一下是出于什么原因JetCache新版本将disconnectedBehavior的值默认设为"REJECT_COMMANDS"。
![image](https://user-images.githubusercontent.com/35949905/71650866-11f51a80-2d54-11ea-9a59-a0fa43c0d989.png)

**Comment by areyouok** [comment]
这是为了在redis不可用的时候快速失败，参考这里

https://github.com/alibaba/jetcache/issues/174

**Comment by lhqwer129** [comment]
Lettuce通过netty连接redis时，如果是redis连接空闲时间过长导致连接断开，还未自动重连时，调用PUT方法，这个时候快速失败造成本次操作失败，是否会造成数据库与redis数据不一致的问题？

**Comment by areyouok** [comment]
redis没有可能和数据库保持强一致。如果不快速失败，高并发下会挂掉的。

你可以看看lettuce的超时配置，设置长一点？

**Comment by lhqwer129** [comment]
好的，多谢解答～

**Comment by LikoLi** [comment]
最近我们生产环境运维将redis的timeout从0变更为了300，导致经常报[Currently not connected. Commands are rejected]这个错，我有什么办法能将disconnectedBehavior 改回DEFAULT吗？
