### ISSUE TITLE
cacheNullValue 参数对于 MultiLevelCache 无效

### ISSUE THREAD

**Issue by raychow** [alibaba/jetcache#442]
在方法上设置注解

`@Cached(name = "cache", cacheType = CacheType.BOTH, cacheNullValue = true)`

当 cacheType = CacheType.BOTH 时, cacheNullValue = true 并没有被设置到 MultiLevelCache 上去

**Comment by areyouok** [comment]
CacheContext的132行设置了

**Comment by raychow** [comment]
> CacheContext的132行设置了

哦哦, 升级新版果然有了
