### ISSUE TITLE
springboot2.2.2 版本出现redis依赖错误的问题

### ISSUE THREAD

**Issue by cxc3214** [alibaba/jetcache#444]
spring boot 版本 2.2.2.RELEASE
jedis 版本 <jedis.version>3.1.0</jedis.version>
启动用就报错：
`Caused by: java.lang.ClassNotFoundException: redis.clients.util.Pool`
使用的版本 2.5.16  2.6.0.M3 2.5.9 都没有用
`<dependency>
  <groupId>com.alicp.jetcache</groupId>
  <artifactId>jetcache-starter-redis</artifactId>
  <version>版本</version>
</dependency>`

**Comment by useiya** [comment]
https://github.com/alibaba/jetcache/wiki/RedisWithJedis_CN#常见问题
强制直接依赖jedis版本2.9.0：

<dependency>
    <groupId>redis.clients</groupId>
    <artifactId>jedis</artifactId>
    <version>2.9.0</version>
</dependency>

**Comment by areyouok** [comment]
参考
https://github.com/alibaba/jetcache/issues/426

**Comment by fank243** [comment]
升级到2.6.0.RC可以启动的

https://www.yuque.com/fank243/devops/aqmaaq
