### ISSUE TITLE
api方式创建的缓存，无法定义name吗？

### ISSUE THREAD

**Issue by loveXiaoiao** [alibaba/jetcache#445]
使用API的方式创建缓存，如下：
`Cache<String, Integer> caffeineCachepeter = CaffeineCacheBuilder.createCaffeineCacheBuilder()
                .limit(100)
                .expireAfterWrite(200, TimeUnit.SECONDS)
                .keyConvertor(FastjsonKeyConvertor.INSTANCE)
                .buildCache();`
这种方式没有地方可以定义name，不像注解。那么其他地方我想操作这个缓存，我怎么拿到它呢？

如果是有name的缓存，目前通过这种方式能拿到：
`Cache cacheTest = springConfigProvider.getCacheManager().getCache(CacheConsts.DEFAULT_AREA, "loadUser");
      Cache cache = ((CacheHandler.CacheHandlerRefreshCache) cacheTest).getTargetCache();`

黄老师，请问有定义规范的获取已存在cache的方式吗？我看文档上没有，看源码也是通过name拿的。

**Comment by loveXiaoiao** [comment]
还有一个问题，顺便在这里问下，jetcache和springboot-actuator结合么，就是说metrics结果里有jetcache的数据么

**Comment by areyouok** [comment]
第一个问题，name本身就不是Cache的属性，它其实就是放到map里面的key，你自己按你想要的name放到CacheManager里面就行了。

第二个问题，现在没有。

**Comment by loveXiaoiao** [comment]
> 第一个问题，name本身就不是Cache的属性，它其实就是放到map里面的key，你自己按你想要的name放到CacheManager里面就行了。
> 
> 第二个问题，现在没有。

好的，谢谢答复
