### ISSUE TITLE
在使用mybatis的dao层中使用@Cached注解,但未缓存结果.

### ISSUE THREAD

**Issue by kklt1990** [alibaba/jetcache#45]
想在项目中使用mybatis的dao层中使用@Cached注解.测试并没有进行缓存方法的缓存结果.
![image](https://user-images.githubusercontent.com/25313758/39394941-a434eb56-4b0a-11e8-859d-b3ff20467c30.png)
例如在getUserByName方法上进行使用.
该如何使用?

**Comment by areyouok** [comment]
JetCache的方法缓存注解是用Spring的aop做的，所以加了注解的类需要注册成spring bean才可以工作。

**Comment by areyouok** [comment]
另外EnableMethodCache注解可以指定aop的顺序。

**Comment by kklt1990** [comment]
谢谢指导,问题已解决.

**Comment by imhuzi** [comment]
@kklt1990 具体如何做的呢？
