### ISSUE TITLE
需求: 可否增加 bom 文件方便 maven 和 gradle 项目的使用

### ISSUE THREAD

**Issue by zqq90** [alibaba/jetcache#452]
BOM (Bill of Materials)

比如: [junit-bom-5.6.0.pom](https://repo1.maven.org/maven2/org/junit/junit-bom/5.6.0/junit-bom-5.6.0.pom)

```groovy
dependencyManagement {
    imports {
        mavenBom "org.junit:junit-bom:5.6.0"
    }
}
```

**Comment by areyouok** [comment]
这玩意我还不会弄。你撸一个？

jetcache本身的依赖比较轻量简单，spring4.0以上，到目前最新的版本都可以，spring framework和spring boot版本配套就好，如果你用spring boot的话，这个应该是spring boot管理的。

但是因为jedis2.10以上版本有不兼容的API修改，实在没有办法用一份代码支持，所以jetcache2.6版本只能支持jedis3.1，2.5系列支持jedis2.9。

2.6发布的时候我准备在wiki中整理一个表格。
