### ISSUE TITLE
Consider revisiting the entries above or defining a bean named 'redisLettuceAutoInit' in your configuration

### ISSUE THREAD

**Issue by Skqing** [alibaba/jetcache#455]
`@Bean(name = "defaultClient")
    @DependsOn(RedisLettuceAutoConfiguration.AUTO_INIT_BEAN_NAME)
    public LettuceFactory defaultClient() {
        return new LettuceFactory("remote.default", RedisClusterClient.class);
    }`

**Comment by areyouok** [comment]
I can't understand what you mean.
