### ISSUE TITLE
tryLockAndRun设置超时时间之后，会进行自动刷新吗？

### ISSUE THREAD

**Issue by tawoli** [alibaba/jetcache#456]
例如：我设置了30秒的过期时间，若30秒之内没有释放锁，该锁会自动刷新吗（没有注解@CacheRefresh）？

**Comment by areyouok** [comment]
30秒以后就释放了，所以如果回调执行时间超过30秒，可能会发生重入。

**Comment by tawoli** [comment]
> 30秒以后就释放了，所以如果回调执行时间超过30秒，可能会发生重入。

d
