### ISSUE TITLE
@Cached 设置expire后偶发无效，redis中查看TTL为2147483648

### ISSUE THREAD

**Issue by sirouyang** [alibaba/jetcache#464]
spring boot 2.1.0.RELEASE
版本
`
<dependency>
            <groupId>com.alicp.jetcache</groupId>
            <artifactId>jetcache-starter-redis-lettuce</artifactId>
            <version>2.6.0</version>
</dependency>
`
用法
`
@CreateCache(name = XX.xx, cacheType = CacheType.REMOTE)
private Cache<Object, ScanEntity> xxCache;

@Cached(name = "XX.xx", cacheType = CacheType.REMOTE , expire = 35 ,localExpire =  35 , key = "#id")

public Xxxx xxxLxxx (String id) { 
     return Xxxx;
}
`
yaml配置
`
jetcache:
  statIntervalMinutes: 15
  areaInCacheName: false

  local:
    default:
      type: linkedhashmap
      keyConvertor: fastjson
      limit: 100
  remote:
    default:
      type: redis.lettuce
      keyConvertor: fastjson
      valueEncoder: java
      valueDecoder: java
      uri:
        - redis://paasword@127.0.0.1:6379/0
      poolConfig:
        minIdle: 5
        maxIdle: 20
        maxTotal: 50
`
出现问题重启项目后，可能大概率会正常，目测为一半一半

将上面xxCache改为
`
@CreateCache(name = XX.xx, cacheType = CacheType.REMOTE , expire = 35) 
private Cache<Object, ScanEntity> xxCache;
`
后正常

**Comment by sirouyang** [comment]
spring boot 2.1.0.RELEASE

**Comment by areyouok** [comment]
这两个注解都会创建Cache实例，取决于哪个先初始化，所以配置要一样。
