### ISSUE TITLE
集群一级缓存同步

### ISSUE THREAD

**Issue by 723854867** [alibaba/jetcache#477]
jetcache目前不支持一级缓存集群同步吧？后续版本会考虑吗？这个功能在实际业务中应用场景很广的，现在流行微服务，基本都是多节点集群部署的，如果没有一级缓存同步的话基本没法用！

**Comment by areyouok** [comment]
暂时不考虑了。可以把一级缓存超时时间设置的短一点，或者自己扩展。

如果要做成通用的考虑点比较多。

**Comment by 723854867** [comment]
谢了
