### ISSUE TITLE
keyconverter默认是fastjson 我可以用jackson序列化吗？ 应该怎么写呢？

### ISSUE THREAD

**Issue by conifercone** [alibaba/jetcache#488]

**Comment by Skyyyyyyyyy** [comment]
已解决

**Comment by scott17090025902** [comment]
怎么弄的啊，能说一下吗

**Comment by Skyyyyyyyyy** [comment]
> 怎么弄的啊，能说一下吗

`
@Override
      public Function<Object, Object> parseKeyConvertor(String convertor) {
        if (JACKSON.equalsIgnoreCase(convertor)) {
          return JacksonKeyConvertor.INSTANCE;
        }
        return super.parseKeyConvertor(convertor);
      }


public class JacksonKeyConvertor implements UnaryOperator<Object> {

    public static final JacksonKeyConvertor INSTANCE = new JacksonKeyConvertor();

    private final ObjectMapper objectMapper = new ObjectMapper();


    @Override
    public Object apply(Object originalKey) {
        if (originalKey == null) {
            return null;
        }
        if (originalKey instanceof String) {
            return originalKey;
        }
        try {
            return objectMapper.writeValueAsString(originalKey);
        } catch (JsonProcessingException e) {
            e.printStackTrace();
        }
        return null;
    }
}
`

**Comment by scott17090025902** [comment]
非常感谢，我去试一下

**Comment by icyfox-bupt** [comment]
@MercyFervor 
请问你这个修改方式是直接改源码了吗？
我试图不修改源码添加一个`KeyConvertor`，但是不知道在何处添加这个判断逻辑。

**Comment by MercyFervor** [comment]
@icyfox-bupt 其实是重写的SpringConfigProvider这个bean
`public static final String FASTJSON = "fastjson";

  public static final String JACKSON = "jackson";

  /**
   * 重写 SpringConfigProvider 中的编码和解码
   **/
  @Bean
  public SpringConfigProvider springConfigProvider() {

    return new SpringConfigProvider() {

      @Override
      public Function<byte[], Object> parseValueDecoder(String valueDecoder) {
        if (FASTJSON.equalsIgnoreCase(valueDecoder)) {
          return new FastJsonSerialPolicy().decoder();
        } else if (JACKSON.equalsIgnoreCase(valueDecoder)) {
          return new JacksonSerialPolicy().decoder();
        }
        return super.parseValueDecoder(valueDecoder);
      }

      @Override
      public Function<Object, byte[]> parseValueEncoder(String valueEncoder) {
        if (FASTJSON.equalsIgnoreCase(valueEncoder)) {
          return new FastJsonSerialPolicy().encoder();
        } else if (JACKSON.equalsIgnoreCase(valueEncoder)) {
          return new JacksonSerialPolicy().encoder();
        }
        return super.parseValueEncoder(valueEncoder);
      }

      @Override
      public Function<Object, Object> parseKeyConvertor(String convertor) {
        if (JACKSON.equalsIgnoreCase(convertor)) {
          return JacksonKeyConvertor.INSTANCE;
        }
        return super.parseKeyConvertor(convertor);
      }
    };
  }`
上述代码你可以创建一个配置类写在里面 然后在项目的配置文件中指定jetcache的编解码 类似这种
`jetcache:
  statIntervalMinutes: 15
  areaInCacheName: false
  local:
    default:
      type: caffeine
      keyConvertor: jackson
  remote:
    default:
      type: redis
      keyConvertor: jackson
      valueEncoder: jackson
      valueDecoder: jackson`

**Comment by icyfox-bupt** [comment]
@MercyFervor 感谢帮助

你的方法我尝试了，可以通过这个方法定义自己的`NameConvertor`和`KeyConvertor`

不过后来我发现在用户设置了annotation里的`name`或者`key`后，这两个convertor会被跳过

所以在用户定义了key的时候，我的需求还需要另找出路...

**Comment by areyouok** [comment]
spring context里面引入一个KeyConvertorParser bean是最简单的方式。

convertor不会被跳过。

如果指定了key属性会按key属性先评估key，然后再送入key convertor，产生的结果对于远程cache会再拼接一个前缀，这个前缀是全局前缀（默认没有设置）+cacheName。
