### ISSUE TITLE
兼容事务回滚机制吗？

### ISSUE THREAD

**Issue by flyshines** [alibaba/jetcache#49]

**Comment by areyouok** [comment]
jetcache不管事务，注解在方法上，如果方法发生异常，那么相关的缓存更新操作不会执行。

和spring cache一样，condition脚本用于方法执行前的条件判断，不满足条件不操作缓存。以前有unless用于方法执行后的条件判断，在某次改造中因为不好实现就去掉了，以后可能会再加上。
