### ISSUE TITLE
加载不到@Cached定义

### ISSUE THREAD

**Issue by Jinyun-Liu** [alibaba/jetcache#490]
Cache operation aborted because can't find @Cached definition || can't find @Cached definition with area=default name=userCache., specified in  ***
使用    @CacheUpdate(name = "userCache.", key = "#user.id", value = "#user")    @CacheInvalidate(name = "userCache.", key = "#id")  都出现了上面的问题，如何解决

**Comment by 985496501** [comment]
单元测试出现这个问题，应用一直用没有这个问题，这算是个bug吗？如何通过单元测试 调用呢

**Comment by siaron** [comment]
多个项目在一个项目里只使用 @Cached, 在另一个项目中使用@CacheInvalidate 就会出问题.
