### ISSUE TITLE
内存泄漏问题

### ISSUE THREAD

**Issue by zhouyuan015** [alibaba/jetcache#507]
用的redis.lettuce方式，运行一段时间经常会报 io.netty.util.ResourceLeakDetector : LEAK: ByteBuf.release() was not called before it's garbage-collected. See https://netty.io/wiki/reference-counted-objects.html for more information.

**Comment by zhouyuan015** [comment]
自己的原因，抱歉。关闭

**Comment by yoursBallerino** [comment]
> 自己的原因，抱歉。关闭

可以问下怎么解决的吗，我也遇到了，是netty版本的问题吗

**Comment by zhouyuan015** [comment]
> 



> 我



> 



> > 自己的原因，抱歉。关闭
> 
> 可以问下怎么解决的吗，我也遇到了，是netty版本的问题吗

内嵌用的是netty服务器，结果有开发又导入了个tomcat依赖，所导致的问题

>
