### ISSUE TITLE
不支持自定义的cacheInterceptor

### ISSUE THREAD

**Issue by Andreby42** [alibaba/jetcache#518]
可否提供思路用来改造aop拦截中的自定义cache name ，类如多租户标识，在aop中进行无感知加入name中

我看了下 大体是在 JetCacheInterceptor 这个类里面做的拦截操作，

谢谢！

**Comment by Andreby42** [comment]
搞定了，重写了JetCacheInterceptor  以及一系列的加载措施

**Comment by majiajue** [comment]
> 搞定了，重写了JetCacheInterceptor 以及一系列的加载措施

你重写以后怎么生效的，我现在就是不生效
