### ISSUE TITLE
使用本地缓存，但需要永久保留在内存中，请问怎么操作？limit不能受限

### ISSUE THREAD

**Issue by zhanghonglei1015** [alibaba/jetcache#521]
使用本地缓存，但需要永久保留在内存中，请问怎么操作？limit不能受限

感谢解答~

**Comment by liu844869663** [comment]
好像不支持

**Comment by zhanghonglei1015** [comment]
> 好像不支持

之前用EhCache，还能写到磁盘里，起码不用担心数据丢失，jetCache本地缓存用不好，没准数据丢了。。。

**Comment by zhanghonglei1015** [comment]
> 不设置expire可以吗？

是limit限制的，不是expire，expire默认是无穷大

**Comment by liu844869663** [comment]
好像必须设置 limit ，如果没有设置的话本地缓存全局的 limit 为100，永久保存在内存中，数据不需要更新吗？

**Comment by zhanghonglei1015** [comment]
> 好像必须设置 limit ，如果没有设置的话本地缓存全局的 limit 默认取100，永久保存在内存中，数据不需要更新吗？

更新是需要的，但业务场景是需要数据肯定得能取得到，更新时也会同步数据的，但不管更没更新，一段时间后，数据没了，那就尴尬了

**Comment by liu844869663** [comment]
缓存数据没了会继续执行原有方法返回数据并重新缓存，怎么会没了呢

**Comment by zhanghonglei1015** [comment]
> 缓存数据没了会继续执行原有方法返回数据并重新缓存，怎么会没了呢

直接使用啊，通过注入实例的方式，不是方法注解
官方也说了，方法注解只是方便，但不灵活，还是有些场景是需要直接使用cache实例的

**Comment by liu844869663** [comment]
> > 缓存数据没了会继续执行原有方法返回数据并重新缓存，怎么会没了呢
> 
> 直接使用啊，通过注入实例的方式，不是方法注解
> 官方也说了，方法注解只是方便，但不灵活，还是有些场景是需要直接使用cache实例的

那只能将localLimit设置为Integer.MAX_VALUE？

**Comment by zhanghonglei1015** [comment]
> > > 缓存数据没了会继续执行原有方法返回数据并重新缓存，怎么会没了呢
> > 
> > 
> > 直接使用啊，通过注入实例的方式，不是方法注解
> > 官方也说了，方法注解只是方便，但不灵活，还是有些场景是需要直接使用cache实例的
> 
> 那只能将localLimit设置为Integer.MAX_VALUE？

好像还真是这个，看源代码注释localExpire只有BOTH时有用，localLimit是LOCAL和BOTH都有用，我试试先，多谢多谢~
