### ISSUE TITLE
开启自动刷新时，本地缓存达到容量淘汰后，自动刷新的taskMap不会一起被淘汰

### ISSUE THREAD

**Issue by lynnllh** [alibaba/jetcache#538]
好像有个问题，开启自动刷新时，本地缓存达到最大值淘汰后，自动刷新的taskMap不会一起被淘汰。我设置本地缓存locallimit为3，在loader函数里面断点innerMap的数量是3，表示缓存淘汰生效，但是taskMap的数量不是3，这样历史访问的缓存key也会不停的刷新，并且会不断累计

**Comment by areyouok** [comment]
自动刷新不适合大量key的刷新，它基于stopRefreshAfterLastAccess来停止刷新
