### ISSUE TITLE
黄哥，Spring Aop 怎么配，大概的流程，谢谢

### ISSUE THREAD

**Issue by xty19** [alibaba/jetcache#54]
看了示例的测试代码，看了xml配置文件，还是没弄明白。
问下，大概 的步骤，谢谢啊

**Comment by areyouok** [comment]
不需要直接配置spring aop。用spring boot吗？

**Comment by xty19** [comment]
@areyouok 
不使用spring boot

**Comment by areyouok** [comment]
这个文档“未使用SpringBoot的配置方式”部分已经很详细了：
https://github.com/alibaba/jetcache/wiki/GettingStarted_CN

如果你看不明白，应该去看一下spring的Configuration的用法。

**Comment by xty19** [comment]
@areyouok 
好的，谢谢，我这就看看

**Comment by xty19** [comment]
@areyouok 
谢谢了，自己太着急了，没看仔细。
在程序中，使用AnnotationConfigApplicationContext即可
