### ISSUE TITLE
请问多个key对应同一个model时，怎么做到同时清除？

### ISSUE THREAD

**Issue by wpl980** [alibaba/jetcache#56]
请问，对于以下这种情况，如何同时清除以userId和userName两个key的cache?
```java
public interface UserService {
    @Cached(name="userCache-", key="#userId", expire = 3600)
    User getUserById(long userId);

    @Cached(name="userCache-", key="#userName", expire = 3600)
    User getUserByUserName(String userName);

    @CacheInvalidate(name="userCache-", key="#userId")
    void deleteUser(long userId);
}
```

**Comment by areyouok** [comment]
现在的注解没这个能力，只能用cache api了。

需要吗？注解搞太复杂是否合适？这样行不：
```java
@CreateCache(name="userCache-", expire = 3600)
private Cache<Long,UserDO> cache;

public void deleteUser(Set userIds){
    ...
    cache.removeAll(userIds);
}

```

name和area相同就会得到同一个cache。

不过这样CreateCache注解和Cached注解的expire、cacheType等属性最好设置成一样的，一般来说CreateCache的定义会先初始化，那么cache的属性应该由CreateCache指定，但我并没有测试过。

**Comment by areyouok** [comment]
如果不放心，这种情况就全用Cache API好了。

**Comment by wpl980** [comment]
其实问题还是，有`#userId`和`#userName`两个key的cache，但是调用`deleteUser`的时候，只清除了前者的缓存，比如Spring Cache的key就支持`#result`来使用返回对象中的属性作为值，类似这样
```java
  @Cacheable(cacheNames="userCache-", key="#result.userId")
  User getUserByUserName(String userName);
```
这样的话，虽然方法参数不一样，但是key是一样的。

**Comment by areyouok** [comment]
sepl里面现在确实不能访问result，我会加上。

现在的注解不能同时做多次缓存更新和失效，这个要看是否有简单的设计能实现这个功能。

**Comment by areyouok** [comment]
CacheUpdate和CacheInvalidate的脚本里面可以引用#result了，代码在master，当前master稳定可用。

这会覆盖同名的参数，我看spring也是这么干的。

**Comment by wpl980** [comment]
最好`Cached`也能支持，但可能改动有些大。

**Comment by areyouok** [comment]
Cached的key属性是不可能支持的，为了取到result把方法都执行了，还要缓存有什么用。

Spring的condition和unless属性一个在方法执行前评估，一个在方法执行后，jetcache以前都有的，后来的改造中把unless去掉了。我回头要想想怎么才能加上。

**Comment by wpl980** [comment]
也是，接下来能同时支持批量的缓存、更新和失效的话就更好了。

**Comment by areyouok** [comment]
批量注解改动会很大，先用cache api吧。

**Comment by areyouok** [comment]
2.5.1 Cached注解增加了postCondition可以访问result

**Comment by antonyhong** [comment]
希望加上类似Spring Cache 的 @Caching 注解这样就对多个key进行删除了

**Comment by YuanWenqing** [comment]
希望添加类似org.springframework.cache.annotation.Caching的支持

**Comment by JanYork** [comment]
如果我是这样的缓存Key，@Cached(name = "mail:", key = "'page_'+#page+#size", expire = 3600)，那我使用cache实例对象去removeAll()时，貌似我不能去获取到缓存的key，比较这个分页参数是动态的，不是固定的，那我如何去删除这类key的缓存？
