### ISSUE TITLE
需要多JetCache做压测流量染色，使用type：redis.springdata方式

### ISSUE THREAD

**Issue by lifaxin** [alibaba/jetcache#576]
需要多JetCache做压测流量染色，使用`type：redis.springdata`方式，这种如何动态切换redis库呢？

**Comment by lifaxin** [comment]
@areyouok

**Comment by areyouok** [comment]
你可以自己定制一个key convertor，有压测标记的话，加一个前缀。

**Comment by lifaxin** [comment]
自己定制key converter还是需要源码修改对吧， 我看fastjson方式是通过硬编码方式进行if判断的，如果增加，需要增加枚举和判断来实现 @areyouok

**Comment by lifaxin** [comment]
已经解决，感谢！
`
public class ShadowFastjsonKeyConvertor implements Function<Object, Object> {

    public static final ShadowFastjsonKeyConvertor INSTANCE = new ShadowFastjsonKeyConvertor();

    @Override
    public Object apply(Object originalKey) {
        if (originalKey == null) {
            return null;
        }
        if (originalKey instanceof String) {
            return shadowKey() + originalKey;
        }
        return shadowKey() + JSON.toJSONString(originalKey);
    }

    private String shadowKey(){
        return ShadowContext.isShadowEnv() ? "shadow-" : "";
    }
}
`


`
@Configuration
public class ShadowFastjsonKeyConfiguration {

    private static final String SHADOW_FASTJSON = "shadowFastJsonConvertor";

    @Bean
    public SpringConfigProvider springConfigProvider(){
        return new SpringConfigProvider(){
            @Override
            public Function<Object, Object> parseKeyConvertor(String convertor) {
                if (StringUtils.equals(SHADOW_FASTJSON, convertor)){
                    return ShadowFastjsonKeyConvertor.INSTANCE;
                }
                return super.parseKeyConvertor(convertor);
            }
        };
    }
}
`
