### ISSUE TITLE
建议和感受

### ISSUE THREAD

**Issue by liyong1028826685** [alibaba/jetcache#58]
首先本人昨天开始阅读源码，里面的代码质量非常高，思想也非常不错，但是我刚看代码还是比较尴尬对一些写法要反复斟酌才能明白，桌子是否可用在一些代码做一些注释这样入手效率会大大增加。
---谢谢。

**Comment by areyouok** [comment]
感谢关注。有问题可以直接问我。开发文档以后也要完善。

现在注释是不能写中文的，我英语比较渣就不想多写。

**Comment by liyong1028826685** [comment]
ok，好的！
