### ISSUE TITLE
tryLockAndRun问题咨询

### ISSUE THREAD

**Issue by 66xc1** [alibaba/jetcache#61]
tryLockAndRun是否能实现，多线程并发修改某个key的value，不会出现数据混乱的情况？我尝试了下，如果key被锁了，其他线程访问会返回结果false。

**Comment by areyouok** [comment]
tryLockAndRun的代码很简单，就在Cache接口的default方法里面，你可以看看。返回false，代表没有执行。

它是不严格的分布式锁，redis发生主备切换并且备机丢失数据的情况下，可能会有两个线程同时得到锁，当然这个概率很低。

如果你只是维护缓存中的数据，也可以考虑remove相关的缓存。看这个文章：
https://coolshell.cn/articles/17416.html

**Comment by 66xc1** [comment]
主要是看到你这个方法，设想是否可以拿来做锁控制，某些场景，比如抢火车票，预先把一定数量的票放入缓存，然后用户并发抢票，可以正常进行，而不会发生多扣的情况。

**Comment by areyouok** [comment]
如果是减库存类的需求，你要考虑两种情况：
1. tryLockAndRun是不严格的分布式锁，所以存在两个线程同时得到锁的可能性。
2. 如果锁定成功但是返回失败，其它线程都无法进入直到超时，所以要设定合理的超时时间

我觉得tryLockAndRun最适合跑定时任务。只需要很简单的代码，就能实现分布式定时任务。当然由于锁不严格，所以任务必须实现为幂等的（可重入）。
