### ISSUE TITLE
关于unless

### ISSUE THREAD

**Issue by areyouok** [alibaba/jetcache#62]
spring的注解里面有个unless属性，在方法调用后执行，可以用#result来访问方法结果，如果unless的SpEL评估为true，则否决相关的缓存操作。这个属性可以用来控制对某些结果不进行缓存。

jetcache以前也有unless属性的（一些属性和spring一样便于熟悉学习），后来因为一些原因去掉了。

现在已经重新实现了unless功能（未push），不过我在想，unless这个名字实在是有歧义，而且和condition是反着的，condition评估为false会否决缓存操作，unless则是为true否决，从字面上很难想到，而且也很绕。

我想将unless改名为postCondition，和condition一样，也是评估为false才否决，这样会比较清晰，不知如何？

**Comment by areyouok** [comment]
先提交再改

**Comment by lakehuang** [comment]
@areyouok 有一个问题就是如果condition评估为false，会缓存结果吗

**Comment by greatwqs** [comment]
5年后再翻到此issue, 看到楼主这样思考设计, 太棒了!

**Comment by greatwqs** [comment]
@lakehuang 

**Cached** 注解 有condition 和 postCondition 两个属性, 参考下面文档, 是否将结果缓存应该使用 postCondition 属性, 
```
@Cached(name = "jetcache::product::", key = "#productId", postCondition = "#result != null", expire = 3600, cacheType = CacheType.REMOTE)
```
属性 | 说明
-- | --
condition | 使用SpEL指定条件，如果表达式返回true的时候才去缓存中查询
postCondition | 使用SpEL指定条件，如果表达式返回true的时候才更新缓存，该评估在方法执行后进行，因此可以访问到#result

https://github.com/alibaba/jetcache/blob/master/docs/CN/MethodCache.md
