### ISSUE TITLE
开启自动刷新但未设置stopRefreshAfterLastAccess时，会导致内存泄漏

### ISSUE THREAD

**Issue by Xie-Jian** [alibaba/jetcache#640]
stopRefreshAfterLastAccess 默认值是 0（不停止）时，无论缓存是否过期，RefreshTask 都还存在，这样随着缓存过的 key 的增加 RefreshTask 也持续增加，导致占用大量内存。是否考虑对 stopRefreshAfterLastAccess 设置一个正值，或者限定 RefreshTask 的容量来解决这个问题呢？

**Comment by areyouok** [comment]
感觉stopRefreshAfterLastAccess设置默认值的话多少都不合适，限定容量也是一样。

考虑到cache刷新本来就不是默认打开的，所以手工开启刷新的时候，就要考虑这方面的问题，设置好相关参数。

此外，带参数（并且候选值很多）的方法一般来说是不该开启刷新的。

**Comment by Xie-Jian** [comment]
确实是这样，最后一句“此外，带参数（并且候选值很多）的方法一般来说是不该开启刷新的”没太理解什么意思，可以举个例子吗？

**Comment by areyouok** [comment]
getUserById(long userId)

**Comment by AVP42** [comment]
是否考虑下过滤功能，对某些热点key，不希望其过期才开启自动刷新？
