### ISSUE TITLE
如果是二级缓存，是否有办法只移除本地缓存且可指定获取Remote缓存

### ISSUE THREAD

**Issue by weidedong** [alibaba/jetcache#66]
@Data
@Component
public class CommonDataCache {
    @CreateCache(expire = 1,localExpire = CacheConsts.DEFAULT_EXPIRE ,cacheType = CacheType.BOTH,name = "common_data_cache.",timeUnit = TimeUnit.DAYS)
    private Cache<CommonDataType,Object> commonDataCache;
}

假如这是一个公共数据缓存，offline后台我会移除CommonDataCache的缓存，并且发布一个消息到客户端，客户端监听这个消息，我希望的操作是首先判断是否有远程缓存，如果有拉取到本地内存（覆盖本地缓存），如果没有，加分布式锁，更新二级缓存
但是我找不到获取远程的方法及更新本地缓存的方法，只能每个客户端都写一次二缓缓存，code如下
  @Override
    public void updateBrands() {
        List<CarBrand> brands = commonDataClient.getBrands();
        commonDataCache.getCommonDataCache().put(CommonDataType.BRAND,brands);
    }

**Comment by areyouok** [comment]
不是太明白你这样做的目的是什么。一般来说，本地设置一个较短的超时时间，超时以后，自然就从remote刷新了。

如果你需要得到多级缓存下面的本地和远程缓存，是有办法的，代码大概是这样，我手写的：

```
Cache c = commonDataCache;
while(c instanceof ProxyCache){
    c = c.getTargetCache();
}
Cache caches[] = ((MultiLevelCache)c).caches();
Cache local = caches[0];
Cache remote = cahces[1];
```

**Comment by weidedong** [comment]
我是想做一个公共数据实时刷新的功能，
多个客户端把公共数据本地缓存为永久，远程缓存缓存为一天，offline(后端维护页面)更新了公共数据此时刷新远程缓存，并发送公共数据过期消息，客户端监听到到过期消息，强制本地缓存过期，并重新拉取远程缓存数据

我拿到了local和remote，就能实现我所说的场景了吗，谢谢
Cache local = caches[0];
Cache remote = cahces[1];

**Comment by areyouok** [comment]
没有超时时间是不好的，通知消息可能会丢的，丢了你就永远错误了。
这个逻辑需要你自己实现。

较短的本地超时+较长的远程超时+自动刷新不行吗？

**Comment by weidedong** [comment]
嗯，是的。较短的本地超时+较长的远程超时+自动刷新。这个方案更好。谢谢啦
