### ISSUE TITLE
tryLock生成了uuid写入到了cache

### ISSUE THREAD

**Issue by weidedong** [alibaba/jetcache#67]
![tim 20180516131544](https://user-images.githubusercontent.com/24674401/40097923-6fa3e810-590b-11e8-91cd-fb4a43a0ab54.png)

如题

**Comment by weidedong** [comment]
如果key的value是string,那事实上无法判断这个值是个锁(guid)还是真正的value?

**Comment by areyouok** [comment]
如果同一个key，既要存你的值，又要用来加锁，你可以自己换个key嘛。

比如
```
cache.put(key)
cache.tryLock(key+"_lock")
```

**Comment by areyouok** [comment]
看来我应该自动加个后缀的，不过之前没有加，现在也不好改了。

**Comment by weidedong** [comment]
@CreateCache(expire = 1,localExpire = CacheConsts.DEFAULT_EXPIRE ,cacheType = CacheType.BOTH,name = "common_data_cache.",timeUnit = TimeUnit.DAYS)
    private Cache<CommonDataType,Object> commonDataCache;

**Comment by weidedong** [comment]
因为我的key用了enum，tryLock的key强制我传enum，所以有这个困惑

**Comment by areyouok** [comment]
现在如果让jetcache自动加个后缀，倒是很好做，不过就破坏兼容性了。

你可以把范型抹掉，然后传入一个字符串，是可以的。

Cache c = commonDataCache;
c.tryLock...(str_key...);

**Comment by weidedong** [comment]
ok,解决了，3q

**Comment by areyouok** [comment]
还有个办法是你自己fork了改一下， 这个还是很好改的。就是Cache接口上的默认方法。
