### ISSUE TITLE
关于缓存过期时间浮动支持

### ISSUE THREAD

**Issue by jxplus** [alibaba/jetcache#672]
你好，为解决缓存雪崩，一般会支持过期时间浮动配置，目前看下来只能自己另外加配置实现，请问后期有考虑@Cached注解增加支持浮动吗？

**Comment by areyouok** [comment]
暂不考虑。你可以用api编程

**Comment by jxplus** [comment]
嗯，那jetchache对雪崩场景是怎么考虑的，自动刷新吗

**Comment by areyouok** [comment]
> > 暂不考虑。你可以用api编程
> > 规划做法是自定义redis实现，读取配置中的每个key的浮动比率，重新计算expireTime，这样改动不大。
> > @areyouok 那jetchache对雪崩场景是怎么考虑的，自动刷新吗？

业务程序自己处理
