### ISSUE TITLE
如何扩展jetcache支持数据压缩

### ISSUE THREAD

**Issue by weidedong** [alibaba/jetcache#68]
我看ConfigProvider中已经写死了
if (SerialPolicy.KRYO.equalsIgnoreCase(valueEncoder)) {
return new KryoValueEncoder(useIdentityNumber);
} else if (SerialPolicy.JAVA.equalsIgnoreCase(valueEncoder)) {
return new JavaValueEncoder(useIdentityNumber);
} else {
throw new CacheConfigException("not supported:" + valueEncoder);
}
我应该如何扩展出一个支持压缩的序列化器，继承接口SerialPolicy? 我的计划是我在自己的项目新增code，不改变jetcache原有源码

要是能内置常见的压缩就好了。如lz4,gzip,zstd，并支持改变压缩比。当然为了兼容现有版本。可设置默认不启用压缩

**Comment by areyouok** [comment]
```
    @Bean
    public SpringConfigProvider springConfigProvider() {
        return new SpringConfigProvider() {
            @Override
            public Function<Object, byte[]> parseValueEncoder(String valueEncoder) {
                  if(valueEncode.equals("xxx")){
                       return MyEncoder();
                  }else{
                       return super.parseValueEncoder(valueEncoder);
                  }
            };
            @Override
            public Function<byte[], Object> parseValueDecoder(String valueDecoder) {
            }
    }
```

**Comment by weidedong** [comment]
perfect
