### ISSUE TITLE
注解写在了实现类的方法上，上层调用接口时注解不生效

### ISSUE THREAD

**Issue by noia-zhou** [alibaba/jetcache#701]
我把缓存注解标注在实现类的方法上，上层通过注入接口来调用方法，此时发现缓存注解不生效。
经过测试，如果直接注入实现类，此时缓存注解才起作用。  

我的问题是，在实现类上标注注解，在上层注入接口的情况下，如何才能让缓存生效？
`
	//注入实现类，缓存注解生效
	@Autowired
	UserRepositoryImpl userRepository;

        //注入接口，缓存注解不生效	！！！--》这种情况如何才能时注解生效？
	//@Autowired
	//UserRepository userRepository;
	
	@Test
	public void testGetByIdFormCache() {
		User user = userRepository.getById(1);
		log.info("查询结果为：{}",JsonUtils.toJsonStr(user));
		
		user = userRepository.getById(1);
		log.info("查询结果为：{}",JsonUtils.toJsonStr(user));
	}
`

**Comment by areyouok** [comment]
请给出一个可以重现的例子，可以基于samples目录下的例子修改

**Comment by noia-zhou** [comment]
感谢作者热心关注！这个问题解决了，是jdk8编译的问题，解决方式：
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-compiler-plugin</artifactId>
				<version>3.8.0</version>
				<configuration>
				    <compilerArgument>-parameters</compilerArgument><------------需要加上此参数
					<source>${java.version}</source>
					<target>${java.version}</target>
				</configuration>
			</plugin>
