### ISSUE TITLE
配置类问题

### ISSUE THREAD

**Issue by lhzsdnu** [alibaba/jetcache#704]
JetCache 2.7.0.RC3     Fastjson 2.0.10 

     Kryo5  测试正常
     RedisCacheBuilder.RedisCacheBuilderImpl remoteCacheBuilder = RedisCacheBuilder
                    .createRedisCacheBuilder()
                    .keyConvertor(Fastjson2KeyConvertor.INSTANCE)
                    .valueEncoder(Kryo5ValueEncoder.INSTANCE)
                    .valueDecoder(Kryo5ValueDecoder.INSTANCE)
                    .jedisPool(pool);
    
     Fastjson2 测试异常  异常信息：com.alicp.jetcache.support.CacheEncodeException: decode error
     RedisCacheBuilder.RedisCacheBuilderImpl remoteCacheBuilder = RedisCacheBuilder
                    .createRedisCacheBuilder()
                    .keyConvertor(Fastjson2KeyConvertor.INSTANCE)
                    .valueEncoder(Fastjson2ValueEncoder.INSTANCE)
                    .valueDecoder(Fastjson2ValueDecoder.INSTANCE)
                    .jedisPool(pool);
![image](https://user-images.githubusercontent.com/20517550/185725266-69ff1026-d01d-48d4-90a4-80c4fd943e92.png)

JetCache 2.7.0.RC3     Fastjson 2.0.11 

     Kryo5  测试异常 ，异常信息：java.lang.ExceptionInInitializerError
     RedisCacheBuilder.RedisCacheBuilderImpl remoteCacheBuilder = RedisCacheBuilder
                    .createRedisCacheBuilder()
                    .keyConvertor(Fastjson2KeyConvertor.INSTANCE)
                    .valueEncoder(Kryo5ValueEncoder.INSTANCE)
                    .valueDecoder(Kryo5ValueDecoder.INSTANCE)
                    .jedisPool(pool);
    
     Fastjson2 测试异常，异常信息：java.lang.ExceptionInInitializerError
     RedisCacheBuilder.RedisCacheBuilderImpl remoteCacheBuilder = RedisCacheBuilder
                    .createRedisCacheBuilder()
                    .keyConvertor(Fastjson2KeyConvertor.INSTANCE)
                    .valueEncoder(Fastjson2ValueEncoder.INSTANCE)
                    .valueDecoder(Fastjson2ValueDecoder.INSTANCE)
                    .jedisPool(pool);
![image](https://user-images.githubusercontent.com/20517550/185725227-78b67906-b19c-4950-8dc6-c200aad6a234.png)

**Comment by areyouok** [comment]
你得把异常贴出来吧？

**Comment by lhzsdnu** [comment]
补充截图了

**Comment by areyouok** [comment]
因为json做序列化兼容性不好，fastjson2作为encoder/decoder是没有注册的，你需要自己搞定。

置顶的2.7版本计划里面有说明。
