### ISSUE TITLE
CacheUpdate如何用返回值更新缓存

### ISSUE THREAD

**Issue by zhanyue76** [alibaba/jetcache#71]
spring cache中可以用@CachePut用方法返回的结果更新缓存，但是jetcache的@CacheUpdate必须指定value，而我的方法没有参数，如何实现更新

**Comment by areyouok** [comment]
更新到2.5.1就可以了。如果从2.3.3以前更新上来注意兼容性：
https://github.com/alibaba/jetcache/wiki/Compatibility_CN
