### ISSUE TITLE
springboot方式可以增加spring-boot-configuration-processor依赖吗，这样配置时候有提示友好一些

### ISSUE THREAD

**Issue by shuohao** [alibaba/jetcache#722]

**Comment by areyouok** [comment]
我不太会这个，如果你有兴趣可以考虑贡献

**Comment by shuohao** [comment]
> 我不太会这个，如果你有兴趣可以考虑贡献

看了下除了JetCacheProperties之外其他的local和remote下的配置并没有通过@ConfigurationProperties方式配置，这种情况下没法通过spring-boot-configuration-processor自动生成spring-configuration-metadata.json，只有JetCacheProperties可提示配置的太有限
