### ISSUE TITLE
关于JetCache分布式缓存

### ISSUE THREAD

**Issue by zhanyue76** [alibaba/jetcache#73]
有没有相关的分布式缓存的相关说明呢

如何在config里配置redis哨兵模式呢

**Comment by areyouok** [comment]
https://github.com/alibaba/jetcache/wiki/RedisWithLettuce_CN

**Comment by areyouok** [comment]
你spring的AnnotationConfigApplicationContext配置了没有

**Comment by zhanyue76** [comment]
嗯嗯，这个好了。但是启动的时候报错
caused by: java.lang.NoSuchMethodError: io.netty.buffer.ByteBufUtil.hexDump([BII)Ljava/lang/String;
是应为netty版本问题吗

**Comment by areyouok** [comment]
是，你看下lettuce依赖了什么版本，再看看实际部署包里面是什么版本
