### ISSUE TITLE
配置jetCache后一直创建redis连接是什么原因呢？

### ISSUE THREAD

**Issue by txyyf233** [alibaba/jetcache#744]
Springboot配置
![image](https://user-images.githubusercontent.com/40618765/201902692-03f72d43-8f62-42ff-8957-ed4032e87239.png)
服务器netstat
![image](https://user-images.githubusercontent.com/40618765/201902757-ec6c4e21-318b-4f6e-9ce0-8f34925cbb66.png)

**Comment by areyouok** [comment]
lettuce应该只有一个连接，加上做pubsub的那个应该是2个，你看看是不是出了什么错

**Comment by txyyf233** [comment]
非常感谢，问题已经解决，不是jetcache配置问题，是其他地方的sub问题

**Comment by Navicoder** [comment]
> 非常感谢，问题已经解决，不是jetcache配置问题，是其他地方的sub问题

你好啊 redis池的配置 minIdle是5 从你的截图来看，也是5个 应该没有问题啊

**Comment by Navicoder** [comment]
您的来信已收到， 谢谢！
