### ISSUE TITLE
通过api获取缓存统计

### ISSUE THREAD

**Issue by yunweiguo** [alibaba/jetcache#754]
目前是通过 CacheManager的方式创建的 缓存

 QuickConfig qc = QuickConfig.newBuilder("user:").cacheType(CacheType.BOTH) // two level cache
                .syncLocal(true) // invalidate local cache in all jvm process after update
                .build();
  userCache = cacheManager.getOrCreateCache(qc);

并全局配置了 15分钟的统计周期
jetcache:
  areaInCacheName: false
  statIntervalMinutes: 15

可以通过输出日志的方式获取到统计信息。

我目前是希望能通过api的方式（类似 caffeine框架的  CacheStats stats = userCache.stats()) 获取到 stat 对象。 但jetCache 框架的好像是不支持  stats()  获取到 stat 对象，后续有计划支持吗？ 或者说目前可以通过其他方式获取到统计对象

**Comment by yunweiguo** [comment]
看了下 issue 里面 有  https://github.com/alibaba/jetcache/issues/341 这个反馈，看了下demo ，好像是不满足需求

**Comment by areyouok** [comment]
搞一个类型为Consumer<StatInfo>的bean放到Spring context里面，通过配置statIntervalMinutes控制回调周期。

**Comment by yunweiguo** [comment]
可以了 感谢
