### ISSUE TITLE
2.7.0版本之后jetcahe-starter-redis中jedis版本控制与SpringBoot冲突的问题。

### ISSUE THREAD

**Issue by Kagenui-yozuru** [alibaba/jetcache#765]
2.7.0版本之后jetcahe-starter-redis依赖jedis4，jedis的版本是在 jetcache-parent 中通过<jedis.version>参数控制的，值为4.2.3。
但是SpringBoot的版本控制参数中有一个同名的参数。在SpringBoot2.7.5版本下对应的值为3.8.0。
实测之后发现SpringBoot的版本控制优先级更高，会覆盖 jetcache-parent 中的配置。导致jetcahe-starter-redis启动时报错。
<img src="https://yozuru-markdown.oss-cn-qingdao.aliyuncs.com/20230328192814.png"/>
(实际生效版本)
<img src="https://yozuru-markdown.oss-cn-qingdao.aliyuncs.com/20230328194613.png"/>
(手动解决冲突)

**Comment by areyouok** [comment]
如果你配置type: redis.springdata的话，那么jetcache使用spring-data（对应的start是jetcache-starter-redis-springdata）来访问redis，jedis的版本（如果你的spring-data使用jedis来访问redis的话）应该以spring-data为准。

否则如果你配置type: redis的话，你的jetcache将直接访问redis，此时不依赖spring-data，对应的starter是jetcache-starter-redis，应该以jetcache要求的jedis版本为准。

**Comment by qingquaner** [comment]
如果dependencyManagement加入jedis4.x，得确能解决在使用spring-data-redis情况下，jetcache无法找到类的问题，
但是项目集成其他框架(plumelog)，该框架使用了jedis3.x，就会出现两者只能二选一的尴尬局面

**Comment by areyouok** [comment]
你用jetcache-redis-springdata就能用jedis3了

samples目录下有例子

**Comment by clhey** [comment]
我理解楼主的问题是“jedis.version”这个参数名称和Springboot定义的一样，导致jetcache定义的redis版本无效，建议官方换个参数名称。

我这里也是同样的问题，我就是干净的依赖了jetcache，并没有使用spring-data-redis，然而jedis版本是3.6.3。
注意看红框，并不是依赖冲突：
![image](https://github.com/alibaba/jetcache/assets/7664669/51d6376b-8b2c-40c6-9f4e-dbf6d13d17b1)
![image](https://github.com/alibaba/jetcache/assets/7664669/65a7a316-ee44-40f2-bcd0-a4285fbf0768)

**Comment by areyouok** [comment]
@clhey 你能知道这个3.6.3是哪个依赖里面定义的吗？
