### ISSUE TITLE
Redis的Set,List数据结构支持的接口和读写分离

### ISSUE THREAD

**Issue by thelifeskygit** [alibaba/jetcache#77]
1、希望增加Redis的Set、List、pipeline等接口操作
2、希望增加Redis的读写分离

**Comment by areyouok** [comment]
2可以考虑，1暂时加不上。原因已经在别的issue里面讨论过了，可以用unwrap方法得到原始对象进行操作。

**Comment by areyouok** [comment]
等我有时间就看下，最近有点忙

**Comment by glpyh** [comment]
可以参考一下我弄的一个，不过没有使用unwrap，我是参考黄哥的文档弄的。[#76](https://github.com/alibaba/jetcache/issues/76)，现在我在项目是这么用的。

**Comment by areyouok** [comment]
读写分离的已经在RedisLettuceCache中实现。
