### ISSUE TITLE
required a bean of type 'com.alicp.jetcache.Cache' that could not be found.

### ISSUE THREAD

**Issue by xzqqqcom** [alibaba/jetcache#776]
springboot2.7.10 
springcloudalibaba2022.0.5.0 
jetcache2.7.3 

依赖：
            <dependency>
                <groupId>com.alicp.jetcache</groupId>
                <artifactId>jetcache-starter-redis-lettuce</artifactId>
                <version>${jetcache.version}</version>
            </dependency>

项目启动报错：required a bean of type 'com.alicp.jetcache.Cache' that could not be found.

定位错误代码：

	@Autowired
	private CacheManager cacheManager;
        private Cache<String,String> testCache;
	@PostConstruct
	public void init(){
		QuickConfig qc = QuickConfig.newBuilder("testCache")
				.expire(Duration.ofSeconds(100))
				.cacheType(CacheType.REMOTE) // two level cache
				.syncLocal(true) // invalidate local cache in all jvm process after update
				.build();
		testCache = cacheManager.getOrCreateCache(qc);
	}

找不到Cache 

启动类有注解@EnableMethodCache(basePackages="xxx此处省略")
配置文件都OK
换成2.6.x版本老写法也报一样的错误

**Comment by areyouok** [comment]
jetcache自己不会要求注入一个com.alicp.jetcache.Cache类型的bean，应该是你自己写的吧。

可以看看samples目录下的例子。

**Comment by xzqqqcom** [comment]
> jetcache自己不会要求注入一个com.alicp.jetcache.Cache类型的bean，应该是你自己写的吧。
> 
> 可以看看samples目录下的例子。

嗯找到原因了，是用了lombok的注解，改正之后报的另一个错误：
nested exception is com.alicp.jetcache.CacheConfigException: no remote cache builder: default
配置没有问题啊，从之前老项目用2.6版本复制过来的。。。

**Comment by xzqqqcom** [comment]
> jetcache自己不会要求注入一个com.alicp.jetcache.Cache类型的bean，应该是你自己写的吧。
> 
> 可以看看samples目录下的例子。

感谢大佬解决了，使用了lombok注解导致的！
