### ISSUE TITLE
@Cached 注解的enabled 我不是很懂怎么用

### ISSUE THREAD

**Issue by xiaoliu10** [alibaba/jetcache#787]
我测试过, 如果这个enabled 设置为fasle的时候, 当前方法执行的时候并不会执行缓存写入操作.
那用CacheContext.enableCache(() -> xxx(id)); 的时候只会执行一次查库操作也不会执行写操作.
那设置这个开关的目的在哪里呢,不是很明白. 如果不执行写入的话 缓存不会初始化出来 那这次调用不是一直不会命中缓存吗? 因为缓存不会写入.

**Comment by areyouok** [comment]
文档有写：

是否激活缓存。例如某个dao方法上加缓存注解，由于某些调用场景下不能有缓存，所以可以设置enabled为false，正常调用不会使用缓存，在需要的地方可使用CacheContext.enableCache在回调中激活缓存，缓存激活的标记在ThreadLocal上，该标记被设置后，所有enable=false的缓存都被激活

**Comment by xiaoliu10** [comment]
不好意思 可能是我这边测试方法有问题  现在理解了, 抱歉, issue 我关了
