### ISSUE TITLE
@Autowired方式拿不到JedisPool

### ISSUE THREAD

**Issue by wongben** [alibaba/jetcache#8]
> 如果需要直接操作JedisPool，可以通过以下方式获取
> 
> @Bean(name = "defaultPool")
> @DependsOn(RedisAutoConfiguration.AUTO_INIT_BEAN_NAME)
> public JedisPoolFactory defaultPool() {
>     return new JedisPoolFactory("remote.default");
> }
> 然后可以直接使用
> 
> @Autowired
> private JedisPool defaultPool;

报错：
Field defaultPool in com.alicp.jetcache.autoconfigure.StarterTest required a bean of type 'redis.clients.jedis.JedisPool' that could not be found.

估计容器里，只有JedisPoolFactory 没有JedisPool

**Comment by areyouok** [comment]
JedisPoolFactory是一个Spring的FactoryBean，它生成的对象就是JedisPool。

你看看还有没有别的配置问题。Spring的@Bean是需要定义在@Configuration标记的类里面的。

一些其他提示：
1、RedisAutoConfiguration.AUTO_INIT_BEAN_NAME这个常量2.2以后才有，2.1直接用@DependsOn("redisAutoInit")。
2、new JedisPoolFactory("remote.default")，这里的default指向YML文件里面定义的名称，比如：
```
  remote:
    default:
      type: redis
```

**Comment by wongben** [comment]
```@RestController
@RequestMapping("/redis")
public class RedisController {
    @Autowired
    private JedisPool defaultPool;
// 这种方式可以, defaultPool.getObject().getResource().sadd("like_01","1","2","3");
//    @Autowired
//    private JedisPoolFactory defaultPool;
    
    @GetMapping("/test")
    public void redis() throws Exception {
        //defaultPool.getObject().getResource().sadd("like_01","1","2","3");
        defaultPool.getResource().sadd("like_01","1","2","3");
    }
}```
用这个方式是可以的，
@Autowired
private JedisPoolFactory defaultPool;
然后defaultPool.getObject().getResource().sadd("like_01","1","2","3");
否则报错
> Caused by: org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'redis.clients.jedis.JedisPool' available: expected at least 1 bean which qualifies as autowire candidate. Dependency annotations: {@org.springframework.beans.factory.annotation.Autowired(required=true)}

springboot:  1.5.1.RELEASE
jetcache: 2.2.0.Beta3

**Comment by areyouok** [comment]
我试了一下，JedisPoolFactory这个类和文档编写时略有变化，请这样写：
```
@Autowired
private Pool<Jedis> defaultPool;
```
