### ISSUE TITLE
有没有spring xml的集成例子

### ISSUE THREAD

**Issue by amwpynnwxf** [alibaba/jetcache#80]
好像只看到了yml和@Configuration 的集成模式，没看到xml的

**Comment by amwpynnwxf** [comment]
看到问题 #54 有提到这个问题，但是很多项目的配置都统一配置在xml
感觉还是有必要demo里加上xml的集成

**Comment by areyouok** [comment]
单元测试的工程jetcache-test里面有，你先看看。

**Comment by areyouok** [comment]
这个xml时jetcache1.x时代的配置方式，所以没有CreateCache注解的支持。

我建议还是按Configuration的方式配置比较好，Spring的xml和Configuration注解是可以混用的。
