### ISSUE TITLE
同一个Spring Bean内部相互调用带有缓存注解的方法不能成功缓存？

### ISSUE THREAD

**Issue by linda8167** [alibaba/jetcache#82]
一个Spring Bean里面的b方法调用带缓存注解的a方法不能缓存？如果不能我该怎么处理？如果可以是我哪里有问题吗？
public class AService {
  	
       @Cached(name = "a:", key = "#arg")
	public String a(String arg) {
              //TODO
        }
        public String b(String arg){
             a(arg);
        }

}

**Comment by JoshShaw** [comment]
用jdk动态代理实现的jetcache的确做不了这个
