### ISSUE TITLE
CachePenetrationProtect 命名是否不妥？

### ISSUE THREAD

**Issue by CodingOX** [alibaba/jetcache#826]
CachePenetration 是指当一个请求查询缓存中不存在的数据时，每次都会直接访问数据库。而Jetcache的实现com.alicp.jetcache.AbstractCache#synchronizedLoad实际上是将针对同一个键的缓存请求处理为一个，以减少对数据库的访问。这个做法旨在解决缓存击穿问题（CacheBreakdown）。因此，命名为CacheBreakdownProtect，以更准确地描述其功能，是不是更好？

**Comment by areyouok** [comment]
这个别纠结了，名字不可能改了

**Comment by areyouok** [comment]
那兼容性也太差了

**Comment by CodingOX** [comment]
> 那兼容性也太差了

原始的注解 标记为 不推荐 并不做破坏性的更新
引入新注解 文档修改
代码再兼容新老2个注解

**Comment by areyouok** [comment]
主要是这个注解用了好多年了，我觉得还是将错就错保留更好，名字的问题不大
