### ISSUE TITLE
关于LinkedHashMapCache,麻烦问一下

### ISSUE THREAD

**Issue by weichanghuan** [alibaba/jetcache#83]
LinkedHashMapCache这个对象它在很多常用操作上面加上了内置锁synchronized，但在多线程操作下，会阻塞，这样我感觉还不如使用concurrenthashmap,或者不用内置锁，换成lock。

**Comment by weichanghuan** [comment]
难道我想错了。。。。

**Comment by areyouok** [comment]
LinkedHashMapCache只是一个简单的0依赖的Cache实现，没想做太复杂，它是线程安全的。

它的好处就是没有依赖。
