### ISSUE TITLE
批量删除

### ISSUE THREAD

**Issue by runzhenghengbin** [alibaba/jetcache#839]
@CacheInvalidate(name = WorkshopManagerCacheKey.WORKSHOP_USER,
        key = "#param.workshopId+':'+#param.userIds+':'+#param.tableSuffix",multi = true)
    boolean removeWorkshopUserBatch(WorkshopUserRemoveBatchParam param);

    @ApiModelProperty(value = "用户id")
    @NotNull(message = "用户id列表不能为空")
    @Size(min = 1, message = "用户id列表至少1个")
    private List<String> userIds;

    @ApiModelProperty(value = "分表依据")
    @NotBlank(message = "分表依据不能为空")
    private String tableSuffix;

    @ApiModelProperty(value = "工作坊id或者坊群组id")
    @NotBlank(message = "工作坊id或者坊群组id不能为空")
    private String workshopId;

这样是否可以删除？

**Comment by areyouok** [comment]
multi要求key是个数组或者Iterable，你这样不行的

**Comment by lingfengcoder** [comment]
> ```
> @CacheInvalidate(name = WorkshopManagerCacheKey.WORKSHOP_USER,
>     key = "#param.workshopId+':'+#param.userIds+':'+#param.tableSuffix",multi = true)
> boolean removeWorkshopUserBatch(WorkshopUserRemoveBatchParam param);
> 
> 
> @ApiModelProperty(value = "用户id")
> @NotNull(message = "用户id列表不能为空")
> @Size(min = 1, message = "用户id列表至少1个")
> private List<String> userIds;
> 
> @ApiModelProperty(value = "分表依据")
> @NotBlank(message = "分表依据不能为空")
> private String tableSuffix;
> 
> @ApiModelProperty(value = "工作坊id或者坊群组id")
> @NotBlank(message = "工作坊id或者坊群组id不能为空")
> private String workshopId;
> ```
> 
> 这样是否可以删除？

可以看看我fork出来并增强的版本，支持批量删除
![image](https://github.com/user-attachments/assets/ea048715-ee3e-4087-a78e-e6cb5d41b813)
坐标：https://github.com/lingfengcoder/jetcache/tree/2.7.8-GM-SNAPSHOT
