### ISSUE TITLE
麻烦问一下jetcache可以做同服务，多节点，本地缓存共享吗，

### ISSUE THREAD

**Issue by weichanghuan** [alibaba/jetcache#87]

**Comment by areyouok** [comment]
没看懂，详细描述

**Comment by zhuxixi** [comment]
应该想问集群部署中多节点缓存同步吧

**Comment by areyouok** [comment]
这个之前讨论过，要么用cacheType=CacheType.REMOTE，要么是cacheType=CacheType.BOTH设置一个比较短localExpire。

如果要同步不同服务器的local缓存，因素很多，目前并没有打算做。

**Comment by weichanghuan** [comment]
是的，我就这3楼的意思

**Comment by zhuxixi** [comment]
试了一下CacheRefresh，感觉有了这个功能集群多节点中也可以不同步缓存。

**Comment by areyouok** [comment]
用CacheRefresh也可以的
