### ISSUE TITLE
跟@Cached注解同一个类里面的方法 ，调用@Cached方法 不会走缓存吗？ 有没有什么办法

### ISSUE THREAD

**Issue by zhengjianfei111** [alibaba/jetcache#88]
@Cached(name = "UserService.UserUrl_", key = "#userId + '_'+ #Code", localLimit = 10 * 1024, localExpire = 600, expire = 1800, cacheType = CacheType.BOTH)
    public String getUserImageByKey(Integer userId, Integer imageKeyCode) {

    }
 
    public List<String> getImageHttpUrlsByKey(Integer userId, List<Key> list) {
        List<String> userImageList = new ArrayList<>(list.size());
        list.forEach(o -> {
            String url = this.getUserImageByKey(userId, o.getCode());
            userImageList.add(imageInfoDTO);
        });
        return userImageList;
    }
   如上  getImageHttpUrlsByKey  里面调 getUserImageByKey并不会走缓存， 是什么原因没有被切面拦截吗？

**Comment by areyouok** [comment]
#78
