### ISSUE TITLE
 能禁用默认值的序列化方式吗？

### ISSUE THREAD

**Issue by fishlikewater** [alibaba/jetcache#92]
或者可以针对每个@CreateCache 创建出来的缓存对象 单独设置序列化方式吗？

**Comment by areyouok** [comment]
必须可以啊。
CreateCache注解上有serialPolicy属性，内置了两种序列化器，如果你觉得不够用的话，自己做一个bean实现SerialPolicy接口，如果你的bean名字是myBean:
```
@CreateCache(serialPolicy="bean:myBean")
```
