### ISSUE TITLE
介绍中说过：“分布式缓存自动刷新”，请问集群下节点之间如何通信？如何避免重复回源？

### ISSUE THREAD

**Issue by lemon-simple** [alibaba/jetcache#93]
介绍中说过：“分布式缓存自动刷新”，请问集群下节点之间通信具体是怎么做的？如何避免重复回源数据库？

**Comment by areyouok** [comment]
实际上每个节点都尝试去刷新，但通过在远程缓存中的分布式锁，保证一个周期内只有一个节点执行了刷新操作。

**Comment by areyouok** [comment]
具体代码参考RefreshCache类

**Comment by lemon-simple** [comment]
除了回源的分布式锁。。节点之间还有什么通信吗？

**Comment by lemon-simple** [comment]
@areyouok 除了回源的分布式锁。。节点之间还有什么通信机制吗？

**Comment by lemon-simple** [comment]
@areyouok 有没有分布式队列或容器

**Comment by areyouok** [comment]
节点间没有通信机制，要做这个太复杂了

**Comment by lemon-simple** [comment]
那如何能保证数据更新？会不会在一个节点做更新了，其余节点也多次更新？

**Comment by lemon-simple** [comment]
@areyouok 那节点之间内存数据不一致问题如何解决？

**Comment by lemon-simple** [comment]
@areyouok 大神，麻烦抽空详细说下哈。在做技术选型，时间有点急，麻烦您了

**Comment by areyouok** [comment]
不会啊，前面已经说过了，“通过在远程缓存中的分布式锁，保证一个周期内只有一个节点执行了刷新操作”。

严格说是这样的：
1. 如果cacheType=CacheType.LOCAL，那么多个节点会重复刷新。
1. 如果cacheType=CacheType.REMOTE，通过在远程缓存中的分布式锁，保证一个周期内只有一个节点执行了刷新操作。
1. 如果cacheType=CacheType.BOTH，即两级缓存，通过在远程缓存中的分布式锁，保证一个周期内只有一个节点执行了刷新操作。但是这个更新仅更新REMOTE，其它服务器本地的缓存不会更新。jetcache支持给远程和本地缓存设置不同的超时时间，所以你可以把本地缓存的超时时间设置短一点。

**Comment by lemon-simple** [comment]
@areyouok 好的 非常谢谢
