### ISSUE TITLE
请问有开发roadmap吗，比如之前有人反馈的提供监控接口（如Prometheus）

### ISSUE THREAD

**Issue by fwk1010** [alibaba/jetcache#931]
感觉现在很多都是bug反馈或使用反馈，功能或特性反馈的没有一个计划路线图

**Comment by areyouok** [comment]
没有roadmap，我主要精力不在这，现在只做基本维护，你需要可以自己做，做的够好可以merge进来

**Comment by fwk1010** [comment]
@areyouok 好的谢谢，我closed了
