### ISSUE TITLE
怎么扩展jetcache的拉取远程缓存

### ISSUE THREAD

**Issue by XW512** [alibaba/jetcache#932]
目前，公司使用的redisTemplate的方式对redis进行操作，想通过扩展的方式把redisTemplate嵌入到jetcache中去，我应该如何进行扩展呢？我尝试过RedisLettuceCacheBuilder.createRedisLettuceCacheBuilder()的connection方式，发现redisTemplate获取不到StatefulConnection，通过转换方式转成AbstractRedisClient，但是公司封装死了redisTemplate，不允许改动，希望大佬告知下如何扩展，感谢感谢

**Comment by areyouok** [comment]
如果能拿到RedisConnectionFactory可以用jetcache-redis-springdata

**Comment by XW512** [comment]
> 如果能拿到RedisConnectionFactory可以用jetcache-redis-springdata

可以拿到，我试下哈，感谢感谢
