### ISSUE TITLE
多节点下，更新缓存，其它节点本地缓存没有失效

### ISSUE THREAD

**Issue by cemian** [alibaba/jetcache#945]
springboot 3.3.0
jetcache 2.7.7
redisson-spring-boot-starter 3.35.0

使用@CreateCache注解，syncLocal = true, cacheType = CacheType.BOTH

notify-keyspace-events：Egx$

jetcache:
  statIntervalMinutes: 1
  areaInCacheName: false
  local:
    default:
      type: caffeine
      keyConvertor: fastjson2
      limit: 100
  remote:
    default:
      type: redisson
      redissonClient: redissonConfig
      broadcastChannel: ba-ad-broadcast
      keyConvertor: fastjson2
      defaultExpireInMillis: 10000
      keyPrefix: 'xxxx'

配置和依赖如上，我在本地以两个不同的端口号启动服务，通过其中一个端口更新缓存，另一个端口对应服务的本地缓存并没有得到更新

**Comment by vivikiki123** [comment]
遇到了相同的问题，请问你解决了吗？

**Comment by vivikiki123** [comment]
我也还没找到问题所在，找到了告诉你

**Comment by cemian** [comment]
> 我也还没找到问题所在，找到了告诉你

好的，感谢

**Comment by vivikiki123** [comment]
> > 我也还没找到问题所在，找到了告诉你
> 
> 好的，感谢

新建了项目测试，还是没有失效，问题原因还是没找到

**Comment by cemian** [comment]
> > > 我也还没找到问题所在，找到了告诉你
> > 
> > 
> > 好的，感谢
> 
> 新建了项目测试，还是没有失效，问题原因还是没找到

我找到原因了。如果你也是用的redisson你可以看下有设置过codec吗，Config.setCodec(new JsonJacksonCodec())。换成默认的编解码器就可以了，原因是在RedissonBroadcastManager.startSubscribe()方法里addListener监听的是byte[]
