### ISSUE TITLE
jetcache redis连接池如何配置？(spring boot)

### ISSUE THREAD

**Issue by ling49043171** [alibaba/jetcache#95]
---------------
jetcache:
  statIntervalMinutes: 15
  areaInCacheName: false
  local:
    default:
      type: linkedhashmap
      keyConvertor: fastjson
      limit: 100
  remote:
    default:
      type: redis
      keyConvertor: fastjson
      valueEncoder: java
      valueDecoder: java
      poolConfig:
        minIdle: 5
        maxIdle: 20
        maxTotal: 50
      host: 10.0.20.203
      port: 8000
      password:

--------------------------
使用以上redis配置会报以下警告，请问连接池如何配置？

[WARN ][4883192][2018/06/19 15:03:30,348][AbstractCache.java][35][http-nio-8080-exec-8][jetcache(RedisCache) GET error. key=[]. Exception=class redis.clients.jedis.exceptions.JedisConnectionException, Message:Could not get a resource from the pool]

[WARN ][4883202][2018/06/19 15:03:30,358][AbstractCache.java][35][http-nio-8080-exec-8][jetcache(RedisCache) PUT error. key=[]. Exception=class redis.clients.jedis.exceptions.JedisConnectionException, Message:Could not get a resource from the pool]

**Comment by areyouok** [comment]
错误是JedisConnectionException，你看看redis是否能连上，文档中的配置方式是没有问题的。

**Comment by ling49043171** [comment]
redis，连接接是否没有问题的。

我采用的链接方式有redisTemplate和jetcache 两种方式并存。

redisTemplate没有出现过连接池问题，只有jetcache有这个问题；并且我仔细对比了文档的中的配置，也没有出入，但是这个警告，实在令人不能安心。

**Comment by areyouok** [comment]
日志里面查看下每15分钟的统计信息。就知道是每次都没连上，还是有时因为连接池满没连上了。

现在的日志没有看到cause，也可以修改RedisCache.needLogStackTrace方法，让它把完整的stackTrace打印出来。或者你在那里打个断点看一下。

**Comment by ling49043171** [comment]
该问题已经解决。

原因：
我的测试环境是没有密码的，但是jecache装配redis pool的时候，根据是否有password这个属性判定的，而不是根据属性值是否为空判定。导致，AUTH sent, but no password异常，该异常没有被异常栈打印，而是转换为上面我提到的异常信息了。

解决办法：
直接删除 password属性(直接把值去掉是不可以的)

**Comment by areyouok** [comment]
感谢反馈，这块的日志需要优化一下。
之前主要是考虑到连接异常会比较常见，就没打印连接异常的stack
